// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: intent-db.lisp (pattern crud-gateway, backend: sqlite)

#![allow(unused_imports, dead_code)]

use rusqlite::{params, OptionalExtension};
use crate::db::error::DbResult;

impl MissionDB {
    pub fn migrate(&self) -> DbResult<()> {
        let conn = self.conn();

        conn.execute_batch("CREATE TABLE IF NOT EXISTS skill_topics (\n    topic TEXT PRIMARY KEY,\n    description TEXT,\n    aka TEXT,\n    allowed_tools TEXT,\n    file_path TEXT NOT NULL,\n    hit_count INTEGER NOT NULL DEFAULT 0,\n    last_hit_at TEXT,\n    fragment_count INTEGER NOT NULL DEFAULT 0,\n    total_lines INTEGER NOT NULL DEFAULT 0,\n    checksum TEXT,\n    created_at TEXT NOT NULL,\n    updated_at TEXT NOT NULL,\n    requires_json TEXT,\n    actions_json TEXT,\n    context_hooks_json TEXT,\n    embedding TEXT,\n    embedding_provider TEXT\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(skill_topics)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "topic") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN topic TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "description") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN description TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "aka") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN aka TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "allowed_tools") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN allowed_tools TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "file_path") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN file_path TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "hit_count") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN hit_count INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "last_hit_at") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN last_hit_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "fragment_count") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN fragment_count INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "total_lines") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN total_lines INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "checksum") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN checksum TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN created_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "updated_at") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN updated_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "requires_json") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN requires_json TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "actions_json") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN actions_json TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "context_hooks_json") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN context_hooks_json TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "embedding") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN embedding TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "embedding_provider") {
            conn.execute_batch("ALTER TABLE skill_topics ADD COLUMN embedding_provider TEXT")?;
        }


        conn.execute_batch("CREATE TABLE IF NOT EXISTS skill_blocks (\n    id TEXT PRIMARY KEY,\n    topic TEXT NOT NULL,\n    block_type TEXT NOT NULL,\n    title TEXT,\n    content TEXT NOT NULL,\n    sort_order INTEGER NOT NULL DEFAULT 0,\n    status TEXT NOT NULL DEFAULT 'active',\n    created_at TEXT NOT NULL,\n    updated_at TEXT NOT NULL\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(skill_blocks)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE skill_blocks ADD COLUMN id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "topic") {
            conn.execute_batch("ALTER TABLE skill_blocks ADD COLUMN topic TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "block_type") {
            conn.execute_batch("ALTER TABLE skill_blocks ADD COLUMN block_type TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "title") {
            conn.execute_batch("ALTER TABLE skill_blocks ADD COLUMN title TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "content") {
            conn.execute_batch("ALTER TABLE skill_blocks ADD COLUMN content TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "sort_order") {
            conn.execute_batch("ALTER TABLE skill_blocks ADD COLUMN sort_order INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "status") {
            conn.execute_batch("ALTER TABLE skill_blocks ADD COLUMN status TEXT DEFAULT 'active'")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE skill_blocks ADD COLUMN created_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "updated_at") {
            conn.execute_batch("ALTER TABLE skill_blocks ADD COLUMN updated_at TEXT")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_skill_blocks_topic ON skill_blocks(topic)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_skill_blocks_status ON skill_blocks(status)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS skill_versions (\n    id INTEGER PRIMARY KEY,\n    topic TEXT NOT NULL,\n    content TEXT NOT NULL,\n    checksum TEXT NOT NULL,\n    created_at TEXT NOT NULL\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(skill_versions)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE skill_versions ADD COLUMN id INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "topic") {
            conn.execute_batch("ALTER TABLE skill_versions ADD COLUMN topic TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "content") {
            conn.execute_batch("ALTER TABLE skill_versions ADD COLUMN content TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "checksum") {
            conn.execute_batch("ALTER TABLE skill_versions ADD COLUMN checksum TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE skill_versions ADD COLUMN created_at TEXT")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_skill_ver_topic ON skill_versions(topic)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS skill_executions (\n    id TEXT PRIMARY KEY,\n    skill_topic TEXT NOT NULL,\n    action_id TEXT NOT NULL,\n    status TEXT NOT NULL DEFAULT 'running',\n    steps_total INTEGER NOT NULL,\n    steps_completed INTEGER NOT NULL DEFAULT 0,\n    context_json TEXT,\n    error TEXT,\n    triggered_by TEXT NOT NULL DEFAULT 'manual',\n    created_at TEXT NOT NULL,\n    completed_at TEXT,\n    duration_ms INTEGER\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(skill_executions)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "skill_topic") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN skill_topic TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "action_id") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN action_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "status") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN status TEXT DEFAULT 'running'")?;
        }
        if !existing_cols.iter().any(|c| c == "steps_total") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN steps_total INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "steps_completed") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN steps_completed INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "context_json") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN context_json TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "error") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN error TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "triggered_by") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN triggered_by TEXT DEFAULT 'manual'")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN created_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "completed_at") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN completed_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "duration_ms") {
            conn.execute_batch("ALTER TABLE skill_executions ADD COLUMN duration_ms INTEGER")?;
        }


        Ok(())
    }

    // ========== skill_topics ==========

    pub fn skill_topic_hit(&self, topic: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE skill_topics SET hit_count = hit_count + 1, last_hit_at = datetime('now') WHERE topic = ?1",
            params![topic],
        )?;
        Ok(())
    }

    pub fn skill_topic_update_stats(&self, topic: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE skill_topics SET total_lines = ?1, checksum = ?2, updated_at = datetime('now') WHERE topic = ?3",
            params![total_lines, checksum, topic],
        )?;
        Ok(())
    }

    // ========== skill_blocks ==========

    pub fn skill_block_set_status(&self, id: &str) -> DbResult<bool> {
        let conn = self.conn();
        conn.execute(
            "UPDATE skill_blocks SET status = ?1, updated_at = datetime('now') WHERE id = ?2",
            params![status, id],
        )?;
        Ok(())
    }

}

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in *_custom.rs
// These signatures are locked by intent-db.lisp declarations.
// Rust compiler enforces your impl matches these exactly.
// ═══════════════════════════════════════════════════════════

pub trait MissionDBCustomLogic {
    /// Logic: INSERT OR REPLACE with timestamp management
    /// Table: skill_topics
    fn skill_topic_upsert(&self, topic: &str, description: Option<&str>, aka: Option<&str>, allowed_tools: Option<&str>, file_path: &str) -> DbResult<()>;

    /// Logic: full INSERT OR REPLACE with all extended fields
    /// Table: skill_topics
    fn skill_topic_upsert_full(&self, topic: &str, description: Option<&str>, aka: Option<&str>, allowed_tools: Option<&str>, file_path: &str, requires_json: Option<&str>, actions_json: Option<&str>, context_hooks_json: Option<&str>) -> DbResult<()>;

    /// Logic: SELECT * with struct mapping
    /// Table: skill_topics
    fn skill_topic_get(&self, topic: &str) -> DbResult<Option<SkillTopic>>;

    /// Logic: SELECT * ORDER BY topic with struct mapping
    /// Table: skill_topics
    fn skill_topic_list(&self) -> DbResult<Vec<SkillTopic>>;

    /// Logic: UPDATE embedding blob + provider WHERE topic
    /// Table: skill_topics
    fn skill_set_topic_embedding(&self, topic: &str, embedding: &[f32], provider: &str) -> DbResult<()>;

    /// Logic: deserialize all topic embedding blobs
    /// Table: skill_topics
    fn skill_load_topic_embeddings(&self) -> DbResult<Vec<(String, Vec<f32>)>>;

    /// Logic: topic, description WHERE embedding IS NULL
    /// Table: skill_topics
    fn skill_topics_missing_embedding(&self, limit: i64) -> DbResult<Vec<(String, String)>>;

    /// Logic: topic, description WHERE provider != current
    /// Table: skill_topics
    fn skill_topics_stale_embedding(&self, current_provider: &str, limit: i64) -> DbResult<Vec<(String, String)>>;

    /// Logic: LIKE search on topic + description + aka
    /// Table: skill_topics
    fn skill_search_topics(&self, query: &str) -> DbResult<Vec<SkillTopic>>;

    /// Logic: INSERT with FTS sync
    /// Table: skill_blocks
    fn skill_block_insert(&self, id: &str, topic: &str, block_type: &str, title: Option<&str>, content: &str, sort_order: i32) -> DbResult<()>;

    /// Logic: UPDATE content + FTS sync
    /// Table: skill_blocks
    fn skill_block_update(&self, id: &str, content: &str) -> DbResult<bool>;

    /// Logic: SELECT * WHERE topic AND status=active ORDER BY sort_order
    /// Table: skill_blocks
    fn skill_blocks_for_topic(&self, topic: &str) -> DbResult<Vec<SkillBlock>>;

    /// Logic: DELETE blocks + FTS cleanup WHERE topic
    /// Table: skill_blocks
    fn skill_blocks_delete_topic(&self, topic: &str) -> DbResult<usize>;

    /// Logic: FTS5 search with snippet + topic JOIN
    /// Table: skill_blocks
    fn skill_search_fts(&self, query: &str) -> DbResult<Vec<SkillSearchResult>>;

    /// Logic: DROP + recreate FTS table from skill_blocks
    /// Table: skill_blocks
    fn skill_rebuild_fts(&self) -> DbResult<()>;

    /// Logic: INSERT with auto-increment ID + timestamp
    /// Table: skill_versions
    fn skill_version_save(&self, topic: &str, content: &str, checksum: &str) -> DbResult<()>;

    /// Logic: SELECT * WHERE topic ORDER BY id DESC LIMIT
    /// Table: skill_versions
    fn skill_version_list(&self, topic: &str, limit: i64) -> DbResult<Vec<SkillVersion>>;

    /// Logic: SELECT * WHERE id
    /// Table: skill_versions
    fn skill_version_get(&self, id: i64) -> DbResult<Option<SkillVersion>>;

    /// Logic: INSERT with auto-timestamp
    /// Table: skill_executions
    fn skill_execution_insert(&self, id: &str, skill_topic: &str, action_id: &str, steps_total: i32, triggered_by: &str, context_json: Option<&str>) -> DbResult<()>;

    /// Logic: UPDATE status + steps + optional error + completion timestamp
    /// Table: skill_executions
    fn skill_execution_update(&self, id: &str, status: &str, steps_completed: i32, error: Option<&str>) -> DbResult<()>;

    /// Logic: same as above + explicit duration_ms
    /// Table: skill_executions
    fn skill_execution_update_with_duration(&self, id: &str, status: &str, steps_completed: i32, error: Option<&str>, duration_ms: i32) -> DbResult<()>;

    /// Logic: GROUP BY skill_topic: total, completed, failed, avg_duration
    /// Table: skill_executions
    fn skill_execution_stats(&self, topic: Option<&str>) -> DbResult<Vec<SkillExecutionStat>>;

    /// Logic: EXISTS WHERE status=running AND topic AND action_id
    /// Table: skill_executions
    fn skill_execution_is_running(&self, skill_topic: &str, action_id: &str) -> DbResult<bool>;

}

