// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: intent-db.lisp (crud-gateway, backend: sqlite)

#![allow(unused_imports, dead_code)]

use rusqlite::{params, OptionalExtension};
use crate::db::error::DbResult;

pub(crate) fn row_to_tool_call(row: &rusqlite::Row) -> rusqlite::Result<ToolCallRecord> {
    Ok(ToolCallRecord {
        id: row.get("id")?,
        session_id: row.get("session_id")?,
        message_id: row.get("message_id").unwrap_or(None),
        tool_name: row.get("tool_name")?,
        input_summary: row.get("input_summary").unwrap_or(None),
        raw_input: row.get("raw_input").unwrap_or(None),
        output_summary: row.get("output_summary").unwrap_or(None),
        raw_output: row.get("raw_output").unwrap_or(None),
        status: row.get("status").unwrap_or("pending".to_string()),
        duration_ms: row.get("duration_ms").unwrap_or(None),
        timestamp: row.get("timestamp")?,
    })
}

impl MissionDB {
    pub fn migrate(&self) -> DbResult<()> {
        let conn = self.conn();

        conn.execute_batch("CREATE TABLE IF NOT EXISTS conversation_tool_calls (\n    id TEXT PRIMARY KEY,\n    session_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,\n    message_id INTEGER,\n    tool_name TEXT NOT NULL,\n    input_summary TEXT,\n    raw_input TEXT,\n    output_summary TEXT,\n    raw_output TEXT,\n    status TEXT NOT NULL DEFAULT 'pending',\n    duration_ms INTEGER,\n    timestamp TEXT NOT NULL\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(conversation_tool_calls)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE conversation_tool_calls ADD COLUMN id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "session_id") {
            conn.execute_batch("ALTER TABLE conversation_tool_calls ADD COLUMN session_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "message_id") {
            conn.execute_batch("ALTER TABLE conversation_tool_calls ADD COLUMN message_id INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "tool_name") {
            conn.execute_batch("ALTER TABLE conversation_tool_calls ADD COLUMN tool_name TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "input_summary") {
            conn.execute_batch("ALTER TABLE conversation_tool_calls ADD COLUMN input_summary TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "raw_input") {
            conn.execute_batch("ALTER TABLE conversation_tool_calls ADD COLUMN raw_input TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "output_summary") {
            conn.execute_batch("ALTER TABLE conversation_tool_calls ADD COLUMN output_summary TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "raw_output") {
            conn.execute_batch("ALTER TABLE conversation_tool_calls ADD COLUMN raw_output TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "status") {
            conn.execute_batch("ALTER TABLE conversation_tool_calls ADD COLUMN status TEXT DEFAULT 'pending'")?;
        }
        if !existing_cols.iter().any(|c| c == "duration_ms") {
            conn.execute_batch("ALTER TABLE conversation_tool_calls ADD COLUMN duration_ms INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "timestamp") {
            conn.execute_batch("ALTER TABLE conversation_tool_calls ADD COLUMN timestamp TEXT")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_tc_session ON conversation_tool_calls(session_id)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_tc_name ON conversation_tool_calls(tool_name)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_tc_status ON conversation_tool_calls(status)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS conversation_events (\n    id INTEGER PRIMARY KEY,\n    session_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,\n    event_type TEXT NOT NULL,\n    content TEXT,\n    raw_data TEXT,\n    timestamp TEXT NOT NULL,\n    event_uuid TEXT\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(conversation_events)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE conversation_events ADD COLUMN id INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "session_id") {
            conn.execute_batch("ALTER TABLE conversation_events ADD COLUMN session_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "event_type") {
            conn.execute_batch("ALTER TABLE conversation_events ADD COLUMN event_type TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "content") {
            conn.execute_batch("ALTER TABLE conversation_events ADD COLUMN content TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "raw_data") {
            conn.execute_batch("ALTER TABLE conversation_events ADD COLUMN raw_data TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "timestamp") {
            conn.execute_batch("ALTER TABLE conversation_events ADD COLUMN timestamp TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "event_uuid") {
            conn.execute_batch("ALTER TABLE conversation_events ADD COLUMN event_uuid TEXT")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_conv_event_session ON conversation_events(session_id)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_conv_event_type ON conversation_events(event_type)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS conversations (\n    id TEXT PRIMARY KEY\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(conversations)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE conversations ADD COLUMN id TEXT")?;
        }


        conn.execute_batch("CREATE TABLE IF NOT EXISTS retrospective_results (\n    session_id TEXT PRIMARY KEY,\n    trigger_reason TEXT NOT NULL,\n    quick_stats TEXT NOT NULL,\n    full_analysis TEXT,\n    created_at TEXT NOT NULL DEFAULT (datetime('now'))\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(retrospective_results)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "session_id") {
            conn.execute_batch("ALTER TABLE retrospective_results ADD COLUMN session_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "trigger_reason") {
            conn.execute_batch("ALTER TABLE retrospective_results ADD COLUMN trigger_reason TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "quick_stats") {
            conn.execute_batch("ALTER TABLE retrospective_results ADD COLUMN quick_stats TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "full_analysis") {
            conn.execute_batch("ALTER TABLE retrospective_results ADD COLUMN full_analysis TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE retrospective_results ADD COLUMN created_at TEXT DEFAULT (datetime('now'))")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_retro_created ON retrospective_results(created_at)")?;

        Ok(())
    }

    // ========== conversation_tool_calls ==========

    pub fn insert_tool_call(&self, tc: &ToolCallRecord) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO conversation_tool_calls (id, session_id, message_id, tool_name, input_summary, raw_input, output_summary, raw_output, status, duration_ms, timestamp) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)",
            params![tc.id, tc.session_id, tc.message_id, tc.tool_name, tc.input_summary, tc.raw_input, tc.output_summary, tc.raw_output, tc.status, tc.duration_ms, tc.timestamp],
        )?;
        Ok(())
    }

    pub fn update_tool_call_output(&self, id: &str) -> DbResult<bool> {
        let conn = self.conn();
        conn.execute(
            "UPDATE conversation_tool_calls SET output_summary = ?1, raw_output = ?2, status = ?3 WHERE id = ?4",
            params![output_summary, raw_output, status, id],
        )?;
        Ok(())
    }

    pub fn get_tool_call_by_id(&self, id: &str) -> DbResult<Option<ToolCallRecord>> {
        let conn = self.read_conn();
        conn.query_row(
            "SELECT * FROM conversation_tool_calls WHERE id = ?1",
            params![id],
            |row| row_to_tool_call(row),
        )
        .optional()
        .map_err(Into::into)
    }

    pub fn count_pending_tool_calls(&self) -> DbResult<i64> {
        let conn = self.read_conn();
        let count: i64 = conn.query_row("SELECT COUNT(*) FROM conversation_tool_calls", [], |row| row.get(0))?;
        Ok(count)
    }

    // ========== conversations ==========

    pub fn mark_conversation_analyzed(&self, id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE conversations SET analyzed_at = datetime('now') WHERE id = ?1",
            params![id],
        )?;
        Ok(())
    }

    pub fn complete_conversation(&self, id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE conversations SET status = 'completed', ended_at = datetime('now'), updated_at = datetime('now') WHERE id = ?1",
            params![id],
        )?;
        Ok(())
    }

    pub fn save_conversation_exit_code(&self, id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE conversations SET exit_code = ?1, updated_at = datetime('now') WHERE id = ?2",
            params![exit_code, id],
        )?;
        Ok(())
    }

    pub fn mark_conversation_compacted(&self, id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE conversations SET status = 'compacted', updated_at = datetime('now') WHERE id = ?1",
            params![id],
        )?;
        Ok(())
    }

    pub fn set_conversation_task_id(&self, id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE conversations SET task_id = ?1 WHERE id = ?2",
            params![task_id, id],
        )?;
        Ok(())
    }

    pub fn get_conversations_by_task_id(&self, task_id: &str) -> DbResult<Vec<Conversation>> {
        let conn = self.read_conn();
        let mut stmt = conn.prepare("SELECT * FROM conversations WHERE task_id = ?1")?;
        let rows = stmt.query_map(params![task_id], |row| /* TODO: row_to_fn */(row))?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    pub fn update_memory_forwarded_at(&self, session_id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE conversations SET memory_forwarded_at = ?1 WHERE session_id = ?2",
            params![memory_forwarded_at, session_id],
        )?;
        Ok(())
    }

    pub fn update_user_voice_forwarded_at(&self, session_id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE conversations SET user_voice_forwarded_at = ?1 WHERE session_id = ?2",
            params![user_voice_forwarded_at, session_id],
        )?;
        Ok(())
    }

    pub fn update_realtime_forwarded_at(&self, session_id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE conversations SET realtime_forwarded_at = ?1 WHERE session_id = ?2",
            params![realtime_forwarded_at, session_id],
        )?;
        Ok(())
    }

    // ========== retrospective_results ==========

    pub fn save_retrospective_result(&self, session_id: &str, trigger_reason: &str, quick_stats: &str, full_analysis: &str, created_at: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO retrospective_results (session_id, trigger_reason, quick_stats, full_analysis, created_at) VALUES (?1, ?2, ?3, ?4, ?5) ON CONFLICT (session_id) DO UPDATE SET trigger_reason = ?2, quick_stats = ?3, full_analysis = ?4",
            params![session_id, trigger_reason, quick_stats, full_analysis, created_at],
        )?;
        Ok(())
    }

    pub fn has_retrospective_result(&self, session_id: &str) -> DbResult<bool> {
        let conn = self.read_conn();
        let count: i64 = conn.query_row("SELECT COUNT(*) FROM retrospective_results WHERE session_id = ?1", params![session_id], |row| row.get(0))?;
        Ok(count)
    }

}

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in *_custom.rs
// These signatures are locked by intent-db.lisp declarations.
// Rust compiler enforces your impl matches these exactly.
// ═══════════════════════════════════════════════════════════

pub trait MissionDBCustomLogic {
    /// Logic: transaction loop INSERT OR IGNORE
    /// Table: conversation_tool_calls
    fn insert_tool_calls_batch(&self, calls: &[ToolCallRecord]) -> DbResult<usize>;

    /// Logic: optional tool_name IN filter, ORDER BY timestamp ASC
    /// Table: conversation_tool_calls
    fn get_tool_calls_by_session(&self, session_id: &str, tool_filter: Option<&[String]>, limit: i64) -> DbResult<Vec<ToolCallRecord>>;

    /// Logic: GROUP BY tool_name: total, completed, avg_duration
    /// Table: conversation_tool_calls
    fn get_tool_call_stats(&self, session_id: &str) -> DbResult<Vec<(String, i64, i64, i64)>>;

    /// Logic: SELECT DISTINCT session_id WHERE status=pending
    /// Table: conversation_tool_calls
    fn get_sessions_with_pending_tool_calls(&self) -> DbResult<Vec<String>>;

    /// Logic: SELECT DISTINCT session_id
    /// Table: conversation_tool_calls
    fn get_sessions_with_tool_calls(&self) -> DbResult<std::collections::HashSet<String>>;

    /// Logic: SELECT message_uuid, role, content for tool_use/tool_result messages
    /// Table: conversation_tool_calls
    fn get_messages_for_tool_call_backfill(&self, session_id: &str) -> DbResult<Vec<(String, String, String)>>;

    /// Logic: tool_name, status, input_summary, output_summary
    /// Table: conversation_tool_calls
    fn get_tool_calls_for_detailed_analysis(&self, session_id: &str) -> DbResult<Vec<(String, String, String, String)>>;

    /// Logic: tool_name, status, timestamp, duration_ms timeline
    /// Table: conversation_tool_calls
    fn get_tool_calls_with_status_timeline(&self, session_id: &str) -> DbResult<Vec<(String, String, String, String)>>;

    /// Logic: SELECT tool_name ORDER BY timestamp ASC
    /// Table: conversation_tool_calls
    fn get_tool_name_sequence(&self, session_id: &str) -> DbResult<Vec<String>>;

    /// Logic: failed tool calls: input, output, raw_output samples
    /// Table: conversation_tool_calls
    fn get_tool_error_samples(&self, session_id: &str, tool_name: &str) -> DbResult<Vec<(String, String, String)>>;

    /// Logic: transaction loop INSERT OR IGNORE with dedup on (session_id, event_uuid)
    /// Table: conversation_events
    fn insert_conversation_events_batch(&self, events: &[ConversationEvent]) -> DbResult<usize>;

    /// Logic: dynamic WHERE with optional type/time filters
    /// Table: conversation_events
    fn get_conversation_events(&self, session_id: &str, event_type: Option<&str>, limit: i64, before: Option<&str>, after: Option<&str>) -> DbResult<Vec<ConversationEvent>>;

    /// Logic: EXISTS check for compact_boundary event
    /// Table: conversation_events
    fn is_compact_boundary_event(&self, session_id: &str, event_uuid: &str) -> DbResult<bool>;

    /// Logic: SELECT events + tool_calls interleaved, ORDER BY timestamp
    /// Table: conversation_events
    fn get_agent_trajectory(&self, session_id: &str) -> DbResult<Vec<serde_json::Value>>;

    /// Logic: GROUP BY event_type: count, first, last
    /// Table: conversation_events
    fn get_event_type_summary(&self, session_id: &str) -> DbResult<Vec<(String, i64, String, String)>>;

    /// Logic: DELETE WHERE created_at < cutoff for completed sessions
    /// Table: conversation_events
    fn cleanup_old_events(&self, cutoff: &str) -> DbResult<usize>;

    /// Logic: SELECT DISTINCT session_id
    /// Table: conversation_events
    fn get_sessions_with_events(&self) -> DbResult<std::collections::HashSet<String>>;

    /// Logic: SELECT id, jsonl_path WHERE jsonl_path IS NOT NULL
    /// Table: conversations
    fn get_conversations_with_jsonl(&self) -> DbResult<Vec<(String, String)>>;

    /// Logic: WHERE analyzed_at IS NULL AND status=completed
    /// Table: conversations
    fn get_unanalyzed_conversations(&self) -> DbResult<Vec<Conversation>>;

    /// Logic: UPDATE active → completed WHERE updated_at < cutoff AND slot active
    /// Table: conversations
    fn complete_stale_conversations(&self, cutoff: &str) -> DbResult<usize>;

    /// Logic: UPDATE status=active, clear ended_at WHERE completed/compacted
    /// Table: conversations
    fn reactivate_conversation(&self, id: &str) -> DbResult<usize>;

    /// Logic: sessions with unforwarded messages, today only, grouped by session
    /// Table: conversations
    fn get_pending_memory_messages(&self, today: &str) -> DbResult<Vec<(String, String, Vec<ConversationMessage>)>>;

    /// Logic: sessions with user_voice_forwarded_at IS NULL, grouped by session
    /// Table: conversations
    fn get_pending_user_voice_messages(&self) -> DbResult<Vec<(String, String, Vec<ConversationMessage>)>>;

    /// Logic: sessions with unforwarded realtime messages
    /// Table: conversations
    fn get_pending_realtime_messages(&self) -> DbResult<Vec<(String, String, Vec<ConversationMessage>)>>;

    /// Logic: same as above with LIMIT on sessions
    /// Table: conversations
    fn get_pending_realtime_messages_with_limit(&self, limit: usize) -> DbResult<Vec<(String, String, Vec<ConversationMessage>)>>;

    /// Logic: SELECT trigger_reason, quick_stats, full_analysis, created_at
    /// Table: retrospective_results
    fn get_retrospective_result(&self, session_id: &str) -> DbResult<Option<(String, String, Option<String>, String)>>;

    /// Logic: SELECT session_id, trigger_reason, quick_stats, full_analysis, created_at
    /// Table: retrospective_results
    fn list_retrospective_results(&self, limit: i64) -> DbResult<Vec<(String, String, String, Option<String>, String)>>;

    /// Logic: completed sessions without retro, with tool call stats
    /// Table: retrospective_results
    fn get_sessions_needing_retrospective(&self) -> DbResult<Vec<(String, i64, i64, f64)>>;

    /// Logic: same as above but with since filter and optional force
    /// Table: retrospective_results
    fn get_sessions_for_retro_backfill(&self, since: &str, force: bool) -> DbResult<Vec<(String, i64, i64, f64)>>;

    /// Logic: tool_name, total, completed, failed, avg_duration_ms from tool_calls
    /// Table: retrospective_results
    fn get_retrospective_tool_stats(&self, session_id: &str, limit: i64) -> DbResult<Vec<(String, i64, i64, i64, f64)>>;

    /// Logic: message_count, tool_count, user_msgs, assistant_msgs
    /// Table: retrospective_results
    fn get_retrospective_meta(&self, session_id: &str) -> DbResult<(i64, i64, i64, i64)>;

    /// Logic: detect consecutive same-tool streaks in tool_calls
    /// Table: retrospective_results
    fn get_retrospective_repeat_patterns(&self, session_id: &str, min_streak: i64) -> DbResult<Vec<(String, i64, String, String)>>;

    /// Logic: tool_name, error_rate, total_calls above threshold
    /// Table: retrospective_results
    fn get_retrospective_high_error_tools(&self, session_id: &str, min_error_rate: f64) -> DbResult<Vec<(String, f64, i64)>>;

    /// Logic: SELECT content FROM messages WHERE role=user ORDER BY id ASC LIMIT 1
    /// Table: retrospective_results
    fn get_first_user_message(&self, session_id: &str) -> DbResult<Option<String>>;

}

