// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: intent-db.lisp (crud-gateway, backend: sqlite)

#![allow(unused_imports, dead_code)]

use rusqlite::{params, OptionalExtension};
use crate::db::error::DbResult;

pub(crate) fn row_to_board_task(row: &rusqlite::Row) -> rusqlite::Result<BoardTask> {
    Ok(BoardTask {
        id: row.get("id")?,
        title: row.get("title")?,
        description: row.get("description").unwrap_or("".to_string()),
        status: { let s: String = row.get("status").unwrap_or_else(|_| "open".to_string()); board_task_status_from_str(&s) },
        priority: row.get("priority").unwrap_or("medium".to_string()),
        category: row.get("category").unwrap_or("other".to_string()),
        project: row.get("project").unwrap_or(None),
        server: row.get("server").unwrap_or(None),
        due_date: row.get("due_date").unwrap_or(None),
        parent_id: row.get("parent_id").unwrap_or(None),
        assignee: row.get("assignee").unwrap_or(None),
        auto_execute: { let v: i32 = row.get("auto_execute").unwrap_or(0); v != 0 },
        prompt_template: row.get("prompt_template").unwrap_or(None),
        hidden: { let v: i32 = row.get("hidden").unwrap_or(0); v != 0 },
        retry_count: row.get("retry_count").unwrap_or(0),
        max_retries: row.get("max_retries").unwrap_or(2),
        order_idx: row.get("order_idx").unwrap_or(0),
        created_at: row.get("created_at")?,
        updated_at: row.get("updated_at")?,
        claim_executor_id: row.get("claim_executor_id").unwrap_or(None),
        claim_executor_type: row.get("claim_executor_type").unwrap_or(None),
        claimed_at: row.get("claimed_at").unwrap_or(None),
        flow_phase: row.get("flow_phase").unwrap_or(None),
        flow_context: row.get("flow_context").unwrap_or(None),
        flow_template: row.get("flow_template").unwrap_or(None),
        depends_on: { let raw: String = row.get("depends_on").unwrap_or_else(|_| "{}".to_string()); serde_json::from_str(&raw).unwrap_or_default() },
        lease_expires_at: row.get("lease_expires_at").unwrap_or(None),
        dedupe_key: row.get("dedupe_key").unwrap_or(None),
        timeout_secs: row.get("timeout_secs").unwrap_or(None),
        context_intent: row.get("context_intent").unwrap_or(None),
        notes_count: row.get("notes_count").unwrap_or(0),
    })
}

pub(crate) fn row_to_board_task_note(row: &rusqlite::Row) -> rusqlite::Result<BoardTaskNote> {
    Ok(BoardTaskNote {
        id: row.get("id")?,
        task_id: row.get("task_id")?,
        content: row.get("content")?,
        note_type: { let s: String = row.get("note_type").unwrap_or_else(|_| "note".to_string()); board_note_type_from_str(&s) },
        author: row.get("author").unwrap_or(None),
        created_at: row.get("created_at")?,
    })
}

impl MissionDB {
    pub fn migrate(&self) -> DbResult<()> {
        let conn = self.conn();

        conn.execute_batch("CREATE TABLE IF NOT EXISTS board_tasks (\n    id TEXT PRIMARY KEY,\n    title TEXT NOT NULL,\n    description TEXT NOT NULL DEFAULT '',\n    status TEXT NOT NULL DEFAULT 'open',\n    priority TEXT NOT NULL DEFAULT 'medium',\n    category TEXT NOT NULL DEFAULT 'other',\n    project TEXT,\n    server TEXT,\n    due_date TEXT,\n    parent_id TEXT,\n    assignee TEXT,\n    auto_execute INTEGER NOT NULL DEFAULT 0,\n    prompt_template TEXT,\n    hidden INTEGER NOT NULL DEFAULT 0,\n    retry_count INTEGER NOT NULL DEFAULT 0,\n    max_retries INTEGER NOT NULL DEFAULT 2,\n    order_idx INTEGER NOT NULL DEFAULT 0,\n    created_at TEXT NOT NULL DEFAULT (datetime('now')),\n    updated_at TEXT NOT NULL DEFAULT (datetime('now')),\n    claim_executor_id TEXT,\n    claim_executor_type TEXT,\n    claimed_at TEXT,\n    flow_phase TEXT,\n    flow_context TEXT,\n    flow_template TEXT,\n    depends_on TEXT NOT NULL DEFAULT '[]',\n    lease_expires_at TEXT,\n    dedupe_key TEXT,\n    timeout_secs INTEGER,\n    context_intent TEXT,\n    notes_count INTEGER NOT NULL DEFAULT 0\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(board_tasks)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "title") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN title TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "description") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN description TEXT DEFAULT ''")?;
        }
        if !existing_cols.iter().any(|c| c == "status") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN status TEXT DEFAULT 'open'")?;
        }
        if !existing_cols.iter().any(|c| c == "priority") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN priority TEXT DEFAULT 'medium'")?;
        }
        if !existing_cols.iter().any(|c| c == "category") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN category TEXT DEFAULT 'other'")?;
        }
        if !existing_cols.iter().any(|c| c == "project") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN project TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "server") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN server TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "due_date") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN due_date TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "parent_id") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN parent_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "assignee") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN assignee TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "auto_execute") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN auto_execute INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "prompt_template") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN prompt_template TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "hidden") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN hidden INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "retry_count") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN retry_count INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "max_retries") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN max_retries INTEGER DEFAULT 2")?;
        }
        if !existing_cols.iter().any(|c| c == "order_idx") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN order_idx INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN created_at TEXT DEFAULT (datetime('now'))")?;
        }
        if !existing_cols.iter().any(|c| c == "updated_at") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN updated_at TEXT DEFAULT (datetime('now'))")?;
        }
        if !existing_cols.iter().any(|c| c == "claim_executor_id") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN claim_executor_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "claim_executor_type") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN claim_executor_type TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "claimed_at") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN claimed_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "flow_phase") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN flow_phase TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "flow_context") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN flow_context TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "flow_template") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN flow_template TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "depends_on") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN depends_on TEXT DEFAULT '[]'")?;
        }
        if !existing_cols.iter().any(|c| c == "lease_expires_at") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN lease_expires_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "dedupe_key") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN dedupe_key TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "timeout_secs") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN timeout_secs INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "context_intent") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN context_intent TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "notes_count") {
            conn.execute_batch("ALTER TABLE board_tasks ADD COLUMN notes_count INTEGER DEFAULT 0")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_board_tasks_status ON board_tasks(status)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_board_tasks_parent ON board_tasks(parent_id)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_board_tasks_category ON board_tasks(category)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_board_tasks_dedupe ON board_tasks(dedupe_key)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_board_tasks_order ON board_tasks(order_idx)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS board_task_notes (\n    id TEXT PRIMARY KEY,\n    task_id TEXT NOT NULL REFERENCES board_tasks(id) ON DELETE CASCADE,\n    content TEXT NOT NULL,\n    note_type TEXT NOT NULL DEFAULT 'note',\n    author TEXT,\n    created_at TEXT NOT NULL DEFAULT (datetime('now'))\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(board_task_notes)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE board_task_notes ADD COLUMN id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "task_id") {
            conn.execute_batch("ALTER TABLE board_task_notes ADD COLUMN task_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "content") {
            conn.execute_batch("ALTER TABLE board_task_notes ADD COLUMN content TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "note_type") {
            conn.execute_batch("ALTER TABLE board_task_notes ADD COLUMN note_type TEXT DEFAULT 'note'")?;
        }
        if !existing_cols.iter().any(|c| c == "author") {
            conn.execute_batch("ALTER TABLE board_task_notes ADD COLUMN author TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE board_task_notes ADD COLUMN created_at TEXT DEFAULT (datetime('now'))")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_board_task_notes_task ON board_task_notes(task_id)")?;

        Ok(())
    }

    // ========== board_tasks ==========

    pub fn insert_board_task(&self, task: &BoardTask) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO board_tasks (id, title, description, status, priority, category, project, server, due_date, parent_id, assignee, auto_execute, prompt_template, hidden, retry_count, max_retries, order_idx, created_at, updated_at, claim_executor_id, claim_executor_type, claimed_at, flow_phase, flow_context, flow_template, depends_on, lease_expires_at, dedupe_key, timeout_secs, context_intent, notes_count) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25, ?26, ?27, ?28, ?29, ?30, ?31)",
            params![task.id, task.title, task.description, board_task_status_to_str(task.status), task.priority, task.category, task.project, task.server, task.due_date, task.parent_id, task.assignee, task.auto_execute as i32, task.prompt_template, task.hidden as i32, task.retry_count, task.max_retries, task.order_idx, task.created_at, task.updated_at, task.claim_executor_id, task.claim_executor_type, task.claimed_at, task.flow_phase, task.flow_context, task.flow_template, serde_json::to_string(&task.depends_on).unwrap_or_else(|_| "{}".to_string()), task.lease_expires_at, task.dedupe_key, task.timeout_secs, task.context_intent, task.notes_count],
        )?;
        Ok(())
    }

    pub fn get_board_task_by_id(&self, id: &str) -> DbResult<Option<BoardTask>> {
        let conn = self.read_conn();
        conn.query_row(
            "SELECT * FROM board_tasks WHERE id = ?1",
            params![id],
            |row| row_to_board_task(row),
        )
        .optional()
        .map_err(Into::into)
    }

    pub fn list_board_tasks_by_status(&self, status: &str) -> DbResult<Vec<BoardTask>> {
        let conn = self.read_conn();
        let mut stmt = conn.prepare("SELECT * FROM board_tasks WHERE status = ?1 ORDER BY order_idx ASC")?;
        let rows = stmt.query_map(params![status], |row| row_to_board_task(row))?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    pub fn find_open_task_by_dedupe_key(&self, dedupe_key: &str) -> DbResult<Option<BoardTask>> {
        let conn = self.read_conn();
        conn.query_row(
            "SELECT * FROM board_tasks WHERE dedupe_key = ?1",
            params![dedupe_key],
            |row| row_to_board_task(row),
        )
        .optional()
        .map_err(Into::into)
    }

    pub fn set_board_task_lease(&self, id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE board_tasks SET lease_expires_at = ?1, updated_at = datetime('now') WHERE id = ?2",
            params![lease_expires_at, id],
        )?;
        Ok(())
    }

    pub fn release_board_claims_by_executor(&self, claim_executor_id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE board_tasks SET claim_executor_id = NULL, claim_executor_type = NULL, claimed_at = NULL, status = 'open', updated_at = datetime('now') WHERE claim_executor_id = ?1",
            params![claim_executor_id],
        )?;
        Ok(())
    }

    pub fn list_autopilot_tasks(&self) -> DbResult<Vec<BoardTask>> {
        let conn = self.read_conn();
        let mut stmt = conn.prepare("SELECT * FROM board_tasks ORDER BY CASE WHEN assignee IS NOT NULL THEN 0 ELSE 1 END, order_idx ASC")?;
        let rows = stmt.query_map([], |row| row_to_board_task(row))?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    pub fn list_running_autopilot_tasks(&self) -> DbResult<Vec<BoardTask>> {
        let conn = self.read_conn();
        let mut stmt = conn.prepare("SELECT * FROM board_tasks ORDER BY claimed_at ASC")?;
        let rows = stmt.query_map([], |row| row_to_board_task(row))?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    pub fn clear_done_board_tasks(&self) -> DbResult<i64> {
        let conn = self.conn();
        conn.execute(
            "DELETE FROM board_tasks",
            [],
        )?;
        Ok(())
    }

    pub fn count_tasks_by_category(&self, category: &str) -> DbResult<i64> {
        let conn = self.read_conn();
        let count: i64 = conn.query_row("SELECT COUNT(*) FROM board_tasks WHERE category = ?1", params![category], |row| row.get(0))?;
        Ok(count)
    }

    // ========== board_task_notes ==========

    pub fn insert_board_task_note(&self, task_id: &str, content: &str, note_type: &str, author: &str) -> DbResult<BoardTaskNote> {
        let id = uuid::Uuid::new_v4().to_string();
        let created_at = chrono::Utc::now().to_rfc3339();
        let conn = self.conn();
        conn.execute(
            "INSERT INTO board_task_notes (id, created_at, task_id, content, note_type, author) VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![id, created_at, task_id, content, note_type, author],
        )?;
        Ok(BoardTaskNote {
            id: id,
            task_id: task_id,
            content: content,
            note_type: note_type,
            author: author,
            created_at: created_at,
        })
    }

    pub fn get_board_task_notes(&self, task_id: &str) -> DbResult<Vec<BoardTaskNote>> {
        let conn = self.read_conn();
        let mut stmt = conn.prepare("SELECT * FROM board_task_notes WHERE task_id = ?1 ORDER BY created_at ASC")?;
        let rows = stmt.query_map(params![task_id], |row| row_to_board_task_note(row))?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

}

fn board_task_status_to_str(status: BoardTaskStatus) -> &'static str {
    match status {
        BoardTaskStatus::Open => "open",
        BoardTaskStatus::Running => "running",
        BoardTaskStatus::Verifying => "verifying",
        BoardTaskStatus::Done => "done",
        BoardTaskStatus::Blocked => "blocked",
        BoardTaskStatus::Failed => "failed",
        BoardTaskStatus::Skipped => "skipped",
    }
}

fn board_task_status_from_str(s: &str) -> BoardTaskStatus {
    match s {
        "open" => BoardTaskStatus::Open,
        "running" => BoardTaskStatus::Running,
        "verifying" => BoardTaskStatus::Verifying,
        "done" => BoardTaskStatus::Done,
        "blocked" => BoardTaskStatus::Blocked,
        "failed" => BoardTaskStatus::Failed,
        "skipped" => BoardTaskStatus::Skipped,
        _ => BoardTaskStatus::Open,
    }
}

fn board_note_type_to_str(status: BoardNoteType) -> &'static str {
    match status {
        BoardNoteType::Progress => "progress",
        BoardNoteType::Summary => "summary",
        BoardNoteType::Note => "note",
    }
}

fn board_note_type_from_str(s: &str) -> BoardNoteType {
    match s {
        "progress" => BoardNoteType::Progress,
        "summary" => BoardNoteType::Summary,
        "note" => BoardNoteType::Note,
        _ => BoardNoteType::Note,
    }
}

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in *_custom.rs
// These signatures are locked by intent-db.lisp declarations.
// Rust compiler enforces your impl matches these exactly.
// ═══════════════════════════════════════════════════════════

pub trait MissionDBCustomLogic {
    /// Logic: resolve parent_id, compute max order_idx, construct struct, insert
    /// Table: board_tasks
    fn create_board_task(&self, input: &CreateBoardTaskInput) -> DbResult<BoardTask>;

    /// Logic: dynamic SET with push_field macro, resolve parent_id/depends_on, auto-clear claims
    /// Table: board_tasks
    fn update_board_task(&self, id: &str, update: &UpdateBoardTaskInput) -> DbResult<Option<BoardTask>>;

    /// Logic: exact match, then prefix match for short IDs >= 6 chars
    /// Table: board_tasks
    fn resolve_board_task_id(&self, id: &str) -> DbResult<Option<String>>;

    /// Logic: resolve_board_task_id → get_board_task_by_id
    /// Table: board_tasks
    fn get_board_task(&self, id: &str) -> DbResult<Option<BoardTask>>;

    /// Logic: CAS: UPDATE WHERE status='open' AND claim_executor_id IS NULL
    /// Table: board_tasks
    fn claim_board_task(&self, id: &str, executor_id: &str, executor_type: &str) -> DbResult<Option<BoardTask>>;

    /// Logic: recursive descendant collection + cascade delete notes
    /// Table: board_tasks
    fn delete_board_task(&self, id: &str) -> DbResult<i64>;

    /// Logic: read-modify-write: open↔done toggle
    /// Table: board_tasks
    fn toggle_board_task(&self, id: &str) -> DbResult<Option<BoardTask>>;

    /// Logic: find open by dedupe_key → update to done
    /// Table: board_tasks
    fn close_task_by_dedupe_key(&self, dedupe_key: &str) -> DbResult<Option<BoardTask>>;

    /// Logic: dual-phase: lease-expired + fallback time-based recovery
    /// Table: board_tasks
    fn recover_stale_running_tasks(&self, fallback_stale_minutes: i64) -> DbResult<usize>;

    /// Logic: DAG traversal: check each dep status (done=ok, failed/skipped=blocked, else=pending)
    /// Table: board_tasks
    fn check_dependencies(&self, depends_on: &[TaskId]) -> DbResult<DependencyStatus>;

    /// Logic: BFS graph traversal over depends_on JSON arrays
    /// Table: board_tasks
    fn find_downstream_tasks(&self, task_id: &str) -> DbResult<Vec<String>>;

    /// Logic: reset target + optionally cascade-reset all downstream
    /// Table: board_tasks
    fn retry_board_task(&self, task_id: &str, reset_downstream: bool) -> DbResult<Vec<String>>;

    /// Logic: multi-table aggregation: status counts, pending questions, new KB entries
    /// Table: board_tasks
    fn board_summary(&self, since: Option<&str>) -> DbResult<serde_json::Value>;

    /// Logic: dynamic SQL builder with query/project/category/status/parent_id filters
    /// Table: board_tasks
    fn search_board_tasks(&self, input: &BoardSearchInput) -> DbResult<BoardSearchResult>;

    /// Logic: 3-query batch: main tasks → children → notes, assembled into tree
    /// Table: board_tasks
    fn get_board_tasks_with_context(&self, ids: &[String], include_children: bool) -> DbResult<Vec<BoardTaskWithContext>>;

    /// Logic: dynamic IN clause from priority list
    /// Table: board_tasks
    fn count_open_tasks_by_priority(&self, priorities: &[&str]) -> DbResult<i64>;

    /// Logic: whitelist column name, dynamic SQL, JSON row serialization
    /// Table: board_tasks
    fn query_board_tasks_in_range(&self, time_col: &str, since: &str, until: &str) -> DbResult<Vec<serde_json::Value>>;

    /// Logic: fixed SQL with 3 params, JSON row serialization
    /// Table: board_tasks
    fn query_board_tasks_in_range_with_status(&self, status: &str, since: &str, until: &str) -> DbResult<Vec<serde_json::Value>>;

    /// Logic: get_board_task → get_board_task_notes → compose
    /// Table: board_task_notes
    fn get_board_task_with_notes(&self, id: &str) -> DbResult<Option<BoardTaskWithNotes>>;

}

