// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: intent-db.lisp (crud-gateway, backend: sqlite)

#![allow(unused_imports, dead_code)]

use rusqlite::{params, OptionalExtension};
use crate::db::error::DbResult;

impl MissionDB {
    pub fn migrate(&self) -> DbResult<()> {
        let conn = self.conn();

        conn.execute_batch("CREATE TABLE IF NOT EXISTS backfill_progress (\n    phase TEXT PRIMARY KEY,\n    status TEXT NOT NULL DEFAULT 'pending',\n    last_cursor INTEGER NOT NULL DEFAULT 0,\n    total_estimated INTEGER NOT NULL DEFAULT 0,\n    processed INTEGER NOT NULL DEFAULT 0,\n    failed INTEGER NOT NULL DEFAULT 0,\n    started_at TEXT,\n    completed_at TEXT,\n    updated_at TEXT\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(backfill_progress)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "phase") {
            conn.execute_batch("ALTER TABLE backfill_progress ADD COLUMN phase TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "status") {
            conn.execute_batch("ALTER TABLE backfill_progress ADD COLUMN status TEXT DEFAULT 'pending'")?;
        }
        if !existing_cols.iter().any(|c| c == "last_cursor") {
            conn.execute_batch("ALTER TABLE backfill_progress ADD COLUMN last_cursor INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "total_estimated") {
            conn.execute_batch("ALTER TABLE backfill_progress ADD COLUMN total_estimated INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "processed") {
            conn.execute_batch("ALTER TABLE backfill_progress ADD COLUMN processed INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "failed") {
            conn.execute_batch("ALTER TABLE backfill_progress ADD COLUMN failed INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "started_at") {
            conn.execute_batch("ALTER TABLE backfill_progress ADD COLUMN started_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "completed_at") {
            conn.execute_batch("ALTER TABLE backfill_progress ADD COLUMN completed_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "updated_at") {
            conn.execute_batch("ALTER TABLE backfill_progress ADD COLUMN updated_at TEXT")?;
        }


        conn.execute_batch("CREATE TABLE IF NOT EXISTS backfill_failures (\n    session_id TEXT NOT NULL,\n    phase TEXT NOT NULL,\n    retry_count INTEGER NOT NULL DEFAULT 1,\n    last_error TEXT,\n    updated_at TEXT,\n    PRIMARY KEY ()\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(backfill_failures)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "session_id") {
            conn.execute_batch("ALTER TABLE backfill_failures ADD COLUMN session_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "phase") {
            conn.execute_batch("ALTER TABLE backfill_failures ADD COLUMN phase TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "retry_count") {
            conn.execute_batch("ALTER TABLE backfill_failures ADD COLUMN retry_count INTEGER DEFAULT 1")?;
        }
        if !existing_cols.iter().any(|c| c == "last_error") {
            conn.execute_batch("ALTER TABLE backfill_failures ADD COLUMN last_error TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "updated_at") {
            conn.execute_batch("ALTER TABLE backfill_failures ADD COLUMN updated_at TEXT")?;
        }


        conn.execute_batch("CREATE TABLE IF NOT EXISTS beacons (\n    id TEXT PRIMARY KEY,\n    name TEXT NOT NULL,\n    description TEXT,\n    created_at TEXT NOT NULL DEFAULT (datetime('now')),\n    updated_at TEXT NOT NULL DEFAULT (datetime('now')),\n    harvest_count INTEGER NOT NULL DEFAULT 0,\n    UNIQUE(name)\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(beacons)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE beacons ADD COLUMN id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "name") {
            conn.execute_batch("ALTER TABLE beacons ADD COLUMN name TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "description") {
            conn.execute_batch("ALTER TABLE beacons ADD COLUMN description TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE beacons ADD COLUMN created_at TEXT DEFAULT (datetime('now'))")?;
        }
        if !existing_cols.iter().any(|c| c == "updated_at") {
            conn.execute_batch("ALTER TABLE beacons ADD COLUMN updated_at TEXT DEFAULT (datetime('now'))")?;
        }
        if !existing_cols.iter().any(|c| c == "harvest_count") {
            conn.execute_batch("ALTER TABLE beacons ADD COLUMN harvest_count INTEGER DEFAULT 0")?;
        }


        conn.execute_batch("CREATE TABLE IF NOT EXISTS beacon_nodes (\n    beacon_id TEXT NOT NULL REFERENCES beacons(id) ON DELETE CASCADE,\n    repo TEXT NOT NULL,\n    file_path TEXT NOT NULL,\n    symbol_name TEXT NOT NULL,\n    annotation TEXT,\n    PRIMARY KEY ()\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(beacon_nodes)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "beacon_id") {
            conn.execute_batch("ALTER TABLE beacon_nodes ADD COLUMN beacon_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "repo") {
            conn.execute_batch("ALTER TABLE beacon_nodes ADD COLUMN repo TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "file_path") {
            conn.execute_batch("ALTER TABLE beacon_nodes ADD COLUMN file_path TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "symbol_name") {
            conn.execute_batch("ALTER TABLE beacon_nodes ADD COLUMN symbol_name TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "annotation") {
            conn.execute_batch("ALTER TABLE beacon_nodes ADD COLUMN annotation TEXT")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_bn_symbol ON beacon_nodes(symbol_name)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_bn_beacon ON beacon_nodes(beacon_id)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS consumer_watermarks (\n    consumer_name TEXT NOT NULL,\n    session_id TEXT NOT NULL,\n    last_processed_msg_id INTEGER,\n    last_processed_time TEXT,\n    extra TEXT,\n    PRIMARY KEY ()\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(consumer_watermarks)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "consumer_name") {
            conn.execute_batch("ALTER TABLE consumer_watermarks ADD COLUMN consumer_name TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "session_id") {
            conn.execute_batch("ALTER TABLE consumer_watermarks ADD COLUMN session_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "last_processed_msg_id") {
            conn.execute_batch("ALTER TABLE consumer_watermarks ADD COLUMN last_processed_msg_id INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "last_processed_time") {
            conn.execute_batch("ALTER TABLE consumer_watermarks ADD COLUMN last_processed_time TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "extra") {
            conn.execute_batch("ALTER TABLE consumer_watermarks ADD COLUMN extra TEXT")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_cw_consumer ON consumer_watermarks(consumer_name)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS message_labels (\n    message_id INTEGER NOT NULL,\n    label TEXT NOT NULL,\n    value TEXT,\n    source TEXT NOT NULL DEFAULT 'rule',\n    created_at TEXT NOT NULL DEFAULT (datetime('now')),\n    PRIMARY KEY ()\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(message_labels)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "message_id") {
            conn.execute_batch("ALTER TABLE message_labels ADD COLUMN message_id INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "label") {
            conn.execute_batch("ALTER TABLE message_labels ADD COLUMN label TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "value") {
            conn.execute_batch("ALTER TABLE message_labels ADD COLUMN value TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "source") {
            conn.execute_batch("ALTER TABLE message_labels ADD COLUMN source TEXT DEFAULT 'rule'")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE message_labels ADD COLUMN created_at TEXT DEFAULT (datetime('now'))")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_msg_label ON message_labels(label, value)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_msg_label_mid ON message_labels(message_id)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS message_translations (\n    message_id INTEGER PRIMARY KEY,\n    translation TEXT NOT NULL,\n    source_lang TEXT NOT NULL DEFAULT 'en',\n    target_lang TEXT NOT NULL DEFAULT 'zh',\n    model TEXT,\n    duration_ms INTEGER,\n    created_at TEXT NOT NULL DEFAULT (datetime('now'))\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(message_translations)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "message_id") {
            conn.execute_batch("ALTER TABLE message_translations ADD COLUMN message_id INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "translation") {
            conn.execute_batch("ALTER TABLE message_translations ADD COLUMN translation TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "source_lang") {
            conn.execute_batch("ALTER TABLE message_translations ADD COLUMN source_lang TEXT DEFAULT 'en'")?;
        }
        if !existing_cols.iter().any(|c| c == "target_lang") {
            conn.execute_batch("ALTER TABLE message_translations ADD COLUMN target_lang TEXT DEFAULT 'zh'")?;
        }
        if !existing_cols.iter().any(|c| c == "model") {
            conn.execute_batch("ALTER TABLE message_translations ADD COLUMN model TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "duration_ms") {
            conn.execute_batch("ALTER TABLE message_translations ADD COLUMN duration_ms INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE message_translations ADD COLUMN created_at TEXT DEFAULT (datetime('now'))")?;
        }


        Ok(())
    }

    // ========== backfill_progress ==========

    pub fn backfill_start_phase(&self, phase: &str, total_estimated: i64, started_at: &str, status: &str, updated_at: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO backfill_progress (phase, status, last_cursor, total_estimated, processed) VALUES (?1, ?2, ?3, ?4, ?5) ON CONFLICT (phase) DO UPDATE SET status = ?4, total_estimated = ?2, started_at = COALESCE(?3, started_at), updated_at = ?5",
            params![phase, total_estimated, started_at, status, updated_at],
        )?;
        Ok(())
    }

    pub fn backfill_update_progress(&self, phase: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE backfill_progress SET last_cursor = ?1, processed = ?2, failed = ?3, updated_at = datetime('now') WHERE phase = ?4",
            params![last_cursor, processed, failed, phase],
        )?;
        Ok(())
    }

    pub fn backfill_complete_phase(&self, phase: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE backfill_progress SET status = 'completed', completed_at = datetime('now'), updated_at = datetime('now') WHERE phase = ?1",
            params![phase],
        )?;
        Ok(())
    }

    // ========== backfill_failures ==========

    pub fn backfill_record_failure(&self, session_id: &str, phase: &str, last_error: &str, updated_at: &str, retry_count: i32) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO backfill_failures (session_id, phase, retry_count, last_error, updated_at) VALUES (?1, ?2, ?3, ?4, ?5) ON CONFLICT (session_id, phase) DO UPDATE SET retry_count = retry_count + 1, last_error = ?3, updated_at = ?4",
            params![session_id, phase, last_error, updated_at, retry_count],
        )?;
        Ok(())
    }

    pub fn backfill_clear_failure(&self, session_id: &str, phase: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "DELETE FROM backfill_failures WHERE session_id = ?1 AND phase = ?2",
            params![session_id, phase],
        )?;
        Ok(())
    }

    // ========== beacons ==========

    pub fn beacon_set_description(&self, name: &str) -> DbResult<bool> {
        let conn = self.conn();
        conn.execute(
            "UPDATE beacons SET description = ?1, updated_at = datetime('now') WHERE name = ?2",
            params![description, name],
        )?;
        Ok(())
    }

    // ========== beacon_nodes ==========

    pub fn beacon_node_upsert(&self, beacon_id: &str, repo: &str, file_path: &str, symbol_name: &str, annotation: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO beacon_nodes (beacon_id, repo, file_path, symbol_name, annotation) VALUES (?1, ?2, ?3, ?4, ?5) ON CONFLICT (beacon_id, repo, file_path, symbol_name) DO UPDATE SET annotation = COALESCE(?5, annotation)",
            params![beacon_id, repo, file_path, symbol_name, annotation],
        )?;
        Ok(())
    }

    // ========== consumer_watermarks ==========

    pub fn watermark_advance_time(&self, consumer_name: &str, session_id: &str, last_processed_time: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO consumer_watermarks (consumer_name, session_id, last_processed_msg_id) VALUES (?1, ?2, ?3) ON CONFLICT (consumer_name, session_id) DO UPDATE SET last_processed_time = ?3",
            params![consumer_name, session_id, last_processed_time],
        )?;
        Ok(())
    }

    pub fn watermark_advance_msg_id(&self, consumer_name: &str, session_id: &str, last_processed_msg_id: i64) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO consumer_watermarks (consumer_name, session_id, last_processed_msg_id) VALUES (?1, ?2, ?3) ON CONFLICT (consumer_name, session_id) DO UPDATE SET last_processed_msg_id = ?3",
            params![consumer_name, session_id, last_processed_msg_id],
        )?;
        Ok(())
    }

    // ========== message_labels ==========

    pub fn label_set(&self, message_id: i64, label: &str, value: &str, source: &str, created_at: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO message_labels (message_id, label, value, source, created_at) VALUES (?1, ?2, ?3, ?4, ?5) ON CONFLICT (message_id, label) DO UPDATE SET value = ?3, source = ?4",
            params![message_id, label, value, source, created_at],
        )?;
        Ok(())
    }

    // ========== message_translations ==========

    pub fn insert_translation(&self, message_id: i64, translation: &str, source_lang: &str, target_lang: &str, model: &str, duration_ms: i32, created_at: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO message_translations (message_id, translation, source_lang, target_lang, model, duration_ms, created_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7) ON CONFLICT (message_id) DO UPDATE SET translation = ?2, model = ?5, duration_ms = ?6",
            params![message_id, translation, source_lang, target_lang, model, duration_ms, created_at],
        )?;
        Ok(())
    }

    pub fn has_translation(&self, message_id: i64) -> DbResult<bool> {
        let conn = self.read_conn();
        let count: i64 = conn.query_row("SELECT COUNT(*) FROM message_translations WHERE message_id = ?1", params![message_id], |row| row.get(0))?;
        Ok(count)
    }

}

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in *_custom.rs
// These signatures are locked by intent-db.lisp declarations.
// Rust compiler enforces your impl matches these exactly.
// ═══════════════════════════════════════════════════════════

pub trait MissionDBCustomLogic {
    /// Logic: SELECT * WHERE phase, map to struct
    /// Table: backfill_progress
    fn backfill_get_phase(&self, phase: &str) -> DbResult<Option<BackfillPhaseStatus>>;

    /// Logic: SELECT * ORDER BY started_at
    /// Table: backfill_progress
    fn backfill_list_phases(&self) -> DbResult<Vec<BackfillPhaseStatus>>;

    /// Logic: WHERE retry_count < max AND cooldown elapsed, return session_ids
    /// Table: backfill_failures
    fn backfill_retryable_failures(&self, phase: &str, max_retries: i64, limit: i64) -> DbResult<Vec<String>>;

    /// Logic: COUNT WHERE retry_count < max (no cooldown check)
    /// Table: backfill_failures
    fn backfill_retryable_failures_no_cooldown(&self, phase: &str, max_retries: i64) -> DbResult<i64>;

    /// Logic: SELECT rowid, id FROM conversations WHERE no summary, rowid > cursor
    /// Table: backfill_failures
    fn conversations_missing_summary_cursor(&self, cursor: i64, limit: i64) -> DbResult<Vec<(i64, String)>>;

    /// Logic: SELECT rowid, id WHERE has embedding but no topic vectors, rowid > cursor
    /// Table: backfill_failures
    fn conversations_needing_topic_vectors_cursor(&self, provider: &str, cursor: i64, limit: i64) -> DbResult<Vec<(i64, String)>>;

    /// Logic: COUNT conversations without summary (user/worker types)
    /// Table: backfill_failures
    fn conversations_missing_summary_count(&self) -> DbResult<i64>;

    /// Logic: COUNT conversations with embedding but no topic vectors
    /// Table: backfill_failures
    fn conversations_needing_topic_vectors_count(&self, provider: &str) -> DbResult<i64>;

    /// Logic: SELECT with LEFT JOIN beacon_nodes for node_count
    /// Table: beacons
    fn beacon_list(&self) -> DbResult<Vec<BeaconInfo>>;

    /// Logic: INSERT OR IGNORE + return id (existing or new)
    /// Table: beacons
    fn beacon_ensure(&self, name: &str) -> DbResult<String>;

    /// Logic: UPDATE harvest_count + 1, return new count
    /// Table: beacons
    fn beacon_increment_harvest(&self, name: &str) -> DbResult<i64>;

    /// Logic: LIKE search on name + description + symbol_name
    /// Table: beacons
    fn beacon_search(&self, query: &str) -> DbResult<Vec<BeaconInfo>>;

    /// Logic: DELETE beacons with no beacon_nodes
    /// Table: beacons
    fn beacon_cleanup_empty(&self) -> DbResult<usize>;

    /// Logic: DELETE WHERE repo AND file_path
    /// Table: beacon_nodes
    fn beacon_nodes_delete_file(&self, repo: &str, file_path: &str) -> DbResult<usize>;

    /// Logic: JOIN beacons ON name → SELECT nodes + optional ast_nodes annotation
    /// Table: beacon_nodes
    fn beacon_map(&self, beacon_name: &str) -> DbResult<Vec<BeaconNode>>;

    /// Logic: UPDATE annotation via beacon name + symbol JOIN
    /// Table: beacon_nodes
    fn beacon_node_annotate(&self, beacon_name: &str, symbol_name: &str, annotation: &str) -> DbResult<bool>;

    /// Logic: SELECT msg_id, time WHERE consumer AND session
    /// Table: consumer_watermarks
    fn watermark_get(&self, consumer: &str, session_id: &str) -> DbResult<Option<(Option<i64>, Option<String>)>>;

    /// Logic: UPSERT with optional field updates via COALESCE
    /// Table: consumer_watermarks
    fn watermark_advance_full(&self, consumer: &str, session_id: &str, msg_id: Option<i64>, timestamp: Option<&str>, extra: Option<&str>) -> DbResult<()>;

    /// Logic: SELECT session_id, msg_id, time WHERE consumer
    /// Table: consumer_watermarks
    fn watermark_list(&self, consumer: &str) -> DbResult<Vec<(String, Option<i64>, Option<String>)>>;

    /// Logic: transaction loop: INSERT OR REPLACE for each label
    /// Table: message_labels
    fn label_set_batch(&self, labels: &[(i64, &str, &str, &str)]) -> DbResult<usize>;

    /// Logic: SELECT label, value, source WHERE message_id
    /// Table: message_labels
    fn label_get(&self, message_id: i64) -> DbResult<Vec<(String, String, String)>>;

    /// Logic: batch SELECT with IN clause, group by message_id
    /// Table: message_labels
    fn label_get_batch(&self, message_ids: &[i64]) -> DbResult<HashMap<i64, Vec<(String, String)>>>;

    /// Logic: SELECT message_id WHERE label AND optional value
    /// Table: message_labels
    fn label_find_messages(&self, label: &str, value: Option<&str>, limit: i64) -> DbResult<Vec<i64>>;

    /// Logic: SELECT translation, target_lang WHERE message_id
    /// Table: message_translations
    fn get_translation(&self, message_id: i64) -> DbResult<Option<(String, String)>>;

}

