// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: intent-db.lisp (pattern crud-gateway, backend: sqlite)

#![allow(unused_imports, dead_code)]

use rusqlite::{params, OptionalExtension};
use crate::db::error::DbResult;

pub(crate) fn row_to_knowledge_entry(row: &rusqlite::Row) -> rusqlite::Result<KnowledgeEntry> {
    Ok(KnowledgeEntry {
        id: row.get("id")?,
        category: row.get("category")?,
        key: row.get("key")?,
        summary: row.get("summary")?,
        detail: row.get("detail").unwrap_or(None),
        source: row.get("source").unwrap_or("conversation".to_string()),
        confidence: row.get("confidence").unwrap_or(1.0),
        access_count: row.get("access_count").unwrap_or(0),
        created_at: row.get("created_at")?,
        updated_at: row.get("updated_at")?,
        last_accessed_at: row.get("last_accessed_at").unwrap_or(None),
        linked_task_id: row.get("linked_task_id").unwrap_or(None),
        embedding: row.get("embedding").unwrap_or(None),
        embedding_provider: row.get("embedding_provider").unwrap_or(None),
        kb_type: row.get("kb_type").unwrap_or("fact".to_string()),
        scope_task_id: row.get("scope_task_id").unwrap_or(None),
        utility_score: row.get("utility_score").unwrap_or(0.5),
        needs_re_extraction: row.get("needs_re_extraction").unwrap_or(0),
    })
}

impl MissionDB {
    pub fn migrate(&self) -> DbResult<()> {
        let conn = self.conn();

        conn.execute_batch("CREATE TABLE IF NOT EXISTS knowledge (\n    id TEXT PRIMARY KEY,\n    category TEXT NOT NULL,\n    key TEXT NOT NULL,\n    summary TEXT NOT NULL,\n    detail TEXT,\n    source TEXT NOT NULL DEFAULT 'conversation',\n    confidence REAL NOT NULL DEFAULT 1.0,\n    access_count INTEGER NOT NULL DEFAULT 0,\n    created_at TEXT NOT NULL,\n    updated_at TEXT NOT NULL,\n    last_accessed_at TEXT,\n    linked_task_id TEXT,\n    embedding TEXT,\n    embedding_provider TEXT,\n    kb_type TEXT NOT NULL DEFAULT 'fact',\n    scope_task_id TEXT,\n    utility_score REAL NOT NULL DEFAULT 0.5,\n    needs_re_extraction INTEGER NOT NULL DEFAULT 0,\n    UNIQUE(category, key)\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(knowledge)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "category") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN category TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "key") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN key TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "summary") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN summary TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "detail") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN detail TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "source") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN source TEXT DEFAULT 'conversation'")?;
        }
        if !existing_cols.iter().any(|c| c == "confidence") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN confidence REAL DEFAULT 1.0")?;
        }
        if !existing_cols.iter().any(|c| c == "access_count") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN access_count INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN created_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "updated_at") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN updated_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "last_accessed_at") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN last_accessed_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "linked_task_id") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN linked_task_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "embedding") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN embedding TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "embedding_provider") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN embedding_provider TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "kb_type") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN kb_type TEXT DEFAULT 'fact'")?;
        }
        if !existing_cols.iter().any(|c| c == "scope_task_id") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN scope_task_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "utility_score") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN utility_score REAL DEFAULT 0.5")?;
        }
        if !existing_cols.iter().any(|c| c == "needs_re_extraction") {
            conn.execute_batch("ALTER TABLE knowledge ADD COLUMN needs_re_extraction INTEGER DEFAULT 0")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_category ON knowledge(category)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_scope ON knowledge(scope_task_id)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_utility ON knowledge(utility_score)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_type ON knowledge(kb_type)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS knowledge_edges (\n    source_id TEXT NOT NULL,\n    target_id TEXT NOT NULL,\n    relation_type TEXT NOT NULL,\n    weight REAL NOT NULL DEFAULT 1.0,\n    created_at TEXT NOT NULL DEFAULT (datetime('now')),\n    PRIMARY KEY ()\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(knowledge_edges)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "source_id") {
            conn.execute_batch("ALTER TABLE knowledge_edges ADD COLUMN source_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "target_id") {
            conn.execute_batch("ALTER TABLE knowledge_edges ADD COLUMN target_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "relation_type") {
            conn.execute_batch("ALTER TABLE knowledge_edges ADD COLUMN relation_type TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "weight") {
            conn.execute_batch("ALTER TABLE knowledge_edges ADD COLUMN weight REAL DEFAULT 1.0")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE knowledge_edges ADD COLUMN created_at TEXT DEFAULT (datetime('now'))")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_edge_source ON knowledge_edges(source_id)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_edge_target ON knowledge_edges(target_id)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS kb_access_log (\n    id INTEGER PRIMARY KEY,\n    kb_id TEXT NOT NULL,\n    co_accessed_ids TEXT NOT NULL,\n    context_source TEXT NOT NULL DEFAULT 'prefetch',\n    created_at TEXT NOT NULL DEFAULT (datetime('now')),\n    session_id TEXT\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(kb_access_log)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE kb_access_log ADD COLUMN id INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "kb_id") {
            conn.execute_batch("ALTER TABLE kb_access_log ADD COLUMN kb_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "co_accessed_ids") {
            conn.execute_batch("ALTER TABLE kb_access_log ADD COLUMN co_accessed_ids TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "context_source") {
            conn.execute_batch("ALTER TABLE kb_access_log ADD COLUMN context_source TEXT DEFAULT 'prefetch'")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE kb_access_log ADD COLUMN created_at TEXT DEFAULT (datetime('now'))")?;
        }
        if !existing_cols.iter().any(|c| c == "session_id") {
            conn.execute_batch("ALTER TABLE kb_access_log ADD COLUMN session_id TEXT")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_access_log_kb ON kb_access_log(kb_id)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_access_log_created ON kb_access_log(created_at)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_access_log_session ON kb_access_log(session_id)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS kb_operation_queue (\n    id TEXT PRIMARY KEY,\n    plan_id TEXT NOT NULL,\n    task_id TEXT,\n    operation TEXT NOT NULL,\n    target_keys TEXT NOT NULL,\n    rationale TEXT,\n    status TEXT NOT NULL DEFAULT 'pending',\n    priority INTEGER NOT NULL DEFAULT 0,\n    result TEXT,\n    created_at TEXT NOT NULL,\n    executed_at TEXT,\n    error TEXT\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(kb_operation_queue)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "plan_id") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN plan_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "task_id") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN task_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "operation") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN operation TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "target_keys") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN target_keys TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "rationale") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN rationale TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "status") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN status TEXT DEFAULT 'pending'")?;
        }
        if !existing_cols.iter().any(|c| c == "priority") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN priority INTEGER DEFAULT 0")?;
        }
        if !existing_cols.iter().any(|c| c == "result") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN result TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN created_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "executed_at") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN executed_at TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "error") {
            conn.execute_batch("ALTER TABLE kb_operation_queue ADD COLUMN error TEXT")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_op_status ON kb_operation_queue(status)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_op_plan ON kb_operation_queue(plan_id)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS kb_ast_links (\n    id INTEGER PRIMARY KEY,\n    kb_id TEXT NOT NULL,\n    ast_node_id TEXT,\n    symbol_name TEXT NOT NULL,\n    file_path TEXT,\n    relation TEXT NOT NULL DEFAULT 'related_to',\n    confidence REAL NOT NULL DEFAULT 0.8,\n    created_at TEXT NOT NULL DEFAULT (datetime('now'))\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(kb_ast_links)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "id") {
            conn.execute_batch("ALTER TABLE kb_ast_links ADD COLUMN id INTEGER")?;
        }
        if !existing_cols.iter().any(|c| c == "kb_id") {
            conn.execute_batch("ALTER TABLE kb_ast_links ADD COLUMN kb_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "ast_node_id") {
            conn.execute_batch("ALTER TABLE kb_ast_links ADD COLUMN ast_node_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "symbol_name") {
            conn.execute_batch("ALTER TABLE kb_ast_links ADD COLUMN symbol_name TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "file_path") {
            conn.execute_batch("ALTER TABLE kb_ast_links ADD COLUMN file_path TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "relation") {
            conn.execute_batch("ALTER TABLE kb_ast_links ADD COLUMN relation TEXT DEFAULT 'related_to'")?;
        }
        if !existing_cols.iter().any(|c| c == "confidence") {
            conn.execute_batch("ALTER TABLE kb_ast_links ADD COLUMN confidence REAL DEFAULT 0.8")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE kb_ast_links ADD COLUMN created_at TEXT DEFAULT (datetime('now'))")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_ast_kb ON kb_ast_links(kb_id)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_ast_symbol ON kb_ast_links(symbol_name)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_ast_file ON kb_ast_links(file_path)")?;
        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_kb_ast_node ON kb_ast_links(ast_node_id)")?;

        conn.execute_batch("CREATE TABLE IF NOT EXISTS prompt_snapshots (\n    task_id TEXT PRIMARY KEY,\n    prompt TEXT NOT NULL,\n    cited_kb_ids TEXT NOT NULL DEFAULT '[]',\n    category TEXT NOT NULL DEFAULT 'other',\n    task_outcome TEXT,\n    created_at TEXT NOT NULL\n)")?;

        let existing_cols: Vec<String> = conn.prepare("PRAGMA table_info(prompt_snapshots)")?
            .query_map([], |row| row.get::<_, String>(1))?
            .filter_map(|r| r.ok())
            .collect();

        if !existing_cols.iter().any(|c| c == "task_id") {
            conn.execute_batch("ALTER TABLE prompt_snapshots ADD COLUMN task_id TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "prompt") {
            conn.execute_batch("ALTER TABLE prompt_snapshots ADD COLUMN prompt TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "cited_kb_ids") {
            conn.execute_batch("ALTER TABLE prompt_snapshots ADD COLUMN cited_kb_ids TEXT DEFAULT '[]'")?;
        }
        if !existing_cols.iter().any(|c| c == "category") {
            conn.execute_batch("ALTER TABLE prompt_snapshots ADD COLUMN category TEXT DEFAULT 'other'")?;
        }
        if !existing_cols.iter().any(|c| c == "task_outcome") {
            conn.execute_batch("ALTER TABLE prompt_snapshots ADD COLUMN task_outcome TEXT")?;
        }
        if !existing_cols.iter().any(|c| c == "created_at") {
            conn.execute_batch("ALTER TABLE prompt_snapshots ADD COLUMN created_at TEXT")?;
        }

        conn.execute_batch("CREATE INDEX IF NOT EXISTS idx_prompt_snap_cat ON prompt_snapshots(category)")?;

        Ok(())
    }

    // ========== knowledge ==========

    pub fn kb_get_by_id(&self, id: &str) -> DbResult<Option<KnowledgeEntry>> {
        let conn = self.read_conn();
        conn.query_row(
            "SELECT * FROM knowledge WHERE id = ?1",
            params![id],
            |row| row_to_knowledge_entry(row),
        )
        .optional()
        .map_err(Into::into)
    }

    pub fn kb_get_id_by_key(&self, key: &str) -> DbResult<Option<String>> {
        let conn = self.read_conn();
        conn.query_row(
            "SELECT * FROM knowledge WHERE key = ?1",
            params![key],
            |row| row_to_knowledge_entry(row),
        )
        .optional()
        .map_err(Into::into)
    }

    pub fn kb_forget(&self, key: &str) -> DbResult<bool> {
        let conn = self.conn();
        let changes = conn.execute(
            "DELETE FROM knowledge WHERE key = ?1",
            params![key],
        )?;
        Ok(changes > 0)
    }

    pub fn kb_set_linked_task_id(&self, key: &str) -> DbResult<bool> {
        let conn = self.conn();
        conn.execute(
            "UPDATE knowledge SET linked_task_id = ?1 WHERE key = ?2",
            params![linked_task_id, key],
        )?;
        Ok(())
    }

    pub fn kb_clear_scope(&self, id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE knowledge SET scope_task_id = NULL, updated_at = datetime('now') WHERE id = ?1",
            params![id],
        )?;
        Ok(())
    }

    pub fn kb_list_by_scope(&self, scope_task_id: &str) -> DbResult<Vec<KnowledgeEntry>> {
        let conn = self.read_conn();
        let mut stmt = conn.prepare("SELECT * FROM knowledge WHERE scope_task_id = ?1")?;
        let rows = stmt.query_map(params![scope_task_id], |row| row_to_knowledge_entry(row))?;
        rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
    }

    // ========== knowledge_edges ==========

    pub fn kb_add_edge(&self, source_id: &str, target_id: &str, relation_type: &str, weight: f64, created_at: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO knowledge_edges (source_id, target_id, relation_type, weight, created_at) VALUES (?1, ?2, ?3, ?4, ?5) ON CONFLICT (source_id, target_id, relation_type) DO UPDATE SET weight = ?4",
            params![source_id, target_id, relation_type, weight, created_at],
        )?;
        Ok(())
    }

    // ========== prompt_snapshots ==========

    pub fn save_prompt_snapshot(&self, task_id: &str, prompt: &str, cited_kb_ids: &str, category: &str, created_at: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "INSERT INTO prompt_snapshots (task_id, prompt, cited_kb_ids, category, task_outcome) VALUES (?1, ?2, ?3, ?4, ?5) ON CONFLICT (task_id) DO UPDATE SET prompt = ?2, cited_kb_ids = ?3, category = ?4, created_at = ?5",
            params![task_id, prompt, cited_kb_ids, category, created_at],
        )?;
        Ok(())
    }

    pub fn update_prompt_snapshot_outcome(&self, task_id: &str) -> DbResult<()> {
        let conn = self.conn();
        conn.execute(
            "UPDATE prompt_snapshots SET task_outcome = ?1 WHERE task_id = ?2",
            params![task_outcome, task_id],
        )?;
        Ok(())
    }

}

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in *_custom.rs
// These signatures are locked by intent-db.lisp declarations.
// Rust compiler enforces your impl matches these exactly.
// ═══════════════════════════════════════════════════════════

pub trait MissionDBCustomLogic {
    /// Logic: SELECT category, COUNT(*) GROUP BY category ORDER BY cnt DESC
    /// Table: knowledge
    fn kb_summary(&self) -> DbResult<Vec<(String, i64)>>;

    /// Logic: SELECT key ORDER BY access_count DESC, updated_at DESC LIMIT
    /// Table: knowledge
    fn kb_hot_keys(&self, limit: i64) -> DbResult<Vec<String>>;

    /// Logic: access_count=0 AND julianday age > N days
    /// Table: knowledge
    fn kb_find_stale(&self, days: i64) -> DbResult<Vec<KnowledgeEntry>>;

    /// Logic: WHERE confidence < threshold ORDER BY confidence ASC
    /// Table: knowledge
    fn kb_list_low_confidence(&self, threshold: f64, limit: usize) -> DbResult<Vec<KnowledgeEntry>>;

    /// Logic: WHERE utility < threshold AND access >= min
    /// Table: knowledge
    fn kb_list_low_utility(&self, threshold: f64, min_access: i64, limit: usize) -> DbResult<Vec<KnowledgeEntry>>;

    /// Logic: kb_type=state AND stale last_accessed_at
    /// Table: knowledge
    fn kb_list_stale_state_entries(&self, stale_days: i64, limit: usize) -> DbResult<Vec<KnowledgeEntry>>;

    /// Logic: 4-phase upsert: exact category+key → key re-cat → fuzzy merge (Jaccard≥0.5) → insert new
    /// Table: knowledge
    fn kb_remember(&self, input: &KBRememberInput) -> DbResult<KBRememberResult>;

    /// Logic: dynamic SET clauses, returns (entry, content_changed)
    /// Table: knowledge
    fn kb_update(&self, key: &str, new_category: Option<&str>, new_summary: Option<&str>, new_detail: Option<&serde_json::Value>, new_confidence: Option<f64>, new_linked_task_id: Option<&str>) -> DbResult<Option<(KnowledgeEntry, bool)>>;

    /// Logic: SELECT + side-effect: bump access_count + utility_score
    /// Table: knowledge
    fn kb_get(&self, key: &str) -> DbResult<Option<KnowledgeEntry>>;

    /// Logic: optional category filter with LIKE for sub-categories
    /// Table: knowledge
    fn kb_list(&self, category: Option<&str>) -> DbResult<Vec<KnowledgeEntry>>;

    /// Logic: kb_list + LIMIT OFFSET
    /// Table: knowledge
    fn kb_list_paginated(&self, category: Option<&str>, limit: u32, offset: u32) -> DbResult<Vec<KnowledgeEntry>>;

    /// Logic: hybrid FTS5 + LIKE fallback search
    /// Table: knowledge
    fn kb_search(&self, query: &str, category: Option<&str>) -> DbResult<Vec<KnowledgeEntry>>;

    /// Logic: kb_search with rank position
    /// Table: knowledge
    fn kb_search_ranked(&self, query: &str, category: Option<&str>, limit: usize) -> DbResult<Vec<(KnowledgeEntry, usize)>>;

    /// Logic: FTS5 MATCH with snippet() and BM25
    /// Table: knowledge
    fn kb_search_fts_ranked(&self, query: &str, category: Option<&str>) -> DbResult<Vec<(String, usize, Option<String>)>>;

    /// Logic: dynamic per-keyword LIKE with multi-column search
    /// Table: knowledge
    fn kb_search_like_ranked(&self, query: &str, category: Option<&str>) -> DbResult<Vec<(String, usize)>>;

    /// Logic: UPDATE embedding blob + provider
    /// Table: knowledge
    fn kb_set_embedding(&self, id: &str, embedding: &[f32], provider: &str) -> DbResult<()>;

    /// Logic: id, summary, detail WHERE embedding IS NULL
    /// Table: knowledge
    fn kb_entries_missing_embedding(&self, category: Option<&str>) -> DbResult<Vec<(String, String, String)>>;

    /// Logic: id, summary, detail WHERE provider != current
    /// Table: knowledge
    fn kb_entries_stale_embedding(&self, current_provider: &str, limit: i64) -> DbResult<Vec<(String, String, String)>>;

    /// Logic: deserialize embedding blobs by category
    /// Table: knowledge
    fn kb_load_embeddings(&self, category: &str) -> DbResult<Vec<(String, Vec<f32>)>>;

    /// Logic: deserialize all embedding blobs
    /// Table: knowledge
    fn kb_load_all_embeddings(&self) -> DbResult<Vec<(String, Vec<f32>)>>;

    /// Logic: loop DELETE + FTS rebuild
    /// Table: knowledge
    fn kb_batch_forget(&self, keys: &[String]) -> DbResult<usize>;

    /// Logic: batch UPDATE access_count + utility_score with anti-spam (1hr cooldown)
    /// Table: knowledge
    fn kb_update_access_stats(&self, entries: &[KnowledgeEntry]) -> DbResult<()>;

    /// Logic: UPDATE confidence = MAX(0.1, MIN(1.0, confidence + delta))
    /// Table: knowledge
    fn kb_adjust_confidence(&self, id: &str, delta: f64) -> DbResult<Option<f64>>;

    /// Logic: transacted batch utility boost/decay
    /// Table: knowledge
    fn kb_batch_apply_utility_feedback(&self, kb_ids: &[String], success: bool) -> DbResult<usize>;

    /// Logic: loop UPDATE needs_re_extraction = 1
    /// Table: knowledge
    fn kb_mark_needs_re_extraction(&self, ids: &[String]) -> DbResult<usize>;

    /// Logic: in-memory Jaccard similarity across categories (threshold 0.6)
    /// Table: knowledge
    fn kb_find_duplicates(&self) -> DbResult<Vec<(KnowledgeEntry, KnowledgeEntry, f64)>>;

    /// Logic: 3-phase: delete infra → Darwinian decay gc → cleanup edges + FTS rebuild
    /// Table: knowledge
    fn kb_auto_gc(&self) -> DbResult<usize>;

    /// Logic: complex aggregation: total, by_category, by_source, by_type, utility distribution
    /// Table: knowledge
    fn kb_stats(&self) -> DbResult<serde_json::Value>;

    /// Logic: coverage stats for KB/Skill/Conversation embeddings across providers
    /// Table: knowledge
    fn embedding_stats(&self) -> DbResult<serde_json::Value>;

    /// Logic: WHERE source_id = ?1 OR target_id = ?1
    /// Table: knowledge_edges
    fn kb_get_edges(&self, id: &str) -> DbResult<Vec<KBEdge>>;

    /// Logic: DELETE WHERE source_id OR target_id
    /// Table: knowledge_edges
    fn kb_delete_edges_for(&self, id: &str) -> DbResult<()>;

    /// Logic: per-id neighbor query, deduplicate, sort by weight, cap at max_extra
    /// Table: knowledge_edges
    fn kb_expand_related(&self, ids: &[String], max_extra: usize) -> DbResult<Vec<String>>;

    /// Logic: for each kb_id: INSERT INTO kb_access_log
    /// Table: kb_access_log
    fn kb_log_co_access(&self, kb_ids: &[String], source: &str, session_id: Option<&str>) -> DbResult<()>;

    /// Logic: SELECT DISTINCT kb_id WHERE session_id
    /// Table: kb_access_log
    fn get_session_cited_kb_ids(&self, session_id: &str) -> DbResult<Vec<String>>;

    /// Logic: clean old logs + fetch recent + build frequency map
    /// Table: kb_access_log
    fn kb_compute_cooccurrence(&self, since_hours: i64, top_n: usize) -> DbResult<HashMap<String, Vec<String>>>;

    /// Logic: loop INSERT OR REPLACE for each operation
    /// Table: kb_operation_queue
    fn kb_ops_save_plan(&self, plan_id: &str, task_id: Option<&str>, operations: &[KBOperation]) -> DbResult<usize>;

    /// Logic: dynamic WHERE with optional filters
    /// Table: kb_operation_queue
    fn kb_ops_list(&self, plan_id: Option<&str>, status: Option<&str>) -> DbResult<Vec<KBOperationRow>>;

    /// Logic: UPDATE SET status, result, error, executed_at
    /// Table: kb_operation_queue
    fn kb_ops_update_status(&self, op_id: &str, status: &str, result: Option<&str>, error: Option<&str>) -> DbResult<bool>;

    /// Logic: UPDATE WHERE status=dispatched AND result LIKE task pattern
    /// Table: kb_operation_queue
    fn kb_ops_complete_by_task_id(&self, task_id: &str, new_status: &str, result: Option<&str>) -> DbResult<bool>;

    /// Logic: UPDATE pending → expired WHERE created_at < TTL
    /// Table: kb_operation_queue
    fn kb_ops_expire_stale(&self, ttl_secs: i64) -> DbResult<usize>;

    /// Logic: SELECT status, COUNT(*) GROUP BY status
    /// Table: kb_operation_queue
    fn kb_ops_plan_summary(&self, plan_id: &str) -> DbResult<serde_json::Value>;

    /// Logic: INSERT ON CONFLICT DO NOTHING
    /// Table: kb_ast_links
    fn kb_add_ast_link(&self, kb_id: &str, symbol_name: &str, file_path: Option<&str>, ast_node_id: Option<&str>, relation: &str, confidence: f64) -> DbResult<()>;

    /// Logic: JOIN knowledge ON kb_id ORDER BY utility DESC LIMIT 10
    /// Table: kb_ast_links
    fn kb_get_memories_for_symbol(&self, symbol_name: &str) -> DbResult<Vec<KnowledgeEntry>>;

    /// Logic: JOIN knowledge ON kb_id ORDER BY symbol_name, utility LIMIT 30
    /// Table: kb_ast_links
    fn kb_get_memories_for_file(&self, file_path: &str) -> DbResult<Vec<(String, KnowledgeEntry)>>;

    /// Logic: DELETE WHERE kb_id
    /// Table: kb_ast_links
    fn kb_delete_ast_links_for(&self, kb_id: &str) -> DbResult<()>;

    /// Logic: lookup ast_nodes by name → UPDATE kb_ast_links.ast_node_id
    /// Table: kb_ast_links
    fn kb_ast_lazy_resolve(&self, link_id: i64, symbol_name: &str) -> DbResult<Option<String>>;

    /// Logic: WHERE category AND task_outcome IS NOT NULL ORDER BY created_at DESC
    /// Table: prompt_snapshots
    fn list_prompt_snapshots(&self, category: &str, limit: usize) -> DbResult<Vec<(String, String, String)>>;

    /// Logic: multi-table JOIN: snapshots WHERE success AND cited KB modified after snapshot
    /// Table: prompt_snapshots
    fn list_modified_snapshots(&self, limit: usize) -> DbResult<Vec<(String, String, String, String)>>;

}

