// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent.lisp (rpc-gateway missiond-mcp)
// Pattern: rpc-gateway (generalized interface layer)

use anyhow::Result;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
#[cfg(windows)]
#[allow(unused_imports)]
use tokio::net::TcpListener;
#[cfg(unix)]
#[allow(unused_imports)]
use tokio::net::UnixListener;

pub mod error_codes {
    pub const UNKNOWN_TOOL: &str = "UNKNOWN_TOOL";
    pub const UNKNOWN_ACTION: &str = "UNKNOWN_ACTION";
    pub const MISSING_PARAM: &str = "MISSING_PARAM";
    pub const INVALID_PARAM: &str = "INVALID_PARAM";
    pub const NOT_FOUND: &str = "NOT_FOUND";
    pub const PERMISSION_DENIED: &str = "PERMISSION_DENIED";
    pub const IPC_TIMEOUT: &str = "IPC_TIMEOUT";
    pub const SPAWN_FAILED: &str = "SPAWN_FAILED";
    pub const DB_ERROR: &str = "DB_ERROR";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RequestId {
    Number(i64),
    String(String),
    Null,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    pub jsonrpc: String,
    pub method: String,
    pub params: Option<Value>,
    pub id: Option<RequestId>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Response {
    pub jsonrpc: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ErrorObject>,
    pub id: RequestId,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorObject {
    pub code: i32,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<Value>,
}

#[derive(Debug, Clone)]
pub enum RpcError {
    ParseError(Option<String>),
    InvalidRequest(Option<String>),
    MethodNotFound(String),
    InvalidParams(String),
    InternalError(String),
}

impl std::fmt::Display for RpcError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message())
    }
}

impl std::error::Error for RpcError {}

impl RpcError {
    pub fn code(&self) -> i32 {
        match self {
            RpcError::ParseError(_) => -32700,
            RpcError::InvalidRequest(_) => -32600,
            RpcError::MethodNotFound(_) => -32601,
            RpcError::InvalidParams(_) => -32602,
            RpcError::InternalError(_) => -32603,
        }
    }

    pub fn message(&self) -> String {
        match self {
            RpcError::ParseError(m) => {
                format!("Parse error: {}", m.as_deref().unwrap_or("invalid JSON"))
            }
            RpcError::InvalidRequest(m) => {
                format!("Invalid request: {}", m.as_deref().unwrap_or(""))
            }
            RpcError::MethodNotFound(m) => format!("Method not found: {m}"),
            RpcError::InvalidParams(m) => format!("Invalid params: {m}"),
            RpcError::InternalError(m) => format!("Internal error: {m}"),
        }
    }
}

impl Response {
    pub fn success(id: RequestId, result: Value) -> Self {
        Self {
            jsonrpc: "2.0".into(),
            result: Some(result),
            error: None,
            id,
        }
    }

    pub fn from_error(id: RequestId, err: RpcError) -> Self {
        Self {
            jsonrpc: "2.0".into(),
            result: None,
            error: Some(ErrorObject {
                code: err.code(),
                message: err.message(),
                data: None,
            }),
            id,
        }
    }
}

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED DISPATCH — routes tool names to handler modules
// ═══════════════════════════════════════════════════════════

pub async fn dispatch_tool<H: MissiondMcp>(handler: &H, name: &str, args: Value) -> Result<Value> {
    match name {
        "mission_task_submit"
        | "mission_task_query"
        | "mission_task_cancel"
        | "mission_task_delegate"
        | "mission_swarm_run" => handler.handle_task(name, args).await,
        "mission_pty_spawn"
        | "mission_pty_send"
        | "mission_pty_read"
        | "mission_pty_status"
        | "mission_pty_screenshot"
        | "mission_pty_confirm"
        | "mission_pty_signal" => handler.handle_pty(name, args).await,
        "mission_slots"
        | "mission_slot_history"
        | "mission_compute_slot"
        | "mission_agents"
        | "mission_master_status"
        | "mission_convergence_status"
        | "mission_nightly_evolution" => handler.handle_slot(name, args).await,
        "mission_cc_query" | "mission_cc_swarm" => handler.handle_cc_tasks(name, args).await,
        "mission_worker" => handler.handle_worker(name, args).await,
        "mission_job_poll" => handler.handle_job(name, args).await,
        "mission_flow_run" => handler.handle_worker(name, args).await,
        "mission_board_create"
        | "mission_board_query"
        | "mission_board_update"
        | "mission_board_delete"
        | "mission_board_claim"
        | "mission_board_decompose"
        | "mission_board_note_add"
        | "mission_board_retry" => handler.handle_board(name, args).await,
        "mission_skill_query"
        | "mission_skill_exec"
        | "mission_skill_mutate"
        | "mission_skill_context" => handler.handle_skill(name, args).await,
        "mission_memory" => handler.handle_memory(name, args).await,
        "mission_insight" => handler.handle_insight(name, args).await,
        "mission_embedding_ops" => handler.handle_embedding(name, args).await,
        "mission_question" | "mission_interaction" => handler.handle_question(name, args).await,
        "mission_router_chat" | "mission_router_chat_manage" => {
            handler.handle_router_chat(name, args).await
        }
        "mission_timeline" => handler.handle_timeline(name, args).await,
        "mission_audit" | "mission_tool_directory" => handler.handle_audit(name, args).await,
        "mission_retrospective_manage" => handler.handle_retrospective(name, args).await,
        "mission_decision_stats" => handler.handle_decision(name, args).await,
        "mission_infra_query" | "mission_infra_ops" => handler.handle_infra(name, args).await,
        "mission_permission_query" | "mission_permission_mutate" => {
            handler.handle_permission(name, args).await
        }
        "mission_sys_config"
        | "mission_sys_logs"
        | "mission_power_control"
        | "mission_control"
        | "mission_pause" => handler.handle_system(name, args).await,
        n if n.starts_with("mission_kb_") => handler.handle_kb(n, args).await,
        n if n.starts_with("mission_board_") => handler.handle_board(n, args).await,
        n if n.starts_with("mission_conversation_") => handler.handle_conversation(n, args).await,
        n if n.starts_with("xjp_") => handler.handle_external(n, args).await,
        _ => anyhow::bail!("Unknown tool: {}", name),
    }
}

pub async fn run_stdio<H: MissiondMcp>(handler: &H) -> Result<()> {
    let stdin = tokio::io::stdin();
    let mut stdout = tokio::io::stdout();
    let mut reader = BufReader::new(stdin);
    let mut line = String::new();

    loop {
        line.clear();
        let bytes = reader.read_line(&mut line).await?;
        if bytes == 0 {
            break;
        }

        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }

        let request: Request = match serde_json::from_str(trimmed) {
            Ok(r) => r,
            Err(e) => {
                let resp = Response::from_error(
                    RequestId::Null,
                    RpcError::ParseError(Some(e.to_string())),
                );
                let json = serde_json::to_string(&resp)?;
                stdout.write_all(json.as_bytes()).await?;
                stdout.write_all(b"\n").await?;
                stdout.flush().await?;
                continue;
            }
        };

        let is_notification = request.id.is_none();
        let id = request.id.clone().unwrap_or(RequestId::Null);
        let response = match request.method.as_str() {
            "initialize" => {
                handler
                    .handle_initialize(id.clone(), request.params.unwrap_or(Value::Null))
                    .await
            }
            "notifications/initialized" => {
                handler
                    .handle_notifications_initialized(
                        id.clone(),
                        request.params.unwrap_or(Value::Null),
                    )
                    .await
            }
            "tools/list" => {
                handler
                    .handle_tools_list(id.clone(), request.params.unwrap_or(Value::Null))
                    .await
            }
            "tools/call" => {
                handler
                    .handle_tools_call(id.clone(), request.params.unwrap_or(Value::Null))
                    .await
            }
            "ping" => {
                handler
                    .handle_ping(id.clone(), request.params.unwrap_or(Value::Null))
                    .await
            }
            other => Response::from_error(id, RpcError::MethodNotFound(other.to_string())),
        };

        if is_notification {
            continue;
        }

        let json = serde_json::to_string(&response)?;
        stdout.write_all(json.as_bytes()).await?;
        stdout.write_all(b"\n").await?;
        stdout.flush().await?;
    }
    Ok(())
}

// IPC transport: newline-delimited JSON over Unix socket / TCP loopback
pub async fn handle_ipc_message(message: &str) -> Result<String> {
    let request: Request =
        serde_json::from_str(message).map_err(|e| anyhow::anyhow!("parse error: {e}"))?;
    let id = request.id.clone().unwrap_or(RequestId::Null);
    // Route to handler — implement in custom.rs
    let response = Response::from_error(id, RpcError::InternalError("not implemented".into()));
    Ok(serde_json::to_string(&response)?)
}

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in custom.rs
// ═══════════════════════════════════════════════════════════

#[async_trait::async_trait]
pub trait MissiondMcp: Send + Sync {
    /// MCP protocol initialization handshake
    async fn handle_initialize(&self, id: RequestId, params: Value) -> Response;

    /// Client confirms initialization complete
    async fn handle_notifications_initialized(&self, id: RequestId, params: Value) -> Response;

    /// List all available tool definitions with JSON Schema
    async fn handle_tools_list(&self, id: RequestId, params: Value) -> Response;

    /// Execute a tool by name with arguments
    async fn handle_tools_call(&self, id: RequestId, params: Value) -> Response;

    /// Health check ping/pong
    async fn handle_ping(&self, id: RequestId, params: Value) -> Response;

    /// Handle tools in the 'task' domain
    async fn handle_task(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'pty' domain
    async fn handle_pty(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'slot' domain
    async fn handle_slot(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'cc_tasks' domain
    async fn handle_cc_tasks(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'worker' domain
    async fn handle_worker(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'job' domain
    async fn handle_job(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'kb' domain
    async fn handle_kb(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'board' domain
    async fn handle_board(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'skill' domain
    async fn handle_skill(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'memory' domain
    async fn handle_memory(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'insight' domain
    async fn handle_insight(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'embedding' domain
    async fn handle_embedding(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'conversation' domain
    async fn handle_conversation(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'question' domain
    async fn handle_question(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'router_chat' domain
    async fn handle_router_chat(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'timeline' domain
    async fn handle_timeline(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'audit' domain
    async fn handle_audit(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'retrospective' domain
    async fn handle_retrospective(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'decision' domain
    async fn handle_decision(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'infra' domain
    async fn handle_infra(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'permission' domain
    async fn handle_permission(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'system' domain
    async fn handle_system(&self, tool_name: &str, args: Value) -> Result<Value>;

    /// Handle tools in the 'external' domain
    async fn handle_external(&self, tool_name: &str, args: Value) -> Result<Value>;
}
