// GENERATED BY scripts/project-v3-contracts.mjs --write
// Source: .missiond/v3/missiond-blueprint.lisp
// Output: crates/missiond-core/src/v3_contracts.rs
// Do not edit by hand.

pub const SCHEMA_VERSION: &str = "missiond.contract-abi.v1";
pub const SOURCE_HASH: &str = "40bafc0dbecc505399b5a0a643e626b8";
pub const RUNTIME_CONFIG_SOURCE_HASH: &str = "c9a87c19a2f41f22ada143949aada7b7";
pub const PROJECT_UNIVERSE_SOURCE_HASH: &str = "c9a87c19a2f41f22ada143949aada7b7";
#[rustfmt::skip]
pub const RUNTIME_DOMAIN_SOURCE_HASHES: &[(&str, &str)] = &[
    (
        "workstation",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "flow",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "compute",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "minimax",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "router",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "cascade",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "project-registry",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "capability-governance",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "memory-kb",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "evidence-lane-policy",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "conversation-ingestion",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "autopilot",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "control-plane-kernel",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
    (
        "learning-engine",
        "c9a87c19a2f41f22ada143949aada7b7",
    ),
];
