// GENERATED BY scripts/project-v3-contracts.mjs --write
// Source: .missiond/v3/missiond-blueprint.lisp
// Output: crates/missiond-core/src/v3_contracts.rs
// Do not edit by hand.

pub const SCHEMA_VERSION: &str = "missiond.contract-abi.v1";
pub const SOURCE_HASH: &str = "6fdc8876332e343c68facb52403be289";
pub const RUNTIME_CONFIG_SOURCE_HASH: &str = "635dbe897cf4358762cf4f4f718142e4";
pub const PROJECT_UNIVERSE_SOURCE_HASH: &str = "635dbe897cf4358762cf4f4f718142e4";
#[rustfmt::skip]
pub const RUNTIME_DOMAIN_SOURCE_HASHES: &[(&str, &str)] = &[
    (
        "workstation",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "flow",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "compute",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "minimax",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "router",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "cascade",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "project-registry",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "capability-governance",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "memory-kb",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "evidence-lane-policy",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "conversation-ingestion",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "autopilot",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "control-plane-kernel",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
    (
        "learning-engine",
        "635dbe897cf4358762cf4f4f718142e4",
    ),
];
