// GENERATED BY scripts/project-v3-contracts.mjs --write
// Source: .missiond/v3/missiond-blueprint.lisp
// Output: crates/missiond-core/src/v3_contracts.rs
// Do not edit by hand.

pub const SCHEMA_VERSION: &str = "missiond.contract-abi.v1";
pub const SOURCE_HASH: &str = "2d449ca9103356fa62903be6b95bfaa8";
pub const RUNTIME_CONFIG_SOURCE_HASH: &str = "25fc096c84f11d39fc4932b18daeee5d";
pub const PROJECT_UNIVERSE_SOURCE_HASH: &str = "25fc096c84f11d39fc4932b18daeee5d";
#[rustfmt::skip]
pub const RUNTIME_DOMAIN_SOURCE_HASHES: &[(&str, &str)] = &[
    (
        "workstation",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "flow",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "compute",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "minimax",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "router",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "cascade",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "project-registry",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "capability-governance",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "memory-kb",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "evidence-lane-policy",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "conversation-ingestion",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "autopilot",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "control-plane-kernel",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
    (
        "learning-engine",
        "25fc096c84f11d39fc4932b18daeee5d",
    ),
];
