(work-order-plan
  :schema "missiond.work-order.plan.v1"
  :id "20260516-macmini-managed-node"
  :intent "20260516-macmini-managed-node"
  :status draft
  :accepted_shards
    ((shard default
       :accepted_shard_id "20260516-macmini-managed-node-shard-default"
       :read_scope ["."]
       :write_scope [".missiond/v3/missiond-blueprint.lisp"
                     ".missiond/work-orders/20260516-macmini-managed-node/audit.lisp"
                     ".missiond/work-orders/20260516-macmini-managed-node/plan.lisp"
                     "crates/missiond-core/src/cc_tasks/watcher.rs"
                     "crates/missiond-core/src/db/pg/conversation.rs"
                     "crates/missiond-core/src/db/pg/observability.rs"
                     "crates/missiond-core/src/db/pg/skill.rs"
                     "crates/missiond-core/src/db/pg/slot.rs"
                     "crates/missiond-daemon/src/handlers/compute/compute_slot.rs"
                     "crates/missiond-daemon/src/context/v3_blueprint_runtime.rs"
                     "crates/missiond-daemon/src/engine/learning_engine/idle_explorer.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/context_gather.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/project/universe.rs"
                     "crates/missiond-daemon/src/helpers.rs"
                     "crates/missiond-daemon/src/main.rs"
                     "crates/missiond-daemon/src/workers/local/experience_harvester.rs"
                     "crates/missiond-daemon/src/workers/sonnet/arch_maintenance_worker.rs"
                     "crates/missiond-pty/src/manager.rs"
                     "crates/missiond-pty/src/pty_recognition.rs"
                     "crates/missiond-pty/src/session.rs"
                     "scripts/check-typed-lisp-compiler.mjs"
                     "scripts/check-v3-skill-runtime-isomorphism.mjs"
                     "scripts/check-v3-workstation-config-isomorphism.mjs"
                     "tools/missiond_lispc/bin/dune"
                     "tools/missiond_lispc/bin/main.ml"
                     "tools/missiond_lispc/bin/workstation_schema.ml"]
       :acceptance ["scripts/cargo-fmt-touched.sh --check"
                    "node scripts/check-v3-skill-runtime-isomorphism.mjs --json"
                    "node scripts/check-v3-workstation-config-isomorphism.mjs --json"
                    "node scripts/check-v3-final-convergence.mjs --json --static-only"
                    "cargo check -p missiond-core -p missiond-daemon -p missiond-mcp"
                    "cargo build -p missiond-daemon -p missiond-mcp --release"
                    "git diff --check"])))
