(work-order-plan
  :schema "missiond.work-order.plan.v1"
  :id "wo-20260604122616-GCP-domain-runtime-governance-cl"
  :intent "wo-20260604122616-GCP-domain-runtime-governance-cl"
  :status draft
  :accepted_shards
    ((shard default
       :accepted_shard_id "wo-20260604122616-GCP-domain-runtime-governance-cl-shard-default"
       :read_scope ["."]
       :write_scope [".missiond/v3/shards/implementation/request-surfaces.lisp"
                     ".missiond/v3/shards/pillar-flow-map.lisp"
                     ".missiond/v3/shards/universe/infrastructure.lisp"
                     ".missiond/v3/shards/universe/project-maturity.lisp"
                     ".missiond/v3/shards/universe/project-registry.lisp"
                     ".missiond/v3/shards/universe/service-layer-template.lisp"
                     ".missiond/v3/shards/universe/service-runtime.lisp"
                     "crates/missiond-core/src/v3_contracts.rs"
                     "crates/missiond-core/src/ws/server.rs"
                     "crates/missiond-daemon/src/context/v3_contracts/generated.rs"
                     "crates/missiond-daemon/src/context/v3_runtime_defaults/generated.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/context_gather.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/project/deployment_channels.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/project/universe.rs"
                     "crates/missiond-daemon/src/handlers/sysinfra/infra.rs"
                     "scripts/check-domain-proxy-isomorphism.mjs"
                     "scripts/check-jarvis-runtime-topology.mjs"
                     "scripts/check-project-ssot-universe.mjs"
                     "scripts/check-v3-infrastructure-universe-isomorphism.mjs"
                     "scripts/check-v3-interaction-gateway-isomorphism.mjs"
                     "scripts/check-v3-runtime-path-hygiene.mjs"
                     "scripts/compile-v3-runtime.mjs"
                     "scripts/deploy-daemon.sh"
                     "scripts/generated/v3_contracts.d.ts"
                     "scripts/generated/v3_contracts.mjs"
                     "scripts/generated/v3_runtime_defaults.mjs"
                     "scripts/lib/behavior_universe.mjs"
                     "scripts/scaffold-product-deployment-closure.mjs"
                     "scripts/smoke-jarvis-chain.mjs"
                     "scripts/smoke-jarvis-intent-plan-dispatch.mjs"
                     "scripts/smoke-jarvis-interaction.mjs"]
       :acceptance ["node scripts/compile-v3-runtime.mjs --write --json"
                    "node scripts/project-v3-contracts.mjs --write"
                    "node scripts/check-project-ssot-universe.mjs --json"
                    "node scripts/check-deployment-channel-coverage.mjs"
                    "node scripts/check-domain-proxy-isomorphism.mjs --json"
                    "cargo check -p missiond-daemon -p missiond-core"
                    "git diff --check"])))
