(work-order-plan
  :schema "missiond.work-order.plan.v1"
  :id "20260523-missiond-runtime-convergence-batch"
  :intent "20260523-missiond-runtime-convergence-batch"
  :status accepted
  :accepted_shards
    ((shard runtime-convergence
       :accepted_shard_id "20260523-missiond-runtime-convergence-batch-shard-runtime"
       :read_scope ["."]
       :write_scope [".missiond/templates/**"
                     ".missiond/v3/missiond-blueprint.lisp"
                     ".missiond/v3/shards/implementation/request-surfaces.lisp"
                     ".missiond/v3/shards/index.lisp"
                     ".missiond/v3/shards/universe/behavior-closure.lisp"
                     ".missiond/v3/shards/universe/project-maturity.lisp"
                     ".missiond/v3/shards/universe/project-registry.lisp"
                     ".missiond/v3/shards/workstation-runtime.lisp"
                     ".missiond/work-orders/20260523-missiond-runtime-convergence-batch/**"
                     "crates/missiond-core/migrations/20260523002000_conversation_message_bool_flags.sql"
                     "crates/missiond-core/src/db/pg/conversation.rs"
                     "crates/missiond-core/src/db/pg/directive.rs"
                     "crates/missiond-core/src/db/pg/message.rs"
                     "crates/missiond-core/src/db/traits.rs"
                     "crates/missiond-core/src/ws/server.rs"
                     "crates/missiond-daemon/src/context/**"
                     "crates/missiond-daemon/src/context/v3_blueprint_runtime.rs"
                     "crates/missiond-daemon/src/context/v3_blueprint_runtime/**"
                     "crates/missiond-daemon/src/context/v3_contracts/generated.rs"
                     "crates/missiond-daemon/src/context/v3_runtime_defaults/generated.rs"
                     "crates/missiond-daemon/src/engine/intent_engine/autopilot.rs"
                     "crates/missiond-daemon/src/handlers/compute/pty.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/plan.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/plan/**"
                     "crates/missiond-daemon/src/handlers/knowledge/plan_dag.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/plan_dag/**"
                     "crates/missiond-daemon/src/handlers/knowledge/project/vault.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/request.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/request/**"
                     "crates/missiond-daemon/src/handlers/knowledge/request/respond/materialization.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/unified_entry/tests.rs"
                     "crates/missiond-daemon/src/handlers/sysinfra/global_instruction.rs"
                     "crates/missiond-daemon/src/llm/gemini_cli.rs"
                     "crates/missiond-daemon/src/workers/local/codex_ingestion_worker.rs"
                     "crates/missiond-daemon/src/workers/local/xjpcode_briefing_worker.rs"
                     "crates/missiond-mcp/src/tools/knowledge/plan.rs"
                     "crates/missiond-pty/src/session.rs"
                     "scripts/check-behavior-universe-fixtures.mjs"
                     "scripts/check-project-behavior-closure.mjs"
                     "scripts/check-project-maturity.mjs"
                     "scripts/check-project-ssot-universe.mjs"
                     "scripts/check-typed-lisp-compiler.mjs"
                     "scripts/check-v3-agent-cli-regression.mjs"
                     "scripts/check-v3-behavior-closure.mjs"
                     "scripts/check-v3-code-isomorphism-complete.mjs"
                     "scripts/check-v3-context-pack-isomorphism.mjs"
                     "scripts/check-v3-final-convergence.mjs"
                     "scripts/check-v3-plan-execution-isomorphism.mjs"
                     "scripts/check-v3-production-runtime-boundary.mjs"
                     "scripts/check-v3-request-flow-smoke.mjs"
                     "scripts/check-v3-request-lisp-isomorphism.mjs"
                     "scripts/check-v3-router-policy-isomorphism.mjs"
                     "scripts/check-v3-runtime-artifact-catalog.mjs"
                     "scripts/check-v3-semantic-checker-coverage.mjs"
                     "scripts/check-v3-typed-sidecar-compression.mjs"
                     "scripts/check-v3-workstation-config-isomorphism.mjs"
                     "scripts/compile-v3-runtime.mjs"
                     "scripts/generated/v3_contracts.d.ts"
                     "scripts/generated/v3_contracts.mjs"
                     "scripts/generated/v3_runtime_defaults.mjs"
                     "scripts/lib/behavior_universe.mjs"
                     "scripts/lib/behavior_universe_fixtures.mjs"
                     "scripts/lib/v3_compiled_contract.mjs"
                     "scripts/lib/v3_semantic_facts.mjs"
                     "scripts/lib/v3_semantic_rules.mjs"
                     "scripts/lib/v3_workstation_runtime.mjs"
                     "scripts/project-v3-contracts.mjs"
                     "scripts/propose-behavior-navigation.mjs"
                     "tools/missiond_lispc/bin/emit_json.ml"
                     "tools/missiond_lispc/bin/genome_schema.ml"
                     "tools/missiond_lispc/bin/main.ml"
                     "tools/missiond_lispc/bin/source_resolver.ml"
                     "tools/missiond_lispc/test/parser_golden.ml"]
       :acceptance ["cargo check -p missiond-core -p missiond-daemon"
                    "cargo test -p missiond-daemon engine_hint_alone_does_not_widen_code_class_to_fast_patch -- --nocapture"
                    "cargo test -p missiond-daemon workstation_class_uses_json_metadata_when_context_intent_is_legacy_jarvis -- --nocapture"
                    "cargo test -p missiond-daemon output_contract_close_blocker_reads_json_dispatch_contract -- --nocapture"
                    "bash scripts/rustfmt-missiond.sh --check"
                    "node scripts/check-v3-grounded-dispatch-isomorphism.mjs --json"
                    "node scripts/check-v3-workflow-isomorphism.mjs --engine=ocaml --json"
                    "node scripts/check-v3-workstation-pool-isomorphism.mjs --json"
                    "node scripts/check-v3-agent-cli-regression.mjs --json"
                    "node scripts/check-v3-final-convergence.mjs --json --static-only"
                    "git diff --check"])))
