;; Pilot task for MissionD task-contract v1.
;; This file is the SSOT; the Markdown brief is generated by:
;;   node scripts/render-claudecode-task.mjs --force .missiond/tasks/wave19/wave19-00-machine-contract-pilot.lisp

(task wave19-00-machine-contract-pilot
  :schema "missiond.task-contract.v1"
  :title "Machine Contract Pilot — render Lisp task to ClaudeCode brief"
  :kind docs
  :status ready
  :owner "claudecode"
  :depends-on []
  :dispatch-strategy "fresh-code-alignment"
  :goal "Prove that a Lisp task-contract can serve as the machine-readable source of truth while Markdown remains a rendered ClaudeCode execution view."

  :write-scope
    ["docs/machine-contract-pilot.md"]

  :must-not-touch
    [".missiond/v2/*.lisp"
     "crates/**"
     "scripts/**"]

  :requirements
    ["Create a short Markdown note explaining that this pilot was generated from a Lisp task contract."
     "Do not modify any source code."
     "Do not modify architecture Lisp files."
     "Keep the note under 80 lines."]

  :acceptance
    ["git diff --check -- docs/machine-contract-pilot.md"
     "node scripts/check-task-contract.mjs .missiond/tasks/wave19/wave19-00-machine-contract-pilot.lisp"]

  :commit
    (:required true
     :message "docs(task): add machine contract pilot note"
     :scope-check write-scope-only)

  :report
    ["Commit hash."
     "Rendered task brief path."
     "Files changed."
     "Acceptance command results."])
