// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent.lisp (domain-engine learning-engine)
// Pattern: domain-engine (zero internal logic)
//
// Implement EngineLogic trait in custom.rs — all business logic lives there.

use anyhow::Result;
use async_trait::async_trait;


pub struct LearningEngine {
    pub(crate) db: DbExecutor,
    pub(crate) llm: LlmGateway,
    pub(crate) event_bus: EventBus,
    pub(crate) extraction_phase: ExtractionPhase,
}

impl LearningEngine {
    pub fn new(db: DbExecutor, llm: LlmGateway, event_bus: EventBus) -> Self {
        Self {
            db,
            llm,
            event_bus,
            extraction_phase: ExtractionPhase::Idle,
        }
    }
}

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in custom.rs
// ═══════════════════════════════════════════════════════════

#[async_trait]
pub trait LearningEngineLogic {
    /// Route a question through KB → LLM → human cascade
    async fn decide(&self, question: &AgentQuestion) -> Result<Decision>;

    /// Extract knowledge entries from a conversation session
    async fn extract_memory(&self, session_id: &str) -> Result<Vec<KnowledgeEntry>>;

    /// Run one learning engine tick
    async fn tick(&self) -> Result<()>;

}

