// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent.lisp (domain-engine slot-orchestrator)
// Pattern: domain-engine (zero internal logic)
//
// Implement EngineLogic trait in custom.rs — all business logic lives there.

use anyhow::Result;
use async_trait::async_trait;


pub struct SlotOrchestrator {
    pub(crate) control: Arc<ControlManager>,
    pub(crate) registry: RwLock<HashMap<String, SlotTaskConfig>>,
    pub(crate) managers: HashMap<CliEngine, Arc<dyn EngineSlotManager>>,
}

impl SlotOrchestrator {
    pub fn new(control: Arc<ControlManager>) -> Self {
        Self {
            control,
            registry: RwLock::new(HashMap::new()),
            managers: HashMap::new(),
        }
    }
}

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in custom.rs
// ═══════════════════════════════════════════════════════════

#[async_trait]
pub trait SlotOrchestratorLogic {
    /// Register a slot configuration for task dispatch
    async fn register(&self, config: SlotTaskConfig) -> Result<()>;

    /// Execute a task on the best available engine slot
    async fn execute(&self, task: &SlotTaskRequest) -> Result<String>;

    /// Get status of all managed engine slots
    async fn status(&self) -> Vec<EngineStatus>;

    /// Check if a task type is registered
    fn is_registered(&self, task_type: &str) -> bool;
}

