-- MissionD PostgreSQL Schema (M2: 1:1 translation from SQLite)
-- Extensions
CREATE EXTENSION IF NOT EXISTS vector;      -- pgvector for embeddings
CREATE EXTENSION IF NOT EXISTS pg_trgm;     -- trigram for Chinese/code search

-- ============================================================================
-- 1. Tasks & Inbox (Slot task delegation)
-- ============================================================================

CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    role TEXT NOT NULL,
    prompt TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    manual INTEGER NOT NULL DEFAULT 0,
    slot_id TEXT,
    session_id TEXT,
    result TEXT,
    error TEXT,
    created_at BIGINT NOT NULL,
    started_at BIGINT,
    finished_at BIGINT,
    notified_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_role ON tasks(role);
CREATE INDEX IF NOT EXISTS idx_tasks_created ON tasks(created_at);
CREATE INDEX IF NOT EXISTS idx_tasks_manual ON tasks(manual);

CREATE TABLE IF NOT EXISTS inbox (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    from_role TEXT NOT NULL,
    content TEXT NOT NULL,
    read INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_inbox_read ON inbox(read);
CREATE INDEX IF NOT EXISTS idx_inbox_created ON inbox(created_at);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id TEXT NOT NULL,
    type TEXT NOT NULL,
    data TEXT,
    timestamp BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_task ON events(task_id);
CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(timestamp);

-- ============================================================================
-- 2. Slot Sessions & Dynamic Slots
-- ============================================================================

CREATE TABLE IF NOT EXISTS slot_sessions (
    slot_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS dynamic_slots (
    id TEXT PRIMARY KEY,
    parent_slot_id TEXT NOT NULL,
    template TEXT NOT NULL,
    objective TEXT,
    config TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    termination_reason TEXT,
    created_at TEXT NOT NULL,
    terminated_at TEXT,
    ttl_seconds INTEGER NOT NULL DEFAULT 14400,
    expires_at TEXT NOT NULL,
    extend_count INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_dynamic_slots_active ON dynamic_slots(status, expires_at);

CREATE TABLE IF NOT EXISTS daemon_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- ============================================================================
-- 3. Board Tasks & Agent Questions
-- ============================================================================

CREATE TABLE IF NOT EXISTS board_tasks (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'open',
    priority TEXT NOT NULL DEFAULT 'medium',
    category TEXT NOT NULL DEFAULT 'other',
    project TEXT,
    server TEXT,
    due_date TEXT,
    parent_id TEXT,
    order_idx INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    assignee TEXT,
    auto_execute INTEGER NOT NULL DEFAULT 0,
    prompt_template TEXT,
    hidden INTEGER NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retries INTEGER NOT NULL DEFAULT 2,
    claim_executor_id TEXT,
    claim_executor_type TEXT,
    claimed_at TEXT,
    flow_phase TEXT,
    flow_context TEXT,
    flow_template TEXT,
    depends_on TEXT NOT NULL DEFAULT '[]',
    lease_expires_at TEXT,
    dedupe_key TEXT,
    timeout_secs INTEGER,
    context_intent TEXT
);
CREATE INDEX IF NOT EXISTS idx_board_tasks_status ON board_tasks(status);
CREATE INDEX IF NOT EXISTS idx_board_tasks_parent ON board_tasks(parent_id);
CREATE INDEX IF NOT EXISTS idx_board_tasks_claim ON board_tasks(claim_executor_id);
CREATE INDEX IF NOT EXISTS idx_board_tasks_dedupe ON board_tasks(dedupe_key, status);

CREATE TABLE IF NOT EXISTS board_task_notes (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL REFERENCES board_tasks(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    note_type TEXT NOT NULL DEFAULT 'note',
    author TEXT,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_board_task_notes_task ON board_task_notes(task_id);

CREATE TABLE IF NOT EXISTS agent_questions (
    id TEXT PRIMARY KEY,
    task_id TEXT,
    slot_id TEXT,
    session_id TEXT,
    question TEXT NOT NULL,
    context TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'pending',
    answer TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    target TEXT NOT NULL DEFAULT 'user',
    options TEXT,
    decision_type TEXT NOT NULL DEFAULT 'implementation',
    retry_count INTEGER NOT NULL DEFAULT 0,
    routing_trace TEXT
);
CREATE INDEX IF NOT EXISTS idx_agent_questions_status ON agent_questions(status);
CREATE INDEX IF NOT EXISTS idx_agent_questions_target ON agent_questions(target, status);

-- ============================================================================
-- 4. Knowledge Base
-- ============================================================================

CREATE TABLE IF NOT EXISTS knowledge (
    id TEXT PRIMARY KEY,
    category TEXT NOT NULL,
    key TEXT NOT NULL,
    summary TEXT NOT NULL,
    detail TEXT,
    source TEXT DEFAULT 'conversation',
    confidence DOUBLE PRECISION DEFAULT 1.0,
    access_count INTEGER DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_accessed_at TEXT,
    linked_task_id TEXT,
    embedding BYTEA,
    embedding_vec vector(768),
    embedding_provider TEXT,
    kb_type TEXT DEFAULT 'fact',
    scope_task_id TEXT,
    utility_score DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    needs_re_extraction INTEGER NOT NULL DEFAULT 0,
    -- FTS: tsvector column replaces FTS5 virtual table
    fts_doc tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce(key, '') || ' ' || coalesce(summary, '') || ' ' || coalesce(detail, '') || ' ' || coalesce(category, ''))
    ) STORED,
    UNIQUE(category, key)
);
CREATE INDEX IF NOT EXISTS idx_knowledge_category ON knowledge(category);
CREATE INDEX IF NOT EXISTS idx_kb_scope ON knowledge(scope_task_id);
CREATE INDEX IF NOT EXISTS idx_kb_utility ON knowledge(utility_score);
CREATE INDEX IF NOT EXISTS idx_kb_fts ON knowledge USING GIN(fts_doc);
CREATE INDEX IF NOT EXISTS idx_kb_trgm ON knowledge USING GIN((key || ' ' || summary) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_kb_embedding ON knowledge USING hnsw(embedding_vec vector_cosine_ops) WITH (m = 16, ef_construction = 64);

CREATE TABLE IF NOT EXISTS credentials (
    id TEXT PRIMARY KEY,
    knowledge_id TEXT REFERENCES knowledge(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    value_encrypted TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS knowledge_edges (
    source_id TEXT NOT NULL,
    target_id TEXT NOT NULL,
    relation_type TEXT NOT NULL,
    weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    created_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (source_id, target_id, relation_type)
);
CREATE INDEX IF NOT EXISTS idx_kb_edge_source ON knowledge_edges(source_id);
CREATE INDEX IF NOT EXISTS idx_kb_edge_target ON knowledge_edges(target_id);

CREATE TABLE IF NOT EXISTS kb_access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kb_id TEXT NOT NULL,
    co_accessed_ids TEXT NOT NULL,
    context_source TEXT NOT NULL DEFAULT 'prefetch',
    created_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    session_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_kb_access_log_kb ON kb_access_log(kb_id);
CREATE INDEX IF NOT EXISTS idx_kb_access_log_created ON kb_access_log(created_at);
CREATE INDEX IF NOT EXISTS idx_kb_access_log_session ON kb_access_log(session_id);

CREATE TABLE IF NOT EXISTS kb_operation_queue (
    id TEXT PRIMARY KEY,
    plan_id TEXT NOT NULL,
    task_id TEXT,
    operation TEXT NOT NULL,
    target_keys TEXT NOT NULL,
    rationale TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    priority INTEGER NOT NULL DEFAULT 0,
    result TEXT,
    created_at TEXT NOT NULL,
    executed_at TEXT,
    error TEXT
);
CREATE INDEX IF NOT EXISTS idx_kb_op_status ON kb_operation_queue(status);
CREATE INDEX IF NOT EXISTS idx_kb_op_plan ON kb_operation_queue(plan_id);

CREATE TABLE IF NOT EXISTS kb_ast_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kb_id TEXT NOT NULL,
    ast_node_id TEXT,
    symbol_name TEXT NOT NULL,
    file_path TEXT,
    relation TEXT NOT NULL DEFAULT 'related_to',
    confidence DOUBLE PRECISION DEFAULT 0.8,
    created_at TEXT DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_kb_ast_kb ON kb_ast_links(kb_id);
CREATE INDEX IF NOT EXISTS idx_kb_ast_symbol ON kb_ast_links(symbol_name);
CREATE INDEX IF NOT EXISTS idx_kb_ast_file ON kb_ast_links(file_path);
CREATE INDEX IF NOT EXISTS idx_kb_ast_node ON kb_ast_links(ast_node_id);

-- ============================================================================
-- 5. Conversations & Messages
-- ============================================================================

CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    project TEXT,
    slot_id TEXT,
    source TEXT NOT NULL DEFAULT 'claude_cli',
    model TEXT,
    git_branch TEXT,
    jsonl_path TEXT,
    message_count INTEGER DEFAULT 0,
    started_at TEXT NOT NULL,
    ended_at TEXT,
    status TEXT DEFAULT 'active',
    analyzed_at TEXT,
    memory_forwarded_at TEXT,
    user_voice_forwarded_at TEXT,
    realtime_forwarded_at TEXT,
    analysis_version INTEGER DEFAULT 0,
    analysis_retries INTEGER DEFAULT 0,
    parent_session_id TEXT,
    task_id TEXT,
    deep_analyzed_message_id BIGINT DEFAULT 0,
    chat_type TEXT DEFAULT 'pty',
    conversation_type TEXT NOT NULL DEFAULT 'user',
    updated_at TEXT,
    llm_summary TEXT,
    embedding_provider TEXT,
    embedding BYTEA,
    session_timeline TEXT,
    timeline_built_at TEXT,
    exit_code INTEGER,
    habit_scanned_at TEXT,
    rolling_summary TEXT,
    last_summarized_msg_id BIGINT DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_conv_status ON conversations(status);
CREATE INDEX IF NOT EXISTS idx_conv_memory_pending ON conversations(slot_id, memory_forwarded_at);
CREATE INDEX IF NOT EXISTS idx_conv_realtime_pending ON conversations(slot_id, realtime_forwarded_at);
CREATE INDEX IF NOT EXISTS idx_conv_task_id ON conversations(task_id);

CREATE TABLE IF NOT EXISTS conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES conversations(id),
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    raw_content TEXT,
    message_uuid TEXT,
    parent_uuid TEXT,
    model TEXT,
    timestamp TEXT NOT NULL,
    metadata TEXT,
    tool_name TEXT,
    raw_role TEXT,
    content_types TEXT,
    has_image INTEGER DEFAULT 0,
    has_tool_use INTEGER DEFAULT 0,
    has_tool_result INTEGER DEFAULT 0,
    token_count INTEGER,
    -- FTS: tsvector replaces conversation_msg_fts
    fts_content tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce(content, ''))
    ) STORED
);
CREATE INDEX IF NOT EXISTS idx_conv_msg_session ON conversation_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_conv_msg_timestamp ON conversation_messages(timestamp);
CREATE UNIQUE INDEX IF NOT EXISTS idx_conv_msg_uuid ON conversation_messages(message_uuid);
CREATE INDEX IF NOT EXISTS idx_conv_msg_tool_name ON conversation_messages(tool_name);
CREATE INDEX IF NOT EXISTS idx_conv_msg_fts ON conversation_messages USING GIN(fts_content);
CREATE INDEX IF NOT EXISTS idx_conv_msg_trgm ON conversation_messages USING GIN(content gin_trgm_ops);

-- Message count trigger (replaces SQLite trg_msg_count_insert)
CREATE OR REPLACE FUNCTION trg_msg_count_fn() RETURNS trigger AS $$
BEGIN
    UPDATE conversations
    SET message_count = message_count + 1,
        updated_at = NEW.timestamp
    WHERE id = NEW.session_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_msg_count_insert
    AFTER INSERT ON conversation_messages
    FOR EACH ROW EXECUTE FUNCTION trg_msg_count_fn();

CREATE TABLE IF NOT EXISTS conversation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES conversations(id),
    event_type TEXT NOT NULL,
    content TEXT,
    raw_data TEXT,
    timestamp TEXT NOT NULL,
    event_uuid TEXT
);
CREATE INDEX IF NOT EXISTS idx_conv_event_session ON conversation_events(session_id);
CREATE INDEX IF NOT EXISTS idx_conv_event_type ON conversation_events(event_type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_conv_event_uuid
    ON conversation_events(session_id, event_uuid) WHERE event_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS conversation_tool_calls (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES conversations(id),
    message_id BIGINT,
    tool_name TEXT NOT NULL,
    input_summary TEXT,
    raw_input TEXT,
    output_summary TEXT,
    raw_output TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    duration_ms INTEGER,
    timestamp TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tc_session ON conversation_tool_calls(session_id);
CREATE INDEX IF NOT EXISTS idx_tc_name ON conversation_tool_calls(tool_name);
CREATE INDEX IF NOT EXISTS idx_tc_status ON conversation_tool_calls(status);

CREATE TABLE IF NOT EXISTS conversation_topic_vectors (
    session_id TEXT NOT NULL,
    chunk_idx INTEGER NOT NULL,
    topic TEXT NOT NULL,
    embedding BYTEA NOT NULL,
    embedding_vec vector(768),
    embedding_provider TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (session_id, chunk_idx)
);
CREATE INDEX IF NOT EXISTS idx_ctv_provider ON conversation_topic_vectors(embedding_provider);
CREATE INDEX IF NOT EXISTS idx_ctv_embedding ON conversation_topic_vectors USING hnsw(embedding_vec vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- ============================================================================
-- 6. Slot Tasks & Token Ledger
-- ============================================================================

CREATE TABLE IF NOT EXISTS slot_tasks (
    id TEXT PRIMARY KEY,
    slot_id TEXT NOT NULL,
    task_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    prompt_summary TEXT,
    source_sessions TEXT,
    output_count INTEGER DEFAULT 0,
    created_at TEXT NOT NULL,
    started_at TEXT,
    completed_at TEXT,
    duration_ms INTEGER,
    error TEXT,
    conversation_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_slot_tasks_slot ON slot_tasks(slot_id);
CREATE INDEX IF NOT EXISTS idx_slot_tasks_type ON slot_tasks(task_type);
CREATE INDEX IF NOT EXISTS idx_slot_tasks_created ON slot_tasks(created_at);

CREATE TABLE IF NOT EXISTS token_usage_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    slot_id TEXT,
    slot_task_id TEXT,
    conversation_id TEXT NOT NULL,
    model TEXT,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    cache_creation_tokens INTEGER NOT NULL DEFAULT 0,
    cache_read_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_token_ledger_conv ON token_usage_ledger(conversation_id);
CREATE INDEX IF NOT EXISTS idx_token_ledger_slot ON token_usage_ledger(slot_id);
CREATE INDEX IF NOT EXISTS idx_token_ledger_created ON token_usage_ledger(created_at);

-- ============================================================================
-- 7. Skills Engine
-- ============================================================================

CREATE TABLE IF NOT EXISTS skill_topics (
    topic TEXT PRIMARY KEY,
    description TEXT,
    aka TEXT,
    allowed_tools TEXT,
    file_path TEXT NOT NULL,
    hit_count INTEGER DEFAULT 0,
    last_hit_at TEXT,
    fragment_count INTEGER DEFAULT 0,
    total_lines INTEGER DEFAULT 0,
    checksum TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    requires_json TEXT,
    actions_json TEXT,
    context_hooks_json TEXT,
    embedding BYTEA,
    embedding_vec vector(768),
    embedding_provider TEXT
);
CREATE INDEX IF NOT EXISTS idx_skill_embedding ON skill_topics USING hnsw(embedding_vec vector_cosine_ops) WITH (m = 16, ef_construction = 64);

CREATE TABLE IF NOT EXISTS skill_blocks (
    id TEXT PRIMARY KEY,
    topic TEXT NOT NULL,
    block_type TEXT NOT NULL,
    title TEXT,
    content TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    -- FTS: tsvector replaces skill_fts
    fts_doc tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce(topic, '') || ' ' || coalesce(title, '') || ' ' || coalesce(content, ''))
    ) STORED
);
CREATE INDEX IF NOT EXISTS idx_skill_blocks_topic ON skill_blocks(topic);
CREATE INDEX IF NOT EXISTS idx_skill_blocks_status ON skill_blocks(status);
CREATE INDEX IF NOT EXISTS idx_skill_blocks_fts ON skill_blocks USING GIN(fts_doc);

CREATE TABLE IF NOT EXISTS skill_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic TEXT NOT NULL,
    content TEXT NOT NULL,
    checksum TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_skill_ver_topic ON skill_versions(topic);

CREATE TABLE IF NOT EXISTS skill_executions (
    id TEXT PRIMARY KEY,
    skill_topic TEXT NOT NULL,
    action_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'running',
    steps_total INTEGER NOT NULL,
    steps_completed INTEGER DEFAULT 0,
    context_json TEXT,
    error TEXT,
    triggered_by TEXT DEFAULT 'manual',
    created_at TEXT NOT NULL,
    completed_at TEXT,
    duration_ms INTEGER
);

-- ============================================================================
-- 8. Observability (Gemini, Incidents, Timeline, Backfill)
-- ============================================================================

CREATE TABLE IF NOT EXISTS gemini_requests (
    id TEXT PRIMARY KEY,
    caller TEXT NOT NULL,
    session_id TEXT,
    api_mode TEXT NOT NULL,
    model TEXT NOT NULL,
    prompt_chars INTEGER,
    response_chars INTEGER,
    queue_wait_ms INTEGER,
    duration_ms INTEGER,
    retry_count INTEGER DEFAULT 0,
    status TEXT NOT NULL,
    error_msg TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    prompt_text TEXT,
    response_text TEXT
);
CREATE INDEX IF NOT EXISTS idx_gemini_req_created ON gemini_requests(created_at);
CREATE INDEX IF NOT EXISTS idx_gemini_req_caller ON gemini_requests(caller);
CREATE INDEX IF NOT EXISTS idx_gemini_req_session ON gemini_requests(session_id);

CREATE TABLE IF NOT EXISTS gemini_file_uploads (
    file_hash TEXT PRIMARY KEY,
    file_uri TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    expires_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS incidents (
    id TEXT PRIMARY KEY,
    severity TEXT NOT NULL,
    source TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    server_id TEXT,
    raw_payload TEXT,
    board_task_id TEXT,
    dedupe_key TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_incidents_created ON incidents(created_at);
CREATE INDEX IF NOT EXISTS idx_incidents_dedupe ON incidents(dedupe_key, created_at);

CREATE TABLE IF NOT EXISTS system_timeline (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id TEXT,
    span_id TEXT,
    parent_span_id TEXT,
    event_type TEXT NOT NULL,
    summary TEXT,
    payload TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    -- FTS: tsvector replaces system_timeline_fts
    fts_doc tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce(summary, '') || ' ' || coalesce(payload, ''))
    ) STORED
);
CREATE INDEX IF NOT EXISTS idx_tl_created ON system_timeline(created_at);
CREATE INDEX IF NOT EXISTS idx_tl_type ON system_timeline(event_type);
CREATE INDEX IF NOT EXISTS idx_tl_trace ON system_timeline(trace_id);
CREATE INDEX IF NOT EXISTS idx_tl_parent ON system_timeline(parent_span_id);
CREATE INDEX IF NOT EXISTS idx_tl_fts ON system_timeline USING GIN(fts_doc);
CREATE INDEX IF NOT EXISTS idx_tl_trgm ON system_timeline USING GIN((coalesce(summary, '') || ' ' || payload) gin_trgm_ops);

CREATE TABLE IF NOT EXISTS router_chat_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_id BIGINT NOT NULL,
    session_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    archived_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    archive_reason TEXT NOT NULL DEFAULT 'clear'
);
CREATE INDEX IF NOT EXISTS idx_rca_session ON router_chat_archive(session_id);
CREATE INDEX IF NOT EXISTS idx_rca_archived ON router_chat_archive(archived_at);

CREATE TABLE IF NOT EXISTS backfill_progress (
    phase TEXT PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'pending',
    last_cursor BIGINT DEFAULT 0,
    total_estimated BIGINT DEFAULT 0,
    processed BIGINT DEFAULT 0,
    failed BIGINT DEFAULT 0,
    started_at TEXT,
    completed_at TEXT,
    updated_at TEXT DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS backfill_failures (
    session_id TEXT NOT NULL,
    phase TEXT NOT NULL,
    retry_count INTEGER DEFAULT 1,
    last_error TEXT,
    updated_at TEXT DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (session_id, phase)
);

-- ============================================================================
-- 9. Vision & Translation Caches
-- ============================================================================

CREATE TABLE IF NOT EXISTS image_descriptions (
    image_hash TEXT PRIMARY KEY,
    media_type TEXT NOT NULL,
    description TEXT NOT NULL,
    char_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS message_translations (
    message_id BIGINT PRIMARY KEY,
    translation TEXT NOT NULL,
    source_lang TEXT NOT NULL DEFAULT 'en',
    target_lang TEXT NOT NULL DEFAULT 'zh',
    model TEXT,
    duration_ms INTEGER,
    created_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

-- ============================================================================
-- 10. AST Code Index
-- ============================================================================

CREATE TABLE IF NOT EXISTS ast_nodes (
    id TEXT PRIMARY KEY,
    repo TEXT NOT NULL,
    file_path TEXT NOT NULL,
    node_type TEXT NOT NULL,
    name TEXT NOT NULL,
    signature TEXT NOT NULL,
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    is_exported INTEGER DEFAULT 0,
    docstring TEXT,
    stub_content TEXT NOT NULL,
    calls TEXT,
    embedding BYTEA,
    embedding_vec vector(768),
    embedding_provider TEXT,
    updated_at TEXT DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    -- FTS: pg_trgm for code symbols (replaces ast_nodes_fts)
    fts_doc tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(signature, '') || ' ' || coalesce(docstring, '') || ' ' || coalesce(stub_content, ''))
    ) STORED
);
CREATE INDEX IF NOT EXISTS idx_ast_repo_file ON ast_nodes(repo, file_path);
CREATE INDEX IF NOT EXISTS idx_ast_name ON ast_nodes(name);
CREATE INDEX IF NOT EXISTS idx_ast_node_type ON ast_nodes(node_type);
CREATE INDEX IF NOT EXISTS idx_ast_exported ON ast_nodes(is_exported);
CREATE INDEX IF NOT EXISTS idx_ast_provider ON ast_nodes(embedding_provider);
CREATE INDEX IF NOT EXISTS idx_ast_fts ON ast_nodes USING GIN(fts_doc);
CREATE INDEX IF NOT EXISTS idx_ast_trgm ON ast_nodes USING GIN(name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_ast_embedding ON ast_nodes USING hnsw(embedding_vec vector_cosine_ops) WITH (m = 16, ef_construction = 64);

CREATE TABLE IF NOT EXISTS ast_file_meta (
    repo TEXT NOT NULL,
    file_path TEXT NOT NULL,
    commit_hash TEXT NOT NULL,
    node_count INTEGER DEFAULT 0,
    updated_at TEXT DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (repo, file_path)
);

-- ============================================================================
-- 11. Beacons (Code navigation)
-- ============================================================================

CREATE TABLE IF NOT EXISTS beacons (
    id TEXT PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    created_at TEXT DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    updated_at TEXT DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    harvest_count INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS beacon_nodes (
    beacon_id TEXT NOT NULL REFERENCES beacons(id) ON DELETE CASCADE,
    repo TEXT NOT NULL,
    file_path TEXT NOT NULL,
    symbol_name TEXT NOT NULL,
    annotation TEXT,
    PRIMARY KEY (beacon_id, repo, file_path, symbol_name)
);
CREATE INDEX IF NOT EXISTS idx_bn_symbol ON beacon_nodes(symbol_name);
CREATE INDEX IF NOT EXISTS idx_bn_beacon ON beacon_nodes(beacon_id);

-- ============================================================================
-- 12. Retrospective & Narration
-- ============================================================================

CREATE TABLE IF NOT EXISTS message_narrations (
    message_id BIGINT PRIMARY KEY,
    session_id TEXT NOT NULL,
    step_title TEXT NOT NULL,
    step_intent TEXT NOT NULL,
    step_result TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_narrations_session ON message_narrations(session_id);

CREATE TABLE IF NOT EXISTS narration_cursors (
    session_id TEXT PRIMARY KEY,
    last_processed_id BIGINT NOT NULL DEFAULT 0,
    batch_index INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'idle',
    retry_count INTEGER NOT NULL DEFAULT 0,
    total_messages INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS retrospective_results (
    session_id TEXT PRIMARY KEY,
    trigger_reason TEXT NOT NULL,
    quick_stats TEXT NOT NULL,
    full_analysis TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_retro_created ON retrospective_results(created_at);

-- ============================================================================
-- 13. Prompt Snapshots & Consumer Watermarks
-- ============================================================================

CREATE TABLE IF NOT EXISTS prompt_snapshots (
    task_id TEXT PRIMARY KEY,
    prompt TEXT NOT NULL,
    cited_kb_ids TEXT NOT NULL DEFAULT '[]',
    category TEXT NOT NULL DEFAULT 'other',
    task_outcome TEXT,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_prompt_snap_cat ON prompt_snapshots(category);

CREATE TABLE IF NOT EXISTS consumer_watermarks (
    consumer_name TEXT NOT NULL,
    session_id TEXT NOT NULL,
    last_processed_msg_id BIGINT,
    last_processed_time TEXT,
    extra TEXT,
    PRIMARY KEY (consumer_name, session_id)
);
CREATE INDEX IF NOT EXISTS idx_cw_consumer ON consumer_watermarks(consumer_name);

CREATE TABLE IF NOT EXISTS message_labels (
    message_id BIGINT NOT NULL,
    label TEXT NOT NULL,
    value TEXT,
    source TEXT NOT NULL DEFAULT 'rule',
    created_at TEXT NOT NULL DEFAULT to_char(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (message_id, label)
);
CREATE INDEX IF NOT EXISTS idx_msg_label ON message_labels(label, value);
CREATE INDEX IF NOT EXISTS idx_msg_label_mid ON message_labels(message_id);
