(work-order-plan
  :schema "missiond.work-order.plan.v1"
  :id "wo-20260605210005-Harden-Jarvis-provider-chain-gov"
  :intent "wo-20260605210005-Harden-Jarvis-provider-chain-gov"
  :status draft
  :accepted_shards
    ((shard default
       :accepted_shard_id "wo-20260605210005-Harden-Jarvis-provider-chain-gov-shard-default"
       :read_scope ["."]
       :write_scope [".missiond/v3/evidence/codex-boot-context.lisp"
                     ".missiond/v3/shards/memory-knowledge-runtime.lisp"
                     ".missiond/v3/shards/request-runtime.lisp"
                     "AGENTS.md"
                     "crates/missiond-core/src/v3_contracts.rs"
                     "crates/missiond-core/src/ws/server.rs"
                     "crates/missiond-daemon/src/context/v3_contracts/generated.rs"
                     "crates/missiond-daemon/src/context/v3_runtime_defaults/generated.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/context_gather.rs"
                     "crates/missiond-daemon/src/provider_box/codex_driver.rs"
                     "crates/missiond-daemon/src/provider_box/http_adapter.rs"
                     "crates/missiond-daemon/src/provider_box/mod.rs"
                     "crates/missiond-daemon/src/provider_box/types.rs"
                     "crates/missiond-daemon/src/workers/local/pty_event_worker.rs"
                     "crates/missiond-mcp/src/tools/knowledge/context_gather.rs"
                     "crates/missiond-pty/src/manager.rs"
                     "packages/board/src/components/Conversations.tsx"
                     "packages/board/src/components/XjpcodePanel.tsx"
                     "scripts/check-v3-codex-boot-context-isomorphism.mjs"
                     "scripts/check-v3-context-surface-registry.mjs"
                     "scripts/check-v3-interactive-provider-box.mjs"
                     "scripts/check-v3-memory-kb-isomorphism.mjs"
                     "scripts/deploy-daemon.sh"
                     "scripts/generated/v3_contracts.d.ts"
                     "scripts/generated/v3_contracts.mjs"
                     "scripts/generated/v3_runtime_defaults.mjs"
                     "scripts/mission-context-pack.mjs"
                     "scripts/smoke-jarvis-intent-plan-dispatch.mjs"
                     ".missiond/work-orders/wo-20260605210005-Harden-Jarvis-provider-chain-gov/plan.lisp"]
       :acceptance ["node scripts/check-project-ssot-universe.mjs --json"
                    "node scripts/check-v3-interaction-gateway-isomorphism.mjs --json"
                    "node scripts/check-v3-grounded-dispatch-isomorphism.mjs --json"
                    "node scripts/check-v3-workflow-isomorphism.mjs --json"
                    "node scripts/check-v3-interactive-provider-box.mjs --json"
                    "node scripts/check-v3-macmini-self-update-lane.mjs --json"
                    "node scripts/check-runtime-evidence-redaction.mjs --json"
                    "cargo test -p missiond-core jarvis_stage_errors_have_standard_phase_codes"
                    "cargo test -p missiond-daemon rollout_extractor_accepts_event_msg_agent_message_final"
                    "cargo test -p missiond-daemon codex_durable_final_idle_grace_has_safe_floor"
                    "cargo test -p missiond-daemon codex_usage_limit_block_is_not_model_switch_prompt"
                    "cargo check -p missiond-core -p missiond-daemon"])))
