(work-order-plan
  :schema "missiond.work-order.plan.v1"
  :id "wo-20260528114000-jarvis-codex-intent-author-lane"
  :intent "wo-20260528114000-jarvis-codex-intent-author-lane"
  :status draft
  :accepted_shards
    ((shard default
       :accepted_shard_id "wo-20260528114000-jarvis-codex-intent-author-lane-shard-default"
       :read_scope ["."]
       :write_scope [".missiond/v3/evidence/workstation-pool.lisp"
                     ".missiond/v3/shards/implementation/request-surfaces.lisp"
                     ".missiond/v3/shards/universe/behavior-closure.lisp"
                     ".missiond/v3/shards/workstation-runtime.lisp"
                     "crates/missiond-core/src/lib.rs"
                     "crates/missiond-core/src/ws/mod.rs"
                     "crates/missiond-core/src/ws/server.rs"
                     "crates/missiond-daemon/src/context/v3_blueprint_runtime.rs"
                     "crates/missiond-daemon/src/context/v3_contracts/generated.rs"
                     "crates/missiond-daemon/src/context/v3_runtime_defaults/generated.rs"
                     "crates/missiond-daemon/src/main.rs"
                     "scripts/check-v3-interaction-gateway-isomorphism.mjs"
                     "scripts/check-v3-workstation-pool-isomorphism.mjs"
                     "scripts/generated/v3_contracts.d.ts"
                     "scripts/generated/v3_contracts.mjs"
                     "scripts/generated/v3_runtime_defaults.mjs"
                     "scripts/smoke-jarvis-intent-plan-dispatch.mjs"
                     "scripts/smoke-jarvis-interaction.mjs"
                     ".missiond/work-orders/wo-20260528114000-jarvis-codex-intent-author-lane/intent.lisp"
                     ".missiond/work-orders/wo-20260528114000-jarvis-codex-intent-author-lane/plan.lisp"
                     ".missiond/work-orders/wo-20260528114000-jarvis-codex-intent-author-lane/audit.lisp"]
       :acceptance ["node scripts/project-v3-contracts.mjs --check --json"
                    "node scripts/compile-v3-runtime.mjs --check --json"
                    "node scripts/check-v3-interaction-gateway-isomorphism.mjs --json"
                    "node scripts/check-v3-workstation-pool-isomorphism.mjs --json"
                    "node scripts/check-v3-behavior-closure.mjs --json"
                    "node scripts/check-v3-code-isomorphism-complete.mjs --json"
                    "node scripts/check-v3-runtime-domain-projections.mjs --json"
                    "bash scripts/rustfmt-missiond.sh --check"
                    "cargo test -p missiond-core ws::server::tests -- --nocapture"
                    "cargo check -p missiond-daemon"
                    "git diff --check"
                    "node scripts/check-v3-final-convergence.mjs --json --static-only (MissionD local subchecks pass; external /Users/jinchen/Projects/xjpcode checker still fails)"])))
