// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module cc_tasks)

use serde_json::json;
use crate::ToolDefinition;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_cc_query =====
        ToolDefinition::new(
            "mission_cc_query",
            "Claude Code 任务监控。sessions/tasks/overview/in_progress",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["sessions", "tasks", "overview", "in_progress"]},
                    "sessionId": {"type": "string", "description": "[tasks] 会话 ID"},
                    "projectPath": {"type": "string", "description": "[sessions/tasks] 项目路径"},
                    "activeOnly": {"type": "boolean", "description": "[sessions] 仅活跃会话", "default": true}
                }
            }),
        ),

        // ===== mission_cc_swarm =====
        ToolDefinition::new(
            "mission_cc_swarm",
            "通过 PTY 触发 Claude Code Swarm 模式并行执行",
            json!({
                "type": "object",
                "required": ["slotId", "tasks"],
                "properties": {
                    "slotId": {"type": "string", "description": "PTY 工位 ID"},
                    "tasks": {"type": "array", "description": "要执行的任务列表"},
                    "teammateCount": {"type": "number", "description": "并行 Agent 数量", "default": 3},
                    "timeoutMs": {"type": "number", "default": 600000}
                }
            }),
        ),

    ]
}
