// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module compute_slot)

use serde_json::json;
use crate::ToolDefinition;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_compute_slot =====
        ToolDefinition::new(
            "mission_compute_slot",
            "动态计算工位管理。create/terminate/extend/list。TTL 生命周期，最多 5 个活跃",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["create", "terminate", "extend", "list"]},
                    "template": {"type": "string", "description": "[create] 模板 ID: coder/ops"},
                    "objective": {"type": "string", "description": "[create] 意图描述"},
                    "cwd": {"type": "string", "description": "[create] 工作目录"},
                    "max_ttl": {"type": "integer", "description": "[create] 最大 TTL 秒(默认 4h, 上限 8h)", "default": 14400},
                    "slot_id": {"type": "string", "description": "[terminate/extend] 动态 slot ID"},
                    "additional_seconds": {"type": "integer", "description": "[extend] 延长秒数(每次上限 3600)"},
                    "status": {"type": "string", "description": "[list] active/terminated"}
                }
            }),
        ),

    ]
}
