// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module compute_slot)

use crate::ToolDefinition;
use serde_json::json;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_compute_slot =====
        ToolDefinition::new(
            "mission_compute_slot",
            "动态计算工位管理。create/terminate/extend/list。TTL 生命周期，最多 5 个活跃",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["create", "terminate", "extend", "list"]},
                    "template": {"type": "string", "description": "[create] 模板 ID: coder/ops"},
                    "objective": {"type": "string", "description": "[create] 意图描述；仅作为工位元数据，不会被自动发送"},
                    "initial_prompt": {"type": "string", "description": "[create] 可选显式 warm-up prompt；只有传入此字段才会在 slot Idle 后发送"},
                    "initialPrompt": {"type": "string", "description": "[create] initial_prompt camelCase alias"},
                    "cwd": {"type": "string", "description": "[create] 工作目录"},
                    "max_ttl": {"type": "integer", "description": "[create] 最大 TTL 秒(默认 4h, 上限 8h)", "default": 14400},
                    "model": {"type": "string", "description": "[create] 可选 CLI 模型覆盖；default/claude-code-default 表示不传 --model"},
                    "model_profile": {"type": "string", "description": "[create] 可选模型 profile；coding-default-opus-4-7 表示 Claude Code Default(Opus 4.7/1M)"},
                    "modelProfile": {"type": "string", "description": "[create] model_profile camelCase alias"},
                    "slot_id": {"type": "string", "description": "[terminate/extend] 动态 slot ID"},
                    "additional_seconds": {"type": "integer", "description": "[extend] 延长秒数(每次上限 3600)"},
                    "status": {"type": "string", "description": "[list] active/terminated"}
                }
            }),
        ),
    ]
}
