// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module job)

use crate::ToolDefinition;
use serde_json::json;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_job_poll =====
        ToolDefinition::new(
            "mission_job_poll",
            "轮询异步 Job 状态。返回 status(running/completed/failed) + result/error",
            json!({
                "type": "object",
                "required": ["job_id"],
                "properties": {
                    "job_id": {"type": "string", "description": "Job ID"},
                    "action": {"type": "string", "enum": ["poll", "list", "cancel"], "default": "poll"}
                }
            }),
        ),
    ]
}
