// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module process)

use serde_json::json;
use crate::ToolDefinition;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_agent =====
        ToolDefinition::new(
            "mission_agent",
            "Agent 进程管理。spawn/kill/restart/list",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["spawn", "kill", "restart", "list"]},
                    "slotId": {"type": "string", "description": "[spawn/kill/restart] 工位 ID"},
                    "visible": {"type": "boolean", "description": "[spawn/restart] 打开终端窗口"},
                    "autoRestart": {"type": "boolean", "description": "[spawn] 崩溃后自动重启"}
                }
            }),
        ),

        // ===== mission_slots =====
        ToolDefinition::new(
            "mission_slots",
            "列出所有工位配置",
            json!({
                "type": "object",
                "properties": {
                }
            }),
        ),

        // ===== mission_inbox =====
        ToolDefinition::new(
            "mission_inbox",
            "获取收件箱消息",
            json!({
                "type": "object",
                "properties": {
                    "unreadOnly": {"type": "boolean", "description": "仅未读", "default": true},
                    "limit": {"type": "number", "default": 10}
                }
            }),
        ),

    ]
}
