// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module pty)

use crate::ToolDefinition;
use serde_json::json;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_pty_spawn =====
        ToolDefinition::new(
            "mission_pty_spawn",
            "启动 PTY 交互式会话。默认异步返回不等待 Idle",
            json!({
                "type": "object",
                "required": ["slotId"],
                "properties": {
                    "slotId": {"type": "string"},
                    "taskId": {"type": "string", "description": "Task-bound spawn scope; requires exact spawn capability when present"},
                    "grantId": {"type": "string", "description": "Exact subject-bound spawn capability grant id"},
                    "subjectKind": {"type": "string", "description": "Capability subject kind, default worker"},
                    "subjectId": {"type": "string", "description": "Capability subject id, default slotId"},
                    "operatorConfirm": {"type": "boolean", "description": "Required for operator-managed diagnostic spawn without taskId/grant"},
                    "waitForIdle": {"type": "boolean", "description": "等待 Claude 就绪", "default": false},
                    "timeoutSecs": {"type": "number", "description": "Idle 超时秒数(waitForIdle=true 时生效)", "default": 60},
                    "autoRestart": {"type": "boolean", "description": "崩溃后自动重启"},
                    "mcpConfigPath": {"type": "string", "description": "MCP 配置文件路径(JSON)"},
                    "operatorShell": {"type": "boolean", "description": "operatorConfirm 专用诊断 shell；用于 CLI 教学/help，不用于任务工位", "default": false}
                }
            }),
        ),
        // ===== mission_pty_send =====
        ToolDefinition::new(
            "mission_pty_send",
            "向 PTY 发送消息。默认 fire-and-forget",
            json!({
                "type": "object",
                "required": ["slotId", "message"],
                "properties": {
                    "slotId": {"type": "string"},
                    "message": {"type": "string"},
                    "waitForResponse": {"type": "boolean", "description": "阻塞等待回复", "default": false},
                    "timeoutMs": {"type": "number", "description": "[waitForResponse=true] 默认/上下限由 V3 workstation-config timeout-policy pty-send-blocking 投影", "default": 300000}
                }
            }),
        ),
        // ===== mission_pty_key =====
        ToolDefinition::new(
            "mission_pty_key",
            "向 PTY 发送一个 allowlist 语义按键。文本输入请使用逐步 raw/write 教学路径；完整消息提交请使用 mission_pty_send。",
            json!({
                "type": "object",
                "required": ["slotId", "key"],
                "properties": {
                    "slotId": {"type": "string"},
                    "key": {
                        "type": "string",
                        "enum": [
                            "enter", "return", "esc", "escape", "tab",
                            "up", "down", "right", "left",
                            "backspace", "delete", "del",
                            "home", "end",
                            "pageup", "page-up", "pagedown", "page-down",
                            "ctrl-c", "ctrl-d", "eof"
                        ],
                        "description": "一次只发送一个人类按键；发送后调用 mission_pty_status/read 观察结果。ctrl-d 对 AGY TUI 使用 kitty CSI 100;5u，plain EOT 用 eof。"
                    }
                }
            }),
        ),
        // ===== mission_pty_text =====
        ToolDefinition::new(
            "mission_pty_text",
            "向 PTY 输入一段可打印文本，但不按回车、不提交消息。Enter/Esc/Tab/Ctrl/方向键必须使用 mission_pty_key。",
            json!({
                "type": "object",
                "required": ["slotId", "text"],
                "properties": {
                    "slotId": {"type": "string"},
                    "text": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 65536,
                        "description": "只允许可打印文本；不能包含换行、回车、ESC 或其他控制字符。提交时另行调用 mission_pty_key(key='enter')。"
                    }
                }
            }),
        ),
        // ===== mission_pty_read =====
        ToolDefinition::new(
            "mission_pty_read",
            "读取 PTY 内容。screen/history/logs",
            json!({
                "type": "object",
                "required": ["action", "slotId"],
                "properties": {
                    "action": {"type": "string", "enum": ["screen", "history", "logs"]},
                    "slotId": {"type": "string"},
                    "lines": {"type": "number", "description": "[screen] 最后 N 行"}
                }
            }),
        ),
        // ===== mission_pty_signal =====
        ToolDefinition::new(
            "mission_pty_signal",
            "向 PTY 发送信号。kill/interrupt",
            json!({
                "type": "object",
                "required": ["action", "slotId"],
                "properties": {
                    "action": {"type": "string", "enum": ["kill", "interrupt"]},
                    "slotId": {"type": "string"}
                }
            }),
        ),
        // ===== mission_pty_confirm =====
        ToolDefinition::new(
            "mission_pty_confirm",
            "发送确认响应(工具使用确认对话框)。response 表达语义选择；运行时用上下键/回车操作菜单，不发送数字快捷键。",
            json!({
                "type": "object",
                "required": ["slotId", "response"],
                "properties": {
                    "slotId": {"type": "string"},
                    "response": {
                        "oneOf": [{"type": "boolean"}, {"type": "number"}, {"type": "string"}],
                        "description": "true/false、yes/no/allow/cancel、或选项编号/option:N。禁止直接输入原始文本；原始文本请用 mission_pty_send。"
                    }
                }
            }),
        ),
        // ===== mission_pty_status =====
        ToolDefinition::new(
            "mission_pty_status",
            "获取 PTY 会话状态",
            json!({
                "type": "object",
                "properties": {
                    "slotId": {"type": "string", "description": "工位 ID(不填返回所有)"}
                }
            }),
        ),
        // ===== mission_pty_screenshot =====
        ToolDefinition::new(
            "mission_pty_screenshot",
            "截取 PTY 终端截图(PNG)，返回文件路径",
            json!({
                "type": "object",
                "required": ["slotId"],
                "properties": {
                    "slotId": {"type": "string"}
                }
            }),
        ),
    ]
}
