// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module slot)

use serde_json::json;
use crate::ToolDefinition;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_slot_history =====
        ToolDefinition::new(
            "mission_slot_history",
            "查询工位任务历史(realtime_extract/deep_analysis/kb_gc 等)",
            json!({
                "type": "object",
                "properties": {
                    "slotId": {"type": "string", "description": "工位 ID(不传查所有)"},
                    "taskType": {"type": "string", "description": "realtime_extract/deep_analysis/kb_gc"},
                    "status": {"type": "string", "description": "pending/running/completed/failed"},
                    "limit": {"type": "integer", "default": 20},
                    "stats": {"type": "boolean", "description": "true 时只返回汇总统计"}
                }
            }),
        ),

        // ===== mission_pause =====
        ToolDefinition::new(
            "mission_pause",
            "全局暂停/恢复所有工位的工作分派",
            json!({
                "type": "object",
                "properties": {
                    "action": {"type": "string", "enum": ["pause", "resume", "status"], "default": "status"}
                }
            }),
        ),

    ]
}
