// 🤖 PARTIALLY GENERATED BY FORGE — manual additions documented below.
//
// Source: .missiond/intent-tools.lisp (module task_delegate).
//
// Manual additions on top of the Forge baseline:
//   * mission_swarm_run :: target_project_ids / targetProjectIds / target_projects /
//     targetProjects array — multi-project structural pass required by
//     V3 swarm-dispatch-policy / project-ssot-convergence workflow. Fix for
//     "tool resolved target_projects to missiond only" defect observed during
//     BoardTask 31e5449c-e315-4003-ad59-c3eebd5eb837.
// When Forge regenerates this file, preserve the swarm target_project_ids
// schema entries below.

use crate::ToolDefinition;
use serde_json::{json, Value};

/// BoardTask 31a99a30 :: dedup-linkage knobs added on top of the legacy
/// `mission_task_delegate` schema. Kept in a sibling helper so the json!
/// macro inside `task_delegate_schema` stays under the default recursion
/// limit (each properties entry recurses through the macro twice).
fn dedup_linkage_properties() -> Value {
    json!({
        "parent_board_task_id": {"type": "string", "description": "父 BoardTask ID。Dedup 守护以此识别同一委派链"},
        "parentBoardTaskId": {"type": "string", "description": "parent_board_task_id camelCase alias"},
        "parent_id": {"type": "string", "description": "parent_board_task_id alias"},
        "parentId": {"type": "string", "description": "parent_board_task_id camelCase alias"},
        "source_board_task_id": {"type": "string", "description": "源 BoardTask ID。多跳 master/plan 链路保留原始锚点；Dedup 守护以此识别相同 source"},
        "sourceBoardTaskId": {"type": "string", "description": "source_board_task_id camelCase alias"},
        "source_id": {"type": "string", "description": "source_board_task_id alias"},
        "sourceId": {"type": "string", "description": "source_board_task_id camelCase alias"},
        "allow_duplicate_code_worker": {"type": "boolean", "default": false, "description": "默认 false：当现有 active BoardTask 已经覆盖重叠 write_scope 时，拒绝再生 code worker。设为 true 显式允许并发"},
        "allowDuplicateCodeWorker": {"type": "boolean", "description": "allow_duplicate_code_worker camelCase alias"},
        "force_duplicate_code_worker": {"type": "boolean", "description": "allow_duplicate_code_worker alias"},
        "forceDuplicateCodeWorker": {"type": "boolean", "description": "allow_duplicate_code_worker camelCase alias"}
    })
}

/// BoardTask 9b88cfff :: mechanic executor-lane knobs added when
/// mechanic-collaboration-boundary flipped to `mechanic-executor-lane-enabled`.
/// Kept in a sibling helper for the same reason as dedup_linkage_properties:
/// each json! property entry double-recurses through the macro and inlining
/// these next to the base schema overflows the default recursion limit.
fn mechanic_lane_properties() -> Value {
    json!({
        "mechanic_mode": {"type": "string", "enum": ["dry-run", "repair"], "default": "dry-run", "description": "engine_hint=mechanic 时使用：dry-run 只诊断，repair 才允许 mechanic 尝试修复"},
        "mechanicMode": {"type": "string", "description": "mechanic_mode camelCase alias"},
        "mechanic_target": {"type": "string", "description": "engine_hint=mechanic 时传给 mechanic --target；缺省使用 accepted_shard_id"},
        "mechanicTarget": {"type": "string", "description": "mechanic_target camelCase alias"},
        "mechanic_bin": {"type": "string", "description": "mechanic binary 路径；缺省 MISSIOND_MECHANIC_BIN 或 mechanic"},
        "mechanicBin": {"type": "string", "description": "mechanic_bin camelCase alias"},
        "mechanic_max_turns": {"type": "integer", "description": "engine_hint=mechanic 时传给 mechanic --max-turns"},
        "mechanicMaxTurns": {"type": "integer", "description": "mechanic_max_turns camelCase alias"},
        "mechanic_model": {"type": "string", "description": "engine_hint=mechanic 时传给 mechanic --model；缺省使用 mechanic 配置默认值"},
        "mechanicModel": {"type": "string", "description": "mechanic_model camelCase alias"}
    })
}

fn task_delegate_schema() -> Value {
    let mut schema = json!({
        "type": "object",
        "required": ["objective"],
        "properties": {
            "objective": {"type": "string", "description": "任务目标(自然语言)"},
            "intent": {"type": "string", "description": "意图类型决定 slot 模板", "enum": ["code", "ops", "research", "general"], "default": "general"},
            "cwd": {"type": "string", "description": "工作目录", "default": "~/Projects"},
            "timeout_secs": {"type": "integer", "description": "超时秒数(上限 7200)", "default": 1800},
            "priority": {"type": "string", "enum": ["high", "medium", "low"], "default": "medium"},
            "depends_on": {"type": "array", "description": "前置任务 ID 列表(DAG)"},
            "context_hints": {"type": "array", "description": "兼容字段；默认不预加载 KB/Skill。请使用 read_scope/context_pack_path 明确上下文"},
            "model": {"type": "string", "description": "可选 CLI 模型覆盖；default/claude-code-default 表示不传 --model"},
            "model_profile": {"type": "string", "description": "可选模型 profile；coding-default-opus-4-7 表示 Claude Code Default(Opus 4.7/1M)"},
            "modelProfile": {"type": "string", "description": "model_profile camelCase alias"},
            "task_class": {"type": "string", "description": "两阶段工位任务类型，如 context-pack/code/review/ops"},
            "taskClass": {"type": "string", "description": "task_class camelCase alias"},
            "pool_hint": {"type": "string", "description": "建议工位池，如 claude-code-default / gemini-ultra-pro"},
            "poolHint": {"type": "string", "description": "pool_hint camelCase alias"},
            "engine_hint": {"type": "string", "description": "建议引擎，如 claude-code / gemini / codex / mechanic"},
            "engineHint": {"type": "string", "description": "engine_hint camelCase alias"},
            "xjpcode_worker_url": {"type": "string", "description": "engine_hint=xjpcode local smoke/dev override. Only loopback URLs are accepted unless daemon policy explicitly allows remote argument overrides."},
            "xjpcodeWorkerUrl": {"type": "string", "description": "xjpcode_worker_url camelCase alias"},
            "context_pack_path": {"type": "string", "description": "两阶段 context-pack Lisp 路径"},
            "contextPackPath": {"type": "string", "description": "context_pack_path camelCase alias"},
            "accepted_shard_id": {"type": "string", "description": "已接受 exact shard ID。code/implementation 工位必填，防止宽目标直接进入实现工位"},
            "acceptedShardId": {"type": "string", "description": "accepted_shard_id camelCase alias"},
            "read_scope": {"type": "array", "description": "允许读取路径列表 (review-class 任务必填，与 write_scope 区分)"},
            "readScope": {"type": "array", "description": "read_scope camelCase alias"},
            "write_scope": {"type": "array", "description": "允许写入路径列表"},
            "writeScope": {"type": "array", "description": "write_scope camelCase alias"},
            "must_not_touch": {"type": "array", "description": "禁止修改路径列表"},
            "mustNotTouch": {"type": "array", "description": "must_not_touch camelCase alias"},
            "acceptance": {"type": "array", "description": "验收命令列表"},
            "acceptance_commands": {"type": "array", "description": "acceptance alias"},
            "acceptanceCommands": {"type": "array", "description": "acceptance_commands camelCase alias"}
        }
    });
    merge_properties(&mut schema, dedup_linkage_properties());
    merge_properties(&mut schema, mechanic_lane_properties());
    schema
}

fn merge_properties(schema: &mut Value, extras: Value) {
    if let (Some(properties), Value::Object(extras)) = (
        schema.get_mut("properties").and_then(|v| v.as_object_mut()),
        extras,
    ) {
        for (key, value) in extras {
            properties.insert(key, value);
        }
    }
}

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_task_delegate =====
        ToolDefinition::new(
            "mission_task_delegate",
            "声明式任务委派：描述目标，Daemon 自主选 slot/创建/执行/回报",
            task_delegate_schema(),
        ),
        // ===== mission_swarm_run =====
        ToolDefinition::new(
            "mission_swarm_run",
            "两阶段并发工位入口：先生成/派发 context-pack 调查任务，再按 accepted shards 派发实现任务",
            json!({
                "type": "object",
                "required": ["objective"],
                "properties": {
                    "objective": {"type": "string", "description": "swarm 总目标"},
                    "project_id": {"type": "string", "description": "项目 ID，如 missiond / jarvis-forge"},
                    "projectId": {"type": "string", "description": "project_id camelCase alias"},
                    "target_project_ids": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Multi-project swarm targets (registered project ids). Required when the objective spans more than one project; if omitted, target_projects collapses to project_id only and the swarm cannot fan out. Aliases: targetProjectIds / target_projects / targetProjects."
                    },
                    "targetProjectIds": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "target_project_ids camelCase alias"
                    },
                    "target_projects": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "target_project_ids snake_case alias"
                    },
                    "targetProjects": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "target_project_ids camelCase alias"
                    },
                    "context_pack_path": {"type": "string", "description": "可选 context-pack Lisp 路径"},
                    "contextPackPath": {"type": "string", "description": "context_pack_path alias"},
                    "accepted_shard_id": {"type": "string", "description": "实现阶段必填：accepted shard ID。read-only 调查阶段无需提供"},
                    "acceptedShardId": {"type": "string", "description": "accepted_shard_id alias"},
                    "max_claude_workers": {"type": "integer", "default": 8},
                    "maxClaudeWorkers": {"type": "integer"},
                    "max_gemini_workers": {"type": "integer", "default": 2},
                    "maxGeminiWorkers": {"type": "integer"},
                    "write_policy": {"type": "string", "enum": ["read-only", "lisp-first", "code"], "default": "read-only"},
                    "writePolicy": {"type": "string"},
                    "dry_run": {"type": "boolean", "default": true},
                    "dryRun": {"type": "boolean"},
                    "read_scope": {"type": "array"},
                    "readScope": {"type": "array"},
                    "write_scope": {"type": "array"},
                    "writeScope": {"type": "array"},
                    "must_not_touch": {"type": "array"},
                    "mustNotTouch": {"type": "array"},
                    "acceptance": {"type": "array"},
                    "acceptance_commands": {"type": "array"},
                    "acceptanceCommands": {"type": "array"},
                    "timeout_secs": {"type": "integer", "default": 1800},
                    "timeoutSecs": {"type": "integer"}
                }
            }),
        ),
    ]
}
