// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module task_delegate)

use crate::ToolDefinition;
use serde_json::json;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_task_delegate =====
        ToolDefinition::new(
            "mission_task_delegate",
            "声明式任务委派：描述目标，Daemon 自主选 slot/创建/执行/回报",
            json!({
                "type": "object",
                "required": ["objective"],
                "properties": {
                    "objective": {"type": "string", "description": "任务目标(自然语言)"},
                    "intent": {"type": "string", "description": "意图类型决定 slot 模板", "enum": ["code", "ops", "research", "general"], "default": "general"},
                    "cwd": {"type": "string", "description": "工作目录", "default": "~/Projects"},
                    "timeout_secs": {"type": "integer", "description": "超时秒数(上限 7200)", "default": 1800},
                    "priority": {"type": "string", "enum": ["high", "medium", "low"], "default": "medium"},
                    "depends_on": {"type": "array", "description": "前置任务 ID 列表(DAG)"},
                    "context_hints": {"type": "array", "description": "上下文关键词，预加载 KB/Skill"},
                    "model": {"type": "string", "description": "可选 CLI 模型覆盖；default/claude-code-default 表示不传 --model"},
                    "model_profile": {"type": "string", "description": "可选模型 profile；coding-default-opus-4-7 表示 Claude Code Default(Opus 4.7/1M)"},
                    "modelProfile": {"type": "string", "description": "model_profile camelCase alias"}
                }
            }),
        ),
    ]
}
