// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module worker)

use serde_json::json;
use crate::ToolDefinition;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_worker =====
        ToolDefinition::new(
            "mission_worker",
            "后台 Worker + LLM 闸口管理。list: 列出状态+闸口; control: 暂停/恢复",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["list", "control"]},
                    "target": {"type": "string", "description": "[control] Worker 名或 LLM 闸口(gemini/sonnet/codex)"},
                    "control_action": {"type": "string", "description": "[control] 操作", "enum": ["pause", "resume", "status"]}
                }
            }),
        ),

        // ===== mission_control =====
        ToolDefinition::new(
            "mission_control",
            "统一调控闸口。级联机制: 关 provider=sonnet 自动暂停依赖 Sonnet 的 Worker",
            json!({
                "type": "object",
                "required": ["target_type", "action"],
                "properties": {
                    "target_type": {"type": "string", "enum": ["global", "provider", "domain", "worker", "slot_role"]},
                    "target_name": {"type": "string", "description": "名称(global 时可省略)"},
                    "action": {"type": "string", "enum": ["pause", "resume", "status"]}
                }
            }),
        ),

    ]
}
