(work-order-plan
  :schema "missiond.work-order.plan.v1"
  :id "20260522-v3-ssot-projection"
  :intent "20260522-v3-ssot-projection"
  :status accepted
  :accepted_shards
    ((shard default
       :accepted_shard_id "20260522-v3-ssot-projection-shard-default"
       :read_scope ["."]
       :write_scope [".gitignore"
                     ".missiond/v3/missiond-blueprint.lisp"
                     ".missiond/v3/shards/**"
                     ".missiond/workflows/nightly-evolution.lisp"
                     ".missiond/work-orders/20260522-v3-ssot-projection/**"
                     "CLAUDE.md"
                     "README.md"
                     "crates/missiond-core/src/ws/server.rs"
                     "crates/missiond-daemon/src/context/v3_blueprint_runtime.rs"
                     "crates/missiond-daemon/src/engine/nightly_evolution.rs"
                     "crates/missiond-mcp/src/tools/compute/process.rs"
                     "crates/missiond-pty/src/manager.rs"
                     "scripts/analyze-v3-self-evolution.mjs"
                     "scripts/check-*.mjs"
                     "scripts/deploy-daemon.sh"
                     "scripts/check-typed-lisp-compiler.mjs"
                     "scripts/check-v3-code-isomorphism-complete.mjs"
                     "scripts/check-v3-final-convergence.mjs"
                     "scripts/check-v3-pillar-flow-schema.mjs"
                     "scripts/check-v3-request-lisp-isomorphism.mjs"
                     "scripts/check-v3-v2-coverage.mjs"
                     "scripts/compile-v3-runtime.mjs"
                     "scripts/lib/v3_blueprint_contract_source.mjs"
                     "scripts/lib/v3_compiled_contract.mjs"
                     "scripts/lib/v3_workstation_runtime.mjs"
                     "tools/missiond_lispc/**"]
       :acceptance ["scripts/rustfmt-missiond.sh --check"
                    "dune test --root tools/missiond_lispc"
                    "node scripts/compile-v3-runtime.mjs --json"
                    "node scripts/check-v3-code-isomorphism-complete.mjs --json"
                    "node scripts/analyze-v3-self-evolution.mjs --json"
                    "node scripts/check-v3-final-convergence.mjs --json --static-only"
                    "cargo test -p missiond-daemon v3_blueprint_runtime"
                    "cargo test --workspace"
                    "git diff --check"])))
