// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-pure-utility.lisp (pure-utility string-helpers)
// Pattern: pure-utility (algorithm isolation chamber)
//
// Implement the trait in custom.rs — only pure functions allowed.

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in custom.rs
// ═══════════════════════════════════════════════════════════

pub trait StringHelpers {
    /// Truncate string to at most max_bytes, never breaking a char boundary.
    /// Returns a valid UTF-8 slice.
    fn safe_byte_truncate(s: &str, max_bytes: usize) -> &str;

    /// Truncate string to at most max_chars Unicode characters.
    fn safe_char_truncate(s: &str, max_chars: usize) -> &str;
}
