(work-order-plan
  :schema "missiond.work-order.plan.v1"
  :id "wo-20260605-board-codex-codebase-build"
  :intent "wo-20260605-board-codex-codebase-build"
  :status draft
  :accepted_shards
    ((shard default
       :accepted_shard_id "wo-20260605-board-codex-codebase-build-shard-default"
       :read_scope [".missiond/v3/missiond-blueprint.lisp"
                    ".missiond/v3/shards/index.lisp"
                    ".missiond/v3/shards/universe/project-registry.lisp"
                    ".missiond/v3/shards/universe/service-runtime.lisp"
                    ".missiond/frontend/board-blueprint.lisp"
                    "packages/board"
                    "crates/missiond-core/src/db/pg/conversation.rs"
                    "crates/missiond-daemon/src/workers/local/codex_ingestion_worker.rs"]
       :write_scope [".gitignore"
                     ".missiond/frontend/board-blueprint.lisp"
                     ".missiond/v3/shards/universe/project-registry.lisp"
                     ".missiond/v3/shards/universe/service-runtime.lisp"
                     "crates/missiond-core/src/db/pg/conversation.rs"
                     "crates/missiond-core/src/v3_contracts.rs"
                     "crates/missiond-daemon/src/context/v3_contracts/generated.rs"
                     "crates/missiond-daemon/src/context/v3_runtime_defaults/generated.rs"
                     "crates/missiond-daemon/src/handlers/comm/codex_ops.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/project/deployment_channels.rs"
                     "crates/missiond-daemon/src/workers/local/codex_ingestion_worker.rs"
                     "crates/missiond-mcp/src/tools/comm/codex_ops.rs"
                     "packages/board/**"
                     "scripts/generated/**"
                     "scripts/serial_baud_probe.py"
                     "scripts/serial_uboot_break.py"]
       :acceptance ["git diff --check"
                    "node scripts/project-v3-contracts.mjs --check --json"
                    "node scripts/compile-v3-runtime.mjs --check --json"
                    "node scripts/check-v3-project-registry-isomorphism.mjs --json"
                    "node scripts/check-project-ssot-universe.mjs --json"
                    "node scripts/check-frontend-board-runtime-projection.mjs"
                    "node scripts/check-frontend-board-code-isomorphism.mjs --json"
                    "node scripts/check-frontend-board-lisp-schema.mjs --json"
                    "cargo check -p missiond-core -p missiond-daemon -p missiond-mcp"
                    "cargo test -p missiond-daemon codex_ingestion_worker"
                    "cargo fmt --all -- --check"
                    "pnpm --dir packages/board typecheck"
                    "pnpm --dir packages/board build"
                    "python3 -m py_compile scripts/serial_baud_probe.py scripts/serial_uboot_break.py"])))
