(work-order-plan
  :schema "missiond.work-order.plan.v1"
  :id "wo-20260526031825-Finalize-runtime-health-checker-"
  :intent "wo-20260526031825-Finalize-runtime-health-checker-"
  :status draft
  :accepted_shards
    ((shard default
       :accepted_shard_id "wo-20260526031825-Finalize-runtime-health-checker--shard-default"
       :read_scope ["."]
       :write_scope [
         ".github/workflows/quality-gates.yml"
         ".missiond/v3/missiond-blueprint.lisp"
         "Cargo.toml"
         "Cargo.lock"
         "crates/missiond-core/src/event"
         "crates/missiond-core/tests/event_chaos.rs"
         "crates/missiond-core/tests/event_dispatcher_integration.rs"
         "crates/missiond-core/tests/event_subscription_integration.rs"
         "crates/missiond-core/src/db/pg/board.rs"
         "crates/missiond-core/migrations"
         "crates/missiond-daemon/src/app_ports.rs"
         "crates/missiond-daemon/src/bus/bootstrap.rs"
         "crates/missiond-daemon/src/context/v3_contracts/generated.rs"
         "crates/missiond-daemon/src/context/v3_runtime_defaults/generated.rs"
         "crates/missiond-daemon/src/engine/intent_engine/mod.rs"
         "crates/missiond-daemon/src/engine/intent_engine/autopilot_workflow.rs"
         "crates/missiond-daemon/src/engine/shared_memory.rs"
         "crates/missiond-daemon/src/handlers/compute/slot.rs"
         "crates/missiond-daemon/src/handlers/compute/worker.rs"
         "crates/missiond-daemon/src/handlers/knowledge/board.rs"
         "crates/missiond-daemon/src/handlers/mod.rs"
         "crates/missiond-daemon/src/handlers/sysinfra/misc.rs"
         "crates/missiond-daemon/src/main.rs"
         "crates/missiond-daemon/src/runtime_actors.rs"
         "crates/missiond-daemon/src/state.rs"
         "crates/missiond-daemon/src/startup_preflight.rs"
         "crates/missiond-daemon/src/workers"
         "crates/missiond-domain"
         "crates/missiond-mcp/src/lib.rs"
         "crates/missiond-mcp/src/tools/mod.rs"
         "packages/board/src/components/OperationsOverview.tsx"
         "packages/board/src/lib/operatorOverview.ts"
         "packages/board/src/lib/missiondBoardClient.ts"
         "packages/board/src/app/api/tasks/route.ts"
         "packages/board/src/app/api/operator/runbook/action/route.ts"
         "scripts/check-board-operator-fixtures.mjs"
         "scripts/check-high-roi-contracts.mjs"
         "scripts/check-v3-architecture-boundaries.mjs"
         "scripts/check-v3-code-isomorphism-complete.mjs"
         "scripts/check-v3-shared-memory-isomorphism.mjs"
         "scripts/generated"
         "AGENTS.md"
       ]
       :acceptance [
         "cargo check -p missiond-core -p missiond-daemon -p missiond-mcp -p skill-store"
         "node scripts/check-v3-shared-memory-isomorphism.mjs --json"
         "node scripts/check-high-roi-contracts.mjs --json"
         "node scripts/check-v3-architecture-boundaries.mjs --json"
         "node scripts/check-board-operator-fixtures.mjs"
         "node scripts/project-v3-contracts.mjs --check --json"
         "node scripts/check-v3-runtime-domain-projections.mjs --json"
         "pnpm --dir packages/board build"
         "git diff --check"
       ])))
