//! Architecture Maintenance Worker — auto-updates YAML manifests when structural code changes land.
//!
//! Subscribes to `GitCommitDetected` events from the EventBus, filters for structural changes
//! (new modules, trait changes, Cargo.toml edits, etc.), and calls Sonnet to update the
//! corresponding `docs/architectures/*.yaml` manifest.
//!
//! Design doc: `docs/designs/arch-maintenance-and-strategic-analysis.md`

use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::{Duration, Instant};

use anyhow::{anyhow, Result};
use serde_json::json;
use tracing::{debug, info, warn};

use crate::event_bus::{DaemonEvent, TimelineEvent};
use crate::gemini_client::REQUEST_CALLER;
use crate::embedding_worker::resolve_llm_credentials;
use crate::state::AppState;

use super::{BackgroundWorker, WorkerContext};

/// Author used for commits generated by this worker (for self-trigger filtering).
const ARCH_COMMIT_AUTHOR: &str = "missiond-arch-worker <noreply@missiond>";
/// Commit message prefix for self-trigger filtering.
const ARCH_COMMIT_PREFIX: &str = "chore(arch):";
/// Maximum diff size sent to LLM (bytes). Truncated beyond this.
const MAX_DIFF_SIZE: usize = 4_000_000;
/// Debounce window — ignore commits for the same repo within this period.
const DEBOUNCE_SECS: u64 = 30;

pub(crate) struct ArchMaintenanceWorker {
    pub timeline_rx: tokio::sync::broadcast::Receiver<TimelineEvent>,
}

impl BackgroundWorker for ArchMaintenanceWorker {
    fn name(&self) -> &'static str { "arch_maintenance" }

    async fn run(self, state: Arc<AppState>, mut ctx: WorkerContext) {
        let mut rx = self.timeline_rx;
        let mut debounce: HashMap<String, Instant> = HashMap::new();
        let mut processing: HashSet<String> = HashSet::new();

        info!("Architecture maintenance worker started");

        loop {
            ctx.wait_if_paused().await;
            match rx.recv().await {
                Ok(te) => {
                    if let DaemonEvent::GitCommitDetected {
                        ref repo,
                        ref hash,
                        ref author,
                        ref message,
                        ..
                    } = te.event
                    {
                        // Self-trigger filter: skip commits made by this worker
                        if author == "missiond-arch-worker"
                            || message.starts_with(ARCH_COMMIT_PREFIX)
                        {
                            debug!(repo = %repo, "arch_maintenance: skipping own commit");
                            continue;
                        }

                        // Debounce: skip if same repo was processed recently
                        let now = Instant::now();
                        if let Some(last) = debounce.get(repo) {
                            if now.duration_since(*last) < Duration::from_secs(DEBOUNCE_SECS) {
                                debug!(repo = %repo, "arch_maintenance: debounced");
                                continue;
                            }
                        }

                        // Concurrency guard: skip if already processing this repo
                        if processing.contains(repo) {
                            debug!(repo = %repo, "arch_maintenance: already processing");
                            continue;
                        }

                        debounce.insert(repo.clone(), now);
                        processing.insert(repo.clone());

                        match process_commit(&state, repo, hash).await {
                            Ok(true) => {
                                info!(repo = %repo, "arch_maintenance: YAML updated");
                                ctx.record_success();
                            }
                            Ok(false) => {
                                debug!(repo = %repo, "arch_maintenance: NO_CHANGE");
                            }
                            Err(e) => {
                                warn!(error = %e, repo = %repo, "arch_maintenance: failed");
                                ctx.record_failure();
                            }
                        }

                        processing.remove(repo);
                    }
                }
                Err(tokio::sync::broadcast::error::RecvError::Lagged(n)) => {
                    warn!(skipped = n, "arch_maintenance lagged");
                }
                Err(_) => break,
            }
        }
    }
}

/// Map repo name → YAML manifest path (relative to missiond project root).
fn yaml_for_repo(repo_name: &str) -> Option<&'static str> {
    match repo_name {
        "missiond" => Some("docs/architectures/missiond.yaml"),
        "cuthub" | "cuthub-frontend" => Some("docs/architectures/cuthub.yaml"),
        "xiaojinpro-backend" => Some("docs/architectures/xjp-backend.yaml"),
        _ => None,
    }
}

/// Resolve the repo root path from the repo name.
/// Uses slot configs to find the actual cwd, then `git rev-parse --show-toplevel`.
fn resolve_repo_path(state: &AppState, repo_name: &str) -> Option<PathBuf> {
    for slot in state.mission.list_slots() {
        if let Some(ref cwd) = slot.config.cwd {
            let path = Path::new(cwd);
            if !path.exists() {
                continue;
            }
            // Check if this cwd's git root matches the repo name
            let output = std::process::Command::new("git")
                .args(["rev-parse", "--show-toplevel"])
                .current_dir(path)
                .output()
                .ok()?;
            if output.status.success() {
                let root = String::from_utf8_lossy(&output.stdout).trim().to_string();
                let root_path = PathBuf::from(&root);
                let name = root_path
                    .file_name()
                    .map(|n| n.to_string_lossy().to_string())
                    .unwrap_or_default();
                if name == repo_name {
                    return Some(root_path);
                }
            }
        }
    }
    None
}

/// Check if the changed files include structural modifications.
fn has_structural_changes(files: &[(String, String)]) -> bool {
    files.iter().any(|(status, path)| {
        // New or deleted files are always structural
        status == "A" || status == "D"
            // Rust module structure
            || path.ends_with("mod.rs")
            || path.ends_with("lib.rs")
            || path.ends_with("Cargo.toml")
            || path.ends_with("main.rs")
            || path.contains("types/")
            || path.contains("traits/")
            || path.contains("interfaces/")
            // Frontend structure
            || (path.contains("app/") && path.ends_with("page.tsx"))
            || (path.contains("hooks/") && path.contains("use"))
            || path.ends_with("middleware.ts")
    })
}

/// Get the list of changed files between HEAD~1 and HEAD for a specific commit.
fn git_diff_files(repo_path: &Path, hash: &str) -> Result<Vec<(String, String)>> {
    let output = std::process::Command::new("git")
        .args(["diff-tree", "--no-commit-id", "-r", "--name-status", hash])
        .current_dir(repo_path)
        .output()
        .map_err(|e| anyhow!("git diff-tree failed: {}", e))?;

    if !output.status.success() {
        return Err(anyhow!(
            "git diff-tree failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    let text = String::from_utf8_lossy(&output.stdout);
    Ok(text
        .lines()
        .filter_map(|line| {
            let mut parts = line.splitn(2, '\t');
            let status = parts.next()?.to_string();
            let path = parts.next()?.to_string();
            Some((status, path))
        })
        .collect())
}

/// Get the diff content for a commit.
fn git_diff_content(repo_path: &Path, hash: &str) -> Result<String> {
    let output = std::process::Command::new("git")
        .args(["diff-tree", "-p", "--no-commit-id", hash])
        .current_dir(repo_path)
        .output()
        .map_err(|e| anyhow!("git diff failed: {}", e))?;

    if !output.status.success() {
        return Err(anyhow!(
            "git diff failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}

/// Strip markdown code block wrapper from LLM output.
fn strip_markdown_code_block(s: &str) -> String {
    let trimmed = s.trim();
    // Check for ```yaml ... ``` or ```YAML ... ``` etc.
    if let Some(rest) = trimmed.strip_prefix("```") {
        // Skip the language tag line
        if let Some(content_start) = rest.find('\n') {
            let inner = &rest[content_start + 1..];
            if let Some(end) = inner.rfind("```") {
                return inner[..end].trim_end().to_string();
            }
        }
    }
    s.to_string()
}

/// Commit the updated YAML with a specific author to enable self-trigger filtering.
fn commit_yaml_update(repo_path: &Path, yaml_path: &str, commit_msg: &str) -> Result<()> {
    // Stage the file
    let add_output = std::process::Command::new("git")
        .args(["add", yaml_path])
        .current_dir(repo_path)
        .output()
        .map_err(|e| anyhow!("git add failed: {}", e))?;

    if !add_output.status.success() {
        return Err(anyhow!(
            "git add failed: {}",
            String::from_utf8_lossy(&add_output.stderr)
        ));
    }

    // Check if there are actual changes staged
    let diff_output = std::process::Command::new("git")
        .args(["diff", "--cached", "--quiet"])
        .current_dir(repo_path)
        .output()
        .map_err(|e| anyhow!("git diff --cached failed: {}", e))?;

    if diff_output.status.success() {
        // No changes staged (file identical), skip commit
        debug!("arch_maintenance: no actual changes to commit");
        return Ok(());
    }

    let full_msg = format!("{} {}", ARCH_COMMIT_PREFIX, commit_msg);
    let commit_output = std::process::Command::new("git")
        .args([
            "commit",
            "-m",
            &full_msg,
            "--author",
            ARCH_COMMIT_AUTHOR,
        ])
        .current_dir(repo_path)
        .output()
        .map_err(|e| anyhow!("git commit failed: {}", e))?;

    if !commit_output.status.success() {
        return Err(anyhow!(
            "git commit failed: {}",
            String::from_utf8_lossy(&commit_output.stderr)
        ));
    }

    info!(
        path = yaml_path,
        msg = %full_msg,
        "arch_maintenance: committed YAML update"
    );
    Ok(())
}

/// Main processing logic for a single commit.
async fn process_commit(state: &AppState, repo: &str, hash: &str) -> Result<bool> {
    // 1. Check if we have a YAML manifest for this repo
    let yaml_rel = match yaml_for_repo(repo) {
        Some(p) => p,
        None => return Ok(false), // No manifest for this repo
    };

    // 2. Resolve repo path
    let repo_path = resolve_repo_path(state, repo)
        .ok_or_else(|| anyhow!("Cannot resolve repo path for '{}'", repo))?;

    // 3. Get changed files and check for structural changes
    let files = tokio::task::spawn_blocking({
        let rp = repo_path.clone();
        let h = hash.to_string();
        move || git_diff_files(&rp, &h)
    })
    .await
    .map_err(|e| anyhow!("spawn_blocking failed: {}", e))??;

    if !has_structural_changes(&files) {
        debug!(repo = %repo, "arch_maintenance: no structural changes");
        return Ok(false);
    }

    info!(
        repo = %repo,
        hash = %&hash[..7.min(hash.len())],
        changed_files = files.len(),
        "arch_maintenance: structural change detected, calling LLM"
    );

    // 4. Read current YAML manifest
    // For missiond repo, the YAML is in the same repo
    // For other repos, it's still in the missiond repo
    let missiond_root = PathBuf::from("/Users/jinchen/Projects/missiond");
    let yaml_path = missiond_root.join(yaml_rel);
    let yaml_content = tokio::fs::read_to_string(&yaml_path)
        .await
        .map_err(|e| anyhow!("Failed to read {}: {}", yaml_path.display(), e))?;

    // 5. Get diff content
    let diff_output = tokio::task::spawn_blocking({
        let rp = repo_path.clone();
        let h = hash.to_string();
        move || git_diff_content(&rp, &h)
    })
    .await
    .map_err(|e| anyhow!("spawn_blocking failed: {}", e))??;

    // Truncate extreme diffs
    let diff_output = if diff_output.len() > MAX_DIFF_SIZE {
        format!(
            "{}...\n[截断: diff 原始 {} 字节，仅保留前 {}]",
            &diff_output[..MAX_DIFF_SIZE],
            diff_output.len(),
            MAX_DIFF_SIZE
        )
    } else {
        diff_output
    };

    // 6. Call LLM (stateless oneshot)
    let prompt = format!(
        r#"你是架构维护专家。对比当前架构 YAML 与最新代码变更。

## 当前架构 YAML
{yaml_content}

## 代码变更（git diff）
{diff_output}

## 规则
- 如果变更仅为实现细节（bug fix、文案、函数体内修改），输出 `NO_CHANGE`
- 如果变更触及了模块拓扑、接口契约、数据流、新增实体，输出更新后的完整 YAML
- 如果新增了设计决策，追加到 design_rationale 区
- 保持现有格式和注释风格
- 输出纯 YAML，不要用 ```yaml 包裹"#
    );

    let (base_url, jwt) = resolve_llm_credentials().await?;
    let model = "claude-sonnet-4-6";
    let url = format!("{}/v1/chat/completions", base_url);
    let body = json!({
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 16384,
    });

    let result = REQUEST_CALLER
        .scope("arch_maintenance".to_string(), async {
            state
                .gemini
                .send(&state.http_client, &url, &jwt, &body)
                .await
        })
        .await?;

    let content = result
        .pointer("/choices/0/message/content")
        .and_then(|v| v.as_str())
        .unwrap_or("(empty response)")
        .to_string();

    // 7. Parse response
    let content = strip_markdown_code_block(&content);

    if content.trim() == "NO_CHANGE" || content.trim() == "`NO_CHANGE`" {
        debug!(repo = %repo, "arch_maintenance: LLM says NO_CHANGE");
        return Ok(false);
    }

    // Basic YAML validation: must contain "project:" (all our manifests start with this)
    if !content.contains("project:") {
        warn!(
            repo = %repo,
            response_len = content.len(),
            "arch_maintenance: LLM response doesn't look like valid YAML, skipping"
        );
        return Ok(false);
    }

    // 8. Write updated YAML
    tokio::fs::write(&yaml_path, &content)
        .await
        .map_err(|e| anyhow!("Failed to write {}: {}", yaml_path.display(), e))?;

    // 9. Commit (in missiond repo, since that's where the YAML lives)
    let commit_msg = format!("update {} manifest (triggered by {})", repo, &hash[..7.min(hash.len())]);
    tokio::task::spawn_blocking({
        let root = missiond_root.clone();
        let yaml = yaml_rel.to_string();
        move || commit_yaml_update(&root, &yaml, &commit_msg)
    })
    .await
    .map_err(|e| anyhow!("spawn_blocking failed: {}", e))??;

    Ok(true)
}
