// GENERATED BY scripts/project-v3-contracts.mjs --write
// Source: .missiond/v3/missiond-blueprint.lisp
// Output: crates/missiond-daemon/src/context/v3_runtime_defaults/generated.rs
// Do not edit by hand.

pub const SCHEMA_VERSION: &str = "missiond.compiled-runtime-config.v1";
pub const SOURCE_HASH: &str = "1582402aff3e6feaeeae5680349b4078";
pub const DEFAULT_RUNTIME_CONFIG_JSON: &str = r#"{
  "blueprint": ".missiond/v3/missiond-blueprint.lisp",
  "source_units": [
    {
      "file": ".missiond/v3/missiond-blueprint.lisp",
      "kind": "missiond-blueprint",
      "included_by": null,
      "include_line": null,
      "source_hash": "d9b5e465ceda433ff27bbaba86902f03"
    },
    {
      "file": ".missiond/v3/shards/index.lisp",
      "kind": "missiond-blueprint-shards",
      "included_by": ".missiond/v3/missiond-blueprint.lisp",
      "include_line": 403,
      "source_hash": "4787b2a01e6c1a6a10606866d3b937de"
    },
    {
      "file": ".missiond/v3/shards/request-runtime.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 7,
      "source_hash": "fef564ab89b01b3856e07afb13327449"
    },
    {
      "file": ".missiond/v3/shards/workstation-runtime.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 14,
      "source_hash": "c37507b3e7c546e078626fd5d4cc8079"
    },
    {
      "file": ".missiond/v3/shards/control-plane-runtime.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 21,
      "source_hash": "09b81d3db03d8642ff6377a54c2a3c02"
    },
    {
      "file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 28,
      "source_hash": "88182347818297dbb20d11859fd848a7"
    },
    {
      "file": ".missiond/v3/shards/agent-navigation.lisp",
      "kind": "agent-entry-index",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 35,
      "source_hash": "6d79ae7a37df9b4fc8f8aaff017dd8ce"
    },
    {
      "file": ".missiond/v3/shards/ops-infra.lisp",
      "kind": "ops-infra",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 42,
      "source_hash": "9ff7b6db5517ad7621332a6a599fb19f"
    },
    {
      "file": ".missiond/v3/shards/v2-convergence-map.lisp",
      "kind": "v2-convergence-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 49,
      "source_hash": "3c62fd9f8d884097afc12c5c00373b0f"
    },
    {
      "file": ".missiond/v3/shards/pillar-flow-map.lisp",
      "kind": "pillar-flow-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 56,
      "source_hash": "eacd5fa2c880e6731c32fbf5e555df14"
    },
    {
      "file": ".missiond/v3/shards/universe/service-runtime.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 63,
      "source_hash": "3fc545bd3c29052f1b183ff5168f9804"
    },
    {
      "file": ".missiond/v3/shards/universe/service-layer-template.lisp",
      "kind": "service-layer-template",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 70,
      "source_hash": "827d8a056e6f55d97569bed0a4098951"
    },
    {
      "file": ".missiond/v3/shards/universe/infrastructure.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 77,
      "source_hash": "7942dd415073a3c1412464369ca2ffc5"
    },
    {
      "file": ".missiond/v3/shards/universe/data-residency.lisp",
      "kind": "data-residency-universe",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 84,
      "source_hash": "23834fd90b8b46a01f5dcfdc57044012"
    },
    {
      "file": ".missiond/v3/shards/universe/project-maturity.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 91,
      "source_hash": "957afdc1606c38cdffd788d23fda82b8"
    },
    {
      "file": ".missiond/v3/shards/universe/project-registry.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 98,
      "source_hash": "e86bc10c35dff17a87162ad2e1f58a77"
    },
    {
      "file": ".missiond/v3/shards/universe/behavior-closure.lisp",
      "kind": "behavior-universe",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 105,
      "source_hash": "7786aa330847cb4ccba418134872426c"
    },
    {
      "file": ".missiond/v3/shards/implementation/request-surfaces.lisp",
      "kind": "implementation-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 112,
      "source_hash": "9e98cfa6b82bd5b9d1f5a8f3ae7f3d29"
    },
    {
      "file": ".missiond/v3/shards/implementation/execution-surfaces.lisp",
      "kind": "implementation-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 119,
      "source_hash": "3596d94b1fe9ced988cf0c578532bcf2"
    },
    {
      "file": ".missiond/v3/shards/implementation/runtime-surfaces.lisp",
      "kind": "implementation-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 126,
      "source_hash": "ab1f158387164359c74ac5c03aa4f4a2"
    },
    {
      "file": ".missiond/v3/shards/implementation/knowledge-surfaces.lisp",
      "kind": "implementation-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 133,
      "source_hash": "2c69009375c64086dd5f67722f294f67"
    },
    {
      "file": ".missiond/v3/shards/implementation/ops-surfaces.lisp",
      "kind": "implementation-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 140,
      "source_hash": "2c2dc6417d4f7f742d440ee0bf527a1b"
    }
  ],
  "source_domains": [
    {
      "id": "blueprint-core",
      "source_hash": "4c0a904911ec5ccb8c04c126056c79b1",
      "source_units": [
        {
          "file": ".missiond/v3/missiond-blueprint.lisp",
          "kind": "missiond-blueprint",
          "included_by": null,
          "include_line": null,
          "source_hash": "d9b5e465ceda433ff27bbaba86902f03"
        },
        {
          "file": ".missiond/v3/shards/index.lisp",
          "kind": "missiond-blueprint-shards",
          "included_by": ".missiond/v3/missiond-blueprint.lisp",
          "include_line": 403,
          "source_hash": "4787b2a01e6c1a6a10606866d3b937de"
        }
      ]
    },
    {
      "id": "control-plane-runtime",
      "source_hash": "4f7b47e8c8e39973bb3d5feca1ab781a",
      "source_units": [
        {
          "file": ".missiond/v3/shards/request-runtime.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 7,
          "source_hash": "fef564ab89b01b3856e07afb13327449"
        },
        {
          "file": ".missiond/v3/shards/control-plane-runtime.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 21,
          "source_hash": "09b81d3db03d8642ff6377a54c2a3c02"
        }
      ]
    },
    {
      "id": "workstation-runtime",
      "source_hash": "ffe908ea722d4cc945877b4bf4ff3f6a",
      "source_units": [
        {
          "file": ".missiond/v3/shards/workstation-runtime.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 14,
          "source_hash": "c37507b3e7c546e078626fd5d4cc8079"
        }
      ]
    },
    {
      "id": "memory-knowledge-runtime",
      "source_hash": "d4a1d4e9b38fd83cac2f287160483147",
      "source_units": [
        {
          "file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 28,
          "source_hash": "88182347818297dbb20d11859fd848a7"
        }
      ]
    },
    {
      "id": "agent-navigation",
      "source_hash": "ba7a66d07782af2af017f407529c8d26",
      "source_units": [
        {
          "file": ".missiond/v3/shards/agent-navigation.lisp",
          "kind": "agent-entry-index",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 35,
          "source_hash": "6d79ae7a37df9b4fc8f8aaff017dd8ce"
        }
      ]
    },
    {
      "id": "ops-infra",
      "source_hash": "1d3a6a7896fcae9ecd5f11529369326a",
      "source_units": [
        {
          "file": ".missiond/v3/shards/ops-infra.lisp",
          "kind": "ops-infra",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 42,
          "source_hash": "9ff7b6db5517ad7621332a6a599fb19f"
        }
      ]
    },
    {
      "id": "v2-convergence",
      "source_hash": "70f6c18ae0b889cde87ef48936b90de6",
      "source_units": [
        {
          "file": ".missiond/v3/shards/v2-convergence-map.lisp",
          "kind": "v2-convergence-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 49,
          "source_hash": "3c62fd9f8d884097afc12c5c00373b0f"
        }
      ]
    },
    {
      "id": "pillar-flow",
      "source_hash": "fa7b27ab7f4edb9e5b1a60324130c8d7",
      "source_units": [
        {
          "file": ".missiond/v3/shards/pillar-flow-map.lisp",
          "kind": "pillar-flow-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 56,
          "source_hash": "eacd5fa2c880e6731c32fbf5e555df14"
        }
      ]
    },
    {
      "id": "universe",
      "source_hash": "374c907f3f7b9a4d58f36fa374fb73b6",
      "source_units": [
        {
          "file": ".missiond/v3/shards/universe/service-runtime.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 63,
          "source_hash": "3fc545bd3c29052f1b183ff5168f9804"
        },
        {
          "file": ".missiond/v3/shards/universe/service-layer-template.lisp",
          "kind": "service-layer-template",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 70,
          "source_hash": "827d8a056e6f55d97569bed0a4098951"
        },
        {
          "file": ".missiond/v3/shards/universe/infrastructure.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 77,
          "source_hash": "7942dd415073a3c1412464369ca2ffc5"
        },
        {
          "file": ".missiond/v3/shards/universe/data-residency.lisp",
          "kind": "data-residency-universe",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 84,
          "source_hash": "23834fd90b8b46a01f5dcfdc57044012"
        },
        {
          "file": ".missiond/v3/shards/universe/project-maturity.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 91,
          "source_hash": "957afdc1606c38cdffd788d23fda82b8"
        },
        {
          "file": ".missiond/v3/shards/universe/project-registry.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 98,
          "source_hash": "e86bc10c35dff17a87162ad2e1f58a77"
        },
        {
          "file": ".missiond/v3/shards/universe/behavior-closure.lisp",
          "kind": "behavior-universe",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 105,
          "source_hash": "7786aa330847cb4ccba418134872426c"
        }
      ]
    },
    {
      "id": "implementation-map",
      "source_hash": "356fd6624066e161018c585cd3079e34",
      "source_units": [
        {
          "file": ".missiond/v3/shards/implementation/request-surfaces.lisp",
          "kind": "implementation-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 112,
          "source_hash": "9e98cfa6b82bd5b9d1f5a8f3ae7f3d29"
        },
        {
          "file": ".missiond/v3/shards/implementation/execution-surfaces.lisp",
          "kind": "implementation-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 119,
          "source_hash": "3596d94b1fe9ced988cf0c578532bcf2"
        },
        {
          "file": ".missiond/v3/shards/implementation/runtime-surfaces.lisp",
          "kind": "implementation-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 126,
          "source_hash": "ab1f158387164359c74ac5c03aa4f4a2"
        },
        {
          "file": ".missiond/v3/shards/implementation/knowledge-surfaces.lisp",
          "kind": "implementation-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 133,
          "source_hash": "2c69009375c64086dd5f67722f294f67"
        },
        {
          "file": ".missiond/v3/shards/implementation/ops-surfaces.lisp",
          "kind": "implementation-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 140,
          "source_hash": "2c2dc6417d4f7f742d440ee0bf527a1b"
        }
      ]
    }
  ],
  "runtime_policies": [
    {
      "id": "autopilot-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "autopilot-policy",
      "payload_key": "autopilot",
      "keyword_keys": [
        ":desc",
        ":stale-conversation-minutes",
        ":slot-task-reap-stale-secs",
        ":recover-stale-running-minutes",
        ":slot-failure-throttle-secs",
        ":deploy-review-timeout-secs",
        ":dynamic-slot-expiring-soon-secs",
        ":stale-board-progress-minutes",
        ":completed-job-gc-minutes",
        ":idle-persistent-slot-secs",
        ":recent-intents-window-secs",
        ":user-stuck-cooldown-secs",
        ":direction-shift-cooldown-secs",
        ":invariants",
        ":checker"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 323,
        "source_column": 3,
        "source_hash": "1582402aff3e6feaeeae5680349b4078"
      }
    },
    {
      "id": "cascade-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "cascade-policy",
      "payload_key": "cascade",
      "keyword_keys": [
        ":desc",
        ":default-manifest",
        ":allowed-root",
        ":trigger-enabled",
        ":default-max-cycles",
        ":max-cycles-limit",
        ":env-overrides",
        ":invariants"
      ],
      "nested_forms": [
        "UNIVERSE_MANIFEST"
      ],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 344,
        "source_column": 3,
        "source_hash": "1582402aff3e6feaeeae5680349b4078"
      }
    },
    {
      "id": "flow-runtime-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "flow-runtime-policy",
      "payload_key": "flow",
      "keyword_keys": [
        ":desc",
        ":llm-call-default-max-tokens",
        ":slot-task-default-model",
        ":slot-task-default-timeout-secs",
        ":parallel-slot-default-parallelism",
        ":parallel-slot-default-timeout-secs",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 357,
        "source_column": 3,
        "source_hash": "1582402aff3e6feaeeae5680349b4078"
      }
    },
    {
      "id": "compute-runtime-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "compute-runtime-policy",
      "payload_key": "compute",
      "keyword_keys": [
        ":desc",
        ":invariants"
      ],
      "nested_forms": [
        "timeout-policy"
      ],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 369,
        "source_column": 3,
        "source_hash": "1582402aff3e6feaeeae5680349b4078"
      }
    },
    {
      "id": "minimax-runtime-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "minimax-runtime-policy",
      "payload_key": "minimax",
      "keyword_keys": [
        ":desc",
        ":model",
        ":direct-http-timeout-secs",
        ":quota-throttle-secs",
        ":default-max-tokens",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 379,
        "source_column": 3,
        "source_hash": "1582402aff3e6feaeeae5680349b4078"
      }
    },
    {
      "id": "router-runtime-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "router-runtime-policy",
      "payload_key": "router",
      "keyword_keys": [
        ":desc",
        ":default-chat-model",
        ":chat-default-max-tokens",
        ":file-chat-default-max-tokens",
        ":flow-gemini-model",
        ":stateless-sonnet-model",
        ":queued-sonnet-model",
        ":anthropic-urgent-model",
        ":anthropic-ops-model",
        ":anthropic-docs-test-chore-model",
        ":compress-model",
        ":compress-channel",
        ":compress-max-tokens",
        ":compress-char-budget-chars",
        ":direct-http-timeout-secs",
        ":router-chat-idle-timeout-secs",
        ":router-chat-retry-max-attempts",
        ":router-chat-retry-initial-backoff-ms",
        ":router-chat-retry-max-backoff-ms",
        ":gemini-pty-queue-timeout-secs",
        ":gemini-http-queue-timeout-secs",
        ":gemini-file-upload-timeout-secs",
        ":gemini-file-poll-timeout-secs",
        ":gemini-cli-absolute-timeout-secs",
        ":gemini-cli-tool-exec-timeout-secs",
        ":queued-sonnet-quota-throttle-secs",
        ":queued-sonnet-default-max-tokens",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 390,
        "source_column": 3,
        "source_hash": "1582402aff3e6feaeeae5680349b4078"
      }
    },
    {
      "id": "project-registry-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "project-registry-policy",
      "payload_key": "projectRegistry",
      "keyword_keys": [
        ":desc",
        ":intent-path-candidates",
        ":default-universe-manifest",
        ":env-overrides",
        ":invariants"
      ],
      "nested_forms": [
        "UNIVERSE_MANIFEST"
      ],
      "source": {
        "source_file": ".missiond/v3/shards/universe/project-registry.lisp",
        "source_line": 1,
        "source_column": 1,
        "source_hash": "1582402aff3e6feaeeae5680349b4078"
      }
    },
    {
      "id": "capability-governance-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "capability-governance-policy",
      "payload_key": "capabilityGovernance",
      "keyword_keys": [
        ":desc",
        ":review-sidecar",
        ":protected-tool-patterns",
        ":protected-flow-patterns",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
        "source_line": 1,
        "source_column": 3,
        "source_hash": "1582402aff3e6feaeeae5680349b4078"
      }
    },
    {
      "id": "memory-kb-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "memory-kb-policy",
      "payload_key": "memoryKb",
      "keyword_keys": [
        ":desc",
        ":pending-message-limit",
        ":tool-result-preview-chars",
        ":assistant-preview-chars",
        ":active-memory-target-ratio",
        ":sensitive-query-suppression",
        ":review-states",
        ":default-query-policy",
        ":invariants"
      ],
      "nested_forms": [
        "architecture:module",
        "active"
      ],
      "source": {
        "source_file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
        "source_line": 264,
        "source_column": 3,
        "source_hash": "1582402aff3e6feaeeae5680349b4078"
      }
    },
    {
      "id": "conversation-ingestion-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "conversation-ingestion-policy",
      "payload_key": "conversationIngestion",
      "keyword_keys": [
        ":desc",
        ":conversation-get-tail-default",
        ":conversation-search-default-limit",
        ":message-search-default-limit",
        ":analysis-context-max-turns",
        ":label-calibration-sample-limit",
        ":jarvis-stream-envelope-schema",
        ":context-before-default",
        ":context-after-default",
        ":conversation-events-default-limit",
        ":agent-trajectory-default-limit",
        ":timeline-query-default-limit",
        ":timeline-query-max-limit",
        ":timeline-search-default-limit",
        ":timeline-search-max-limit",
        ":intent-router-model",
        ":intent-router-timeout-ms",
        ":vision-codex-binary",
        ":vision-codex-model",
        ":vision-codex-idle-timeout-secs",
        ":vision-codex-absolute-timeout-secs",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
        "source_line": 331,
        "source_column": 3,
        "source_hash": "1582402aff3e6feaeeae5680349b4078"
      }
    },
    {
      "id": "learning-engine-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "learning-engine-policy",
      "payload_key": "learningEngine",
      "keyword_keys": [
        ":desc",
        ":realtime-extraction-timeout-secs",
        ":realtime-empty-backoff-base-secs",
        ":realtime-empty-backoff-max-secs",
        ":deep-analysis-zero-output-fuse-threshold",
        ":deep-analysis-zero-output-fuse-secs",
        ":decision-tier3-timeout-secs",
        ":habit-scan-timeout-secs",
        ":token-spend-guard-window-secs",
        ":token-spend-guard-soft-limit",
        ":timeline-analysis-interval-secs",
        ":timeline-analysis-window-hours",
        ":timeline-error-limit",
        ":timeline-llm-sample-limit",
        ":timeline-slow-event-limit",
        ":timeline-slow-threshold-ms",
        ":idle-explore-interval-secs",
        ":habit-scan-interval-secs",
        ":habit-scan-batch-size",
        ":kb-auto-gc-interval-secs",
        ":kb-consolidation-interval-secs",
        ":kb-reflection-interval-secs",
        ":kb-reflection-utility-threshold",
        ":kb-reflection-min-access",
        ":kb-reflection-max-entries",
        ":kb-reflection-max-tokens",
        ":decision-harvest-interval-secs",
        ":cooccurrence-refresh-interval-secs",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
        "source_line": 287,
        "source_column": 3,
        "source_hash": "1582402aff3e6feaeeae5680349b4078"
      }
    }
  ],
  "workstation": {
    "slot_default_profiles": {
      "coder": "coding-default-opus-4-7",
      "researcher": "research-default",
      "ops": "daily-sonnet"
    },
    "slot_templates": {
      "coder": {
        "name": "coder",
        "role": "coder",
        "description": "Dynamic coder slot (ephemeral)",
        "default_model_profile": "coding-default-opus-4-7",
        "mcp_config": "$MISSION_HOME/xjp-mcp-config.json",
        "default_cwd": "$MISSIOND_PROJECTS_DIR"
      },
      "researcher": {
        "name": "researcher",
        "role": "coder",
        "description": "Dynamic researcher slot (read-only analysis)",
        "default_model_profile": "research-default",
        "mcp_config": "$MISSION_HOME/xjp-mcp-config.json",
        "default_cwd": "$MISSIOND_PROJECTS_DIR"
      },
      "ops": {
        "name": "ops",
        "role": "operator",
        "description": "Dynamic ops slot (ephemeral)",
        "default_model_profile": "daily-sonnet",
        "mcp_config": "$MISSION_HOME/xjp-mcp-config.json",
        "default_cwd": "$MISSIOND_PROJECTS_DIR"
      }
    },
    "model_profile_spawn_args": {
      "coding-default-opus-4-7": null,
      "research-default": null,
      "gemini-ultra-pro-preview": "gemini-3.1-pro-preview",
      "codex-master-gpt-5-5-xhigh": "gpt-5.5",
      "codex-gpt-5-5-default": "gpt-5.5",
      "daily-sonnet": "sonnet",
      "quick-haiku": "haiku"
    },
    "startup_slots": [
      {
        "task_type": "arch_maintenance",
        "engine": "claude-code",
        "lifecycle": "persistent",
        "slot_id": "slot-arch-maint",
        "role": "arch-maint",
        "model_profile": "coding-default-opus-4-7",
        "timeout_secs": 600,
        "skip_permissions": false
      },
      {
        "task_type": "strategy_analyst",
        "engine": "gemini",
        "lifecycle": "persistent",
        "slot_id": "slot-gemini-strategy",
        "role": "strategy",
        "model_profile": null,
        "timeout_secs": 600,
        "skip_permissions": false
      },
      {
        "task_type": "gemini_router",
        "engine": "gemini",
        "lifecycle": "persistent",
        "slot_id": "slot-gemini-router",
        "role": "gemini-router",
        "model_profile": null,
        "timeout_secs": 120,
        "skip_permissions": false
      },
      {
        "task_type": "lisp_survey",
        "engine": "claude-code",
        "lifecycle": "persistent",
        "slot_id": "lisp-surveyor",
        "role": "coder",
        "model_profile": "coding-default-opus-4-7",
        "timeout_secs": 900,
        "skip_permissions": false
      }
    ],
    "workstation_pool": [
      {
        "id": "claude-code-default",
        "engine": "claude-code",
        "role": "coder",
        "slot_id": "slot-claude-code-default",
        "task_type": "claude_code_default",
        "model_profile": "coding-default-opus-4-7",
        "model": null,
        "task_classes": [
          "code",
          "implementation",
          "review",
          "context-pack",
          "ops"
        ],
        "capabilities": [
          "code-read",
          "code-write",
          "scoped-commit",
          "mcp"
        ],
        "max_concurrency": 1,
        "timeout_secs": 1800,
        "default_use": "code-implementation",
        "accepts_boardtask": true,
        "write_allowed": true,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": null,
        "tool_policy_path": null
      },
      {
        "id": "claude-code-deploy-ops",
        "engine": "claude-code",
        "role": "deploy-ops",
        "slot_id": "slot-claude-code-deploy-ops",
        "task_type": "claude_code_deploy_ops",
        "model_profile": "coding-default-opus-4-7",
        "model": null,
        "task_classes": [
          "deploy-ops",
          "deployment",
          "ops",
          "incident-response"
        ],
        "capabilities": [
          "deploy-read",
          "deploy-observe",
          "deploy-center-query",
          "rollback-plan",
          "mcp"
        ],
        "max_concurrency": 1,
        "timeout_secs": 2400,
        "default_use": "deployment-operations",
        "accepts_boardtask": true,
        "write_allowed": false,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": null,
        "tool_policy_path": null
      },
      {
        "id": "claude-code-fast-patch",
        "engine": "claude-code",
        "role": "patcher",
        "slot_id": "slot-claude-code-fast-patch",
        "task_type": "claude_code_fast_patch",
        "model_profile": "daily-sonnet",
        "model": null,
        "task_classes": [
          "patch",
          "test",
          "chore",
          "low-risk-fast-path"
        ],
        "capabilities": [
          "code-read",
          "code-write",
          "scoped-commit",
          "narrow-patch",
          "mcp"
        ],
        "max_concurrency": 1,
        "timeout_secs": 900,
        "default_use": "narrow-patch",
        "accepts_boardtask": true,
        "write_allowed": true,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": null,
        "tool_policy_path": null
      },
      {
        "id": "gemini-ultra-pro",
        "engine": "gemini",
        "role": "researcher",
        "slot_id": "slot-gemini-ultra",
        "task_type": "gemini_ultra",
        "model_profile": "gemini-ultra-pro-preview",
        "model": null,
        "task_classes": [
          "research",
          "review",
          "context-pack",
          "lisp-compression",
          "general"
        ],
        "capabilities": [
          "read-only",
          "analysis",
          "design-review"
        ],
        "max_concurrency": 1,
        "timeout_secs": 900,
        "default_use": "research-review",
        "accepts_boardtask": true,
        "write_allowed": false,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": "plan",
        "tool_policy_path": ".missiond/v3/policies/gemini-readonly-policy.toml"
      },
      {
        "id": "gemini-fast-survey",
        "engine": "gemini",
        "role": "survey",
        "slot_id": "slot-gemini-fast-survey",
        "task_type": "gemini_fast_survey",
        "model_profile": null,
        "model": "gemini-2.5-flash",
        "task_classes": [
          "survey",
          "summary",
          "mechanical-scan"
        ],
        "capabilities": [
          "read-only",
          "summary"
        ],
        "max_concurrency": 1,
        "timeout_secs": 600,
        "default_use": "low-authority-survey",
        "accepts_boardtask": true,
        "write_allowed": false,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": "plan",
        "tool_policy_path": ".missiond/v3/policies/gemini-readonly-policy.toml"
      },
      {
        "id": "agy-research",
        "engine": "agy",
        "role": "researcher",
        "slot_id": "slot-agy-research",
        "task_type": "agy_research",
        "model_profile": null,
        "model": null,
        "task_classes": [
          "research",
          "review",
          "context-pack",
          "survey"
        ],
        "capabilities": [
          "read-only",
          "analysis",
          "design-review",
          "provider-successor"
        ],
        "max_concurrency": 1,
        "timeout_secs": 900,
        "default_use": "agy-read-only-research",
        "accepts_boardtask": true,
        "write_allowed": false,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": null,
        "tool_policy_path": null
      },
      {
        "id": "codex-code-worker",
        "engine": "codex",
        "role": "coder",
        "slot_id": "slot-codex-code-worker",
        "task_type": "codex_code_worker",
        "model_profile": "codex-master-gpt-5-5-xhigh",
        "model": null,
        "task_classes": [
          "code",
          "implementation",
          "design",
          "review",
          "regression-analysis"
        ],
        "capabilities": [
          "code-read",
          "code-write",
          "scoped-commit",
          "shell-exec",
          "search"
        ],
        "max_concurrency": 1,
        "timeout_secs": 1800,
        "default_use": "codex-code-shard",
        "accepts_boardtask": true,
        "write_allowed": true,
        "reasoning_effort": "xhigh",
        "search_enabled": true,
        "sandbox": "workspace-write",
        "approval_policy": "never",
        "tool_policy_path": null
      },
      {
        "id": "codex-review-worker",
        "engine": "codex",
        "role": "reviewer",
        "slot_id": "slot-codex-review-worker",
        "task_type": "codex_review_worker",
        "model_profile": "codex-master-gpt-5-5-xhigh",
        "model": null,
        "task_classes": [
          "review",
          "architecture-review",
          "regression-analysis"
        ],
        "capabilities": [
          "code-read",
          "design-review",
          "search"
        ],
        "max_concurrency": 1,
        "timeout_secs": 1200,
        "default_use": "codex-review-shard",
        "accepts_boardtask": true,
        "write_allowed": false,
        "reasoning_effort": "xhigh",
        "search_enabled": true,
        "sandbox": "read-only",
        "approval_policy": "never",
        "tool_policy_path": null
      },
      {
        "id": "codex-intent-author",
        "engine": "codex",
        "role": "intent-author",
        "slot_id": "slot-codex-intent-author",
        "task_type": "codex_intent_author",
        "model_profile": "codex-master-gpt-5-5-xhigh",
        "model": null,
        "task_classes": [
          "intent-authoring",
          "intent-recognition"
        ],
        "capabilities": [
          "intent-recognition",
          "code-read",
          "search"
        ],
        "max_concurrency": 1,
        "timeout_secs": 180,
        "default_use": "jarvis-intent-authoring",
        "accepts_boardtask": false,
        "write_allowed": false,
        "reasoning_effort": "xhigh",
        "search_enabled": true,
        "sandbox": "read-only",
        "approval_policy": "never",
        "tool_policy_path": null
      },
      {
        "id": "codex-plan-author",
        "engine": "codex",
        "role": "plan-author",
        "slot_id": "slot-codex-plan-author",
        "task_type": "codex_plan_author",
        "model_profile": "codex-master-gpt-5-5-xhigh",
        "model": null,
        "task_classes": [
          "plan-authoring",
          "plan-generation"
        ],
        "capabilities": [
          "plan-generation",
          "code-read",
          "search"
        ],
        "max_concurrency": 1,
        "timeout_secs": 180,
        "default_use": "jarvis-plan-authoring",
        "accepts_boardtask": false,
        "write_allowed": false,
        "reasoning_effort": "xhigh",
        "search_enabled": true,
        "sandbox": "read-only",
        "approval_policy": "never",
        "tool_policy_path": null
      },
      {
        "id": "codex-master-control",
        "engine": "codex",
        "role": "orchestrator",
        "slot_id": "slot-codex-master-control",
        "task_type": "codex_master_control",
        "model_profile": "codex-master-gpt-5-5-xhigh",
        "model": null,
        "task_classes": [
          "master-control",
          "orchestration",
          "governance",
          "night-audit"
        ],
        "capabilities": [
          "board-write",
          "kb-write",
          "execution-log",
          "dispatch",
          "code-read",
          "code-write",
          "shell-exec",
          "search",
          "mcp",
          "full-access"
        ],
        "max_concurrency": 1,
        "timeout_secs": 7200,
        "default_use": "resident-master-control",
        "accepts_boardtask": false,
        "write_allowed": true,
        "reasoning_effort": "xhigh",
        "search_enabled": true,
        "sandbox": "danger-full-access",
        "approval_policy": "never",
        "tool_policy_path": null
      }
    ],
    "allowed_cwd_prefixes": [
      "$MISSIOND_PROJECTS_DIR",
      "$MISSIOND_DOWNLOADS_DIR",
      "$MISSIOND_DOCUMENTS_DIR",
      "/tmp"
    ],
    "chat_completions_default_slot": "slot-claude-code-default",
    "timeout_policy": {
      "default_secs": 1800,
      "min_secs": 60,
      "max_secs": 7200,
      "watchdog_grace_secs": 120,
      "missing_session_probe_secs": 120
    },
    "cc_swarm_timeout_policy": {
      "default_secs": 600,
      "min_secs": 60,
      "max_secs": 7200
    },
    "pty_send_timeout_policy": {
      "default_secs": 300,
      "min_secs": 1,
      "max_secs": 7200
    },
    "dynamic_slot_spawn_timeout_policy": {
      "default_secs": 60,
      "min_secs": 10,
      "max_secs": 600
    },
    "context_pack_dispatch_policy": {
      "default_max_parallel": 4,
      "min_parallel": 1,
      "max_parallel": 8
    },
    "swarm_capacity_policy": {
      "default_claude_workers": 8,
      "max_claude_workers": 16,
      "default_gemini_workers": 2,
      "max_gemini_workers": 6,
      "dynamic_slot_limit": 20,
      "delegate_rate_per_minute": 24
    },
    "slot_ttl_policy": {
      "default_secs": 14400,
      "min_secs": 300,
      "max_secs": 28800,
      "default_extend_secs": 3600,
      "max_extend_secs": 3600
    }
  },
  "flow": {
    "llm_call_default_max_tokens": 65536,
    "slot_task_default_model": "opus",
    "slot_task_default_timeout_secs": 3600,
    "parallel_slot_default_parallelism": 3,
    "parallel_slot_default_timeout_secs": 1800
  },
  "compute": {
    "pty_spawn_timeout_policy": {
      "default_secs": 30,
      "min_secs": 1,
      "max_secs": 600
    }
  },
  "minimax": {
    "model": "MiniMax-M2.5-highspeed",
    "direct_http_timeout_secs": 30,
    "quota_throttle_secs": 60,
    "default_max_tokens": 500
  },
  "router": {
    "default_chat_model": "gemini-3.1-pro",
    "chat_default_max_tokens": 16384,
    "file_chat_default_max_tokens": 65536,
    "flow_gemini_model": "gemini-3.1-pro",
    "stateless_sonnet_model": "claude-sonnet",
    "queued_sonnet_model": "claude-sonnet",
    "anthropic_urgent_model": "claude-opus-4-6",
    "anthropic_ops_model": "claude-sonnet-4.5",
    "anthropic_docs_test_chore_model": "claude-haiku-4-5-20251001",
    "compress_model": "gemini-3.1-pro",
    "compress_channel": "google",
    "compress_max_tokens": 2048,
    "compress_char_budget_chars": 100000,
    "direct_http_timeout_secs": 60,
    "router_chat_idle_timeout_secs": 600,
    "router_chat_retry_max_attempts": 3,
    "router_chat_retry_initial_backoff_ms": 250,
    "router_chat_retry_max_backoff_ms": 2000,
    "gemini_pty_queue_timeout_secs": 30,
    "gemini_http_queue_timeout_secs": 300,
    "gemini_file_upload_timeout_secs": 600,
    "gemini_file_poll_timeout_secs": 300,
    "gemini_cli_absolute_timeout_secs": 900,
    "gemini_cli_tool_exec_timeout_secs": 300,
    "queued_sonnet_quota_throttle_secs": 30,
    "queued_sonnet_default_max_tokens": 1024
  },
  "cascade": {
    "default_manifest_path": "$MISSIOND_PROJECTS_DIR/universe.intent.lisp",
    "allowed_root": "$MISSIOND_PROJECTS_DIR",
    "trigger_enabled": true,
    "default_max_cycles": 3,
    "max_cycles_limit": 12
  },
  "projectRegistry": {
    "intent_path_candidates": [
      ".missiond/intent.lisp",
      ".jarvis/intent.lisp",
      "intent.lisp"
    ],
    "default_universe_manifest": "$MISSIOND_PROJECTS_DIR/universe.intent.lisp"
  },
  "capabilityGovernance": {
    "review_sidecar_path": ".missiond/v3/runtime/capability-usage-review.json",
    "protected_tool_patterns": [
      "mission_execution",
      "mission_intent",
      "mission_forge_",
      "mission_sys_",
      "mission_daemon_update",
      "mission_health",
      "mission_power_control",
      "mission_kb_ops",
      "mission_audit",
      "mission_pty_signal",
      "mission_pty_key",
      "mission_pty_text",
      "mission_pty_confirm",
      "mission_incident"
    ],
    "protected_flow_patterns": [
      "engineering",
      "F-execution-log-governance",
      "F-incident-reaction",
      "F-capability-usage-monitoring"
    ]
  },
  "memoryKb": {
    "pending_message_limit": 60,
    "tool_result_preview_chars": 1000,
    "assistant_preview_chars": 500
  },
  "evidenceLanePolicy": {
    "lanes": [
      {
        "lane_id": "runtime_truth",
        "authority_class": "runtime_truth",
        "source_types": [
          "runtime_environment",
          "deploy_release_manifest",
          "deploy_center_provenance",
          "health_smoke",
          "runtime_status"
        ],
        "default_profiles": [
          "intent_default",
          "deploy_ops",
          "conversation_audit",
          "full_debug"
        ],
        "raw_policy": "compact_only",
        "privacy_class": "operational",
        "validity": [
          "current_rule"
        ],
        "freshness": "hot_runtime",
        "injectable_by_default": true,
        "promotion_rules": [
          "already-authoritative",
          "no-kb-promotion"
        ]
      },
      {
        "lane_id": "project_ssot",
        "authority_class": "file_first_lisp_and_compiled_project_universe",
        "source_types": [
          "project_resolution",
          "project_registry",
          "ssot",
          "compiled_project_universe",
          "service_runtime_universe"
        ],
        "default_profiles": [
          "intent_default",
          "deploy_ops",
          "conversation_audit",
          "full_debug"
        ],
        "raw_policy": "compact_only",
        "privacy_class": "internal",
        "validity": [
          "current_rule",
          "project_specific"
        ],
        "freshness": "compiled_runtime_bound",
        "injectable_by_default": true,
        "promotion_rules": [
          "already-authoritative",
          "no-conversation-override"
        ]
      },
      {
        "lane_id": "reviewed_kb",
        "authority_class": "knowledge_review_state",
        "source_types": [
          "knowledge",
          "knowledge_review_state",
          "promoted_decision",
          "incident_pattern",
          "active_fact"
        ],
        "default_profiles": [
          "intent_default",
          "deploy_ops",
          "conversation_audit",
          "full_debug"
        ],
        "raw_policy": "compact_only",
        "privacy_class": "internal",
        "validity": [
          "active_fact",
          "decision",
          "incident_pattern"
        ],
        "freshness": "ttl_or_version_bound",
        "injectable_by_default": true,
        "promotion_rules": [
          "review-required",
          "ttl-required-for-deploy-config-dependency"
        ]
      },
      {
        "lane_id": "active_board",
        "authority_class": "board_projection",
        "source_types": [
          "board_task",
          "workflow_run",
          "incident",
          "deploy_work_order",
          "task_result_projection"
        ],
        "default_profiles": [
          "intent_default",
          "deploy_ops",
          "conversation_audit",
          "full_debug"
        ],
        "raw_policy": "compact_only",
        "privacy_class": "internal",
        "validity": [
          "current_state",
          "active_work_order"
        ],
        "freshness": "active_task_bound",
        "injectable_by_default": true,
        "promotion_rules": [
          "artifact-before-kb"
        ]
      },
      {
        "lane_id": "skill_evidence",
        "authority_class": "evidence_only",
        "source_types": [
          "skill_metadata",
          "skill_procedure",
          "skill_operational_fact",
          "skill_warning",
          "skill_credential_ref",
          "infra_evidence"
        ],
        "default_profiles": [
          "deploy_ops",
          "full_debug"
        ],
        "raw_policy": "compact_only",
        "privacy_class": "internal",
        "validity": [
          "current_rule",
          "historical_pattern",
          "deprecated",
          "project_specific",
          "evidence_only"
        ],
        "freshness": "version_bound_or_historical",
        "injectable_by_default": false,
        "promotion_rules": [
          "needs_review-before-kb",
          "operational-fact-samples-high-confidence-only"
        ]
      },
      {
        "lane_id": "conversation_audit",
        "authority_class": "provider_durable_conversation_read_model",
        "source_types": [
          "conversation_episode",
          "conversation_fact_extract",
          "conversation_duplicate_group",
          "conversation_message_raw"
        ],
        "default_profiles": [
          "conversation_audit",
          "full_debug"
        ],
        "raw_policy": "raw_opt_in_only",
        "privacy_class": "audit",
        "validity": [
          "derived_from_conversation",
          "historical_pattern",
          "needs_review"
        ],
        "freshness": "time_range_bound",
        "injectable_by_default": false,
        "promotion_rules": [
          "episode-first",
          "raw-message-audit-only",
          "fact-extract-needs-review"
        ]
      },
      {
        "lane_id": "cold_archive",
        "authority_class": "forensics_only_cold_archive",
        "source_types": [
          "archived_session",
          "true_user_utterance",
          "transcript_dump",
          "research_dump",
          "raw_provider_log",
          "old_compiled_projection"
        ],
        "default_profiles": [
          "full_debug"
        ],
        "raw_policy": "explicit_path_or_full_debug_only",
        "privacy_class": "audit",
        "validity": [
          "historical_evidence",
          "stale",
          "duplicate",
          "superseded"
        ],
        "freshness": "cold_archive",
        "injectable_by_default": false,
        "promotion_rules": [
          "never-default",
          "no-auto-promotion"
        ]
      },
      {
        "lane_id": "support_refs",
        "authority_class": "redacted_support_catalog",
        "source_types": [
          "support_catalog",
          "deploy_center_service",
          "github_workflow",
          "service_manifest",
          "db_migration_namespace",
          "health_endpoint",
          "smoke_endpoint",
          "agent_ref",
          "secret_ref"
        ],
        "default_profiles": [
          "intent_default",
          "deploy_ops",
          "conversation_audit",
          "full_debug"
        ],
        "raw_policy": "secret_refs_only",
        "privacy_class": "reference",
        "validity": [
          "current_reference",
          "project_specific"
        ],
        "freshness": "runtime_or_catalog_bound",
        "injectable_by_default": true,
        "promotion_rules": [
          "secret-values-never-indexed",
          "provenance-required"
        ]
      }
    ],
    "profiles": [
      {
        "profile": "intent_default",
        "allowed_lanes": [
          "runtime_truth",
          "project_ssot",
          "reviewed_kb",
          "active_board",
          "support_refs"
        ],
        "raw_sources": false,
        "credential_values": false
      },
      {
        "profile": "deploy_ops",
        "allowed_lanes": [
          "runtime_truth",
          "project_ssot",
          "reviewed_kb",
          "active_board",
          "support_refs",
          "skill_evidence"
        ],
        "raw_sources": false,
        "credential_values": false
      },
      {
        "profile": "conversation_audit",
        "allowed_lanes": [
          "runtime_truth",
          "project_ssot",
          "reviewed_kb",
          "active_board",
          "support_refs",
          "conversation_audit"
        ],
        "raw_sources": false,
        "credential_values": false
      },
      {
        "profile": "full_debug",
        "allowed_lanes": [
          "runtime_truth",
          "project_ssot",
          "reviewed_kb",
          "active_board",
          "support_refs",
          "skill_evidence",
          "conversation_audit",
          "cold_archive"
        ],
        "raw_sources": true,
        "credential_values": false
      }
    ]
  },
  "conversationIngestion": {
    "conversation_get_tail_default": 50,
    "conversation_search_default_limit": 10,
    "message_search_default_limit": 20,
    "context_before_default": 3,
    "context_after_default": 5,
    "conversation_events_default_limit": 100,
    "agent_trajectory_default_limit": 200,
    "timeline_query_default_limit": 50,
    "timeline_query_max_limit": 200,
    "timeline_search_default_limit": 20,
    "timeline_search_max_limit": 100,
    "intent_router_model": "claude-opus-4.6",
    "intent_router_timeout_ms": 10000,
    "vision_codex_binary": "codex",
    "vision_codex_model": "gpt-5.4",
    "vision_codex_idle_timeout_secs": 120,
    "vision_codex_absolute_timeout_secs": 300
  },
  "autopilot": {
    "boardtask_timeout_policy": {
      "default_secs": 1800,
      "min_secs": 60,
      "max_secs": 7200,
      "watchdog_grace_secs": 120,
      "missing_session_probe_secs": 120
    },
    "stale_conversation_minutes": 10,
    "slot_task_reap_stale_secs": 1800,
    "recover_stale_running_minutes": 15,
    "slot_failure_throttle_secs": 1800,
    "deploy_review_timeout_secs": 600,
    "dynamic_slot_expiring_soon_secs": 900,
    "stale_board_progress_minutes": 30,
    "completed_job_gc_minutes": 30,
    "idle_persistent_slot_secs": 1800,
    "recent_intents_window_secs": 1800,
    "user_stuck_cooldown_secs": 1800,
    "direction_shift_cooldown_secs": 3600
  },
  "controlPlaneKernel": {
    "schema": "missiond.control-plane-kernel.v1",
    "authority": "postgres-typed-runtime-facts",
    "facts": [
      "task_contracts",
      "task_result_artifacts",
      "event_log",
      "jobs",
      "job_attempts",
      "work_leases",
      "capability_grants",
      "capability_audit_events",
      "review_gates",
      "board_task_views"
    ],
    "runtime_abi_fields": [
      "completion_artifact_schema",
      "job_state_machine",
      "capability_policy",
      "sandbox_policy",
      "projection_policy"
    ],
    "hard_cutover": true,
    "rules": [
      "BoardTask description, Board notes, PTY screens, TUI summaries, and provider prose are projection/observation inputs only.",
      "Runtime control paths MUST read task_contracts, subject-bound capability_grants, work_leases, jobs/job_attempts, event_log, and task_result_artifacts; BoardTask.runtime_metadata is a UI/cache projection only.",
      "Kernel-internal completion writes MUST call typed task_result_put entrypoints directly; mission_shared_memory JSON action dispatch is an external adapter and MUST NOT be the kernel's reverse dependency.",
      "Missing task_contracts on a control-plane task returns TASK_CONTRACT_REQUIRED; MissionD must not parse Markdown descriptions or BoardTask.runtime_metadata to recover canonical control fields.",
      "task_result_put and worker_settle MUST pass exact grant_id + subject_kind + subject_id + operation + scope + task_id capability checks; write-scoped completed artifacts also require current attempt_id plus verification and changed-path evidence.",
      "A successful worker_settle(done) using an exact settle capability grant MUST atomically mark that grant consumed before terminal Board/job projection; bypass grants remain audit-only and cannot be replayed as exact tokens.",
      "Public mission_shared_memory capability_grant MUST itself pass delegate authority: exact authority_grant_id for operation=delegate, or confirmed system/operator/daemon bypass with capability_audit_events. It MUST NOT mint grants from target subject fields alone.",
      "Write-scoped completion verification MUST bind to the current job_attempt: attempt.started records a pre worktree manifest, settle-time verification records a post manifest, compares git status plus git diff --name-only between pre/post HEAD, subtracts pre-existing dirty paths, and fails closed when the current attempt or pre manifest is missing.",
      "Worker spawn MUST carry an exact subject-bound worker/conversation spawn grant and project sandbox_profile from task_contracts/capability facts; unsupported engine/scope combinations return SANDBOX_POLICY_UNSUPPORTED or CAPABILITY_DENIED.",
      "mission_compute_slot(create) for task-bound dynamic workers MUST start a kernel attempt.started event after PTY spawn succeeds and before the worker is advertised idle, so jobs.current_attempt_id and the pre worktree manifest exist before task dispatch or artifact writes.",
      "BoardTask claim, release, heartbeat, expiry, and recovery MUST use work_leases as the lease authority; BoardTask claim fields and shared_claims are compatibility projections/mirrors only.",
      "ProjectionEngine updates board_task_views and Board-facing status from typed events/state, not from note text or PTY/provider final prose.",
      "Non-core full-os tools MUST keep their public MCP names but default to FEATURE_DISABLED unless MISSIOND_FULL_OS_ENABLE or the matching MISSIOND_FEATURE_* gate is explicitly enabled.",
      "Startup services for self-evolution, Lisp code sync, workflow recovery, memory embeddings, and multi-provider diagnostics MUST NOT start in kernel-core mode."
    ],
    "state_machine": [],
    "db_migration": "crates/missiond-core/migrations/20260527000000_control_plane_kernel.sql",
    "checker": "scripts/check-v3-control-plane-kernel-isomorphism.mjs",
    "completion_artifact_schema": {
      "schema": "missiond.task-result-artifact.v1",
      "storage": "task_result_artifacts",
      "required_artifact_hash_for_done": true
    },
    "job_state_machine": {
      "events": [],
      "terminal_states": [
        "completed",
        "blocked",
        "failed",
        "skipped"
      ]
    },
    "capability_policy": {
      "artifact_write": "write:task",
      "settle_done": "settle:task",
      "claim": "claim:*"
    },
    "sandbox_policy": {
      "default": "fail-closed",
      "codex_write": "workspace-write",
      "read_only": "read-only"
    },
    "projection_policy": {
      "board_task": "projection",
      "notes": "projection",
      "pty_provider_text": "observation"
    }
  },
  "learningEngine": {
    "realtime_extraction_timeout_secs": 300,
    "realtime_empty_backoff_base_secs": 30,
    "realtime_empty_backoff_max_secs": 900,
    "deep_analysis_zero_output_fuse_threshold": 3,
    "deep_analysis_zero_output_fuse_secs": 3600,
    "decision_tier3_timeout_secs": 300,
    "habit_scan_timeout_secs": 600,
    "token_spend_guard_window_secs": 3600,
    "token_spend_guard_soft_limit": 250000,
    "timeline_analysis_interval_secs": 43200,
    "timeline_analysis_window_hours": 12,
    "timeline_error_limit": 20,
    "timeline_llm_sample_limit": 50,
    "timeline_slow_event_limit": 20,
    "timeline_slow_threshold_ms": 60000,
    "idle_explore_interval_secs": 7200,
    "habit_scan_interval_secs": 14400,
    "habit_scan_batch_size": 5,
    "kb_auto_gc_interval_secs": 3600,
    "kb_consolidation_interval_secs": 86400,
    "kb_reflection_interval_secs": 604800,
    "kb_reflection_utility_threshold": 0.3,
    "kb_reflection_min_access": 3,
    "kb_reflection_max_entries": 20,
    "kb_reflection_max_tokens": 2000,
    "decision_harvest_interval_secs": 86400,
    "cooccurrence_refresh_interval_secs": 21600
  }
}
"#;
