// GENERATED BY scripts/project-v3-contracts.mjs --write
// Source: .missiond/v3/missiond-blueprint.lisp
// Output: crates/missiond-daemon/src/context/v3_runtime_defaults/generated.rs
// Do not edit by hand.

pub const SCHEMA_VERSION: &str = "missiond.compiled-runtime-config.v1";
pub const SOURCE_HASH: &str = "94844577f61f66fd3b016d4ccf74180a";
pub const DEFAULT_RUNTIME_CONFIG_JSON: &str = r#"{
  "blueprint": ".missiond/v3/missiond-blueprint.lisp",
  "source_units": [
    {
      "file": ".missiond/v3/missiond-blueprint.lisp",
      "kind": "missiond-blueprint",
      "included_by": null,
      "include_line": null,
      "source_hash": "b9fe1413d0c677187a8d784ffe23d828"
    },
    {
      "file": ".missiond/v3/shards/index.lisp",
      "kind": "missiond-blueprint-shards",
      "included_by": ".missiond/v3/missiond-blueprint.lisp",
      "include_line": 357,
      "source_hash": "8882108e8391f000fe8717dc67c1c03f"
    },
    {
      "file": ".missiond/v3/shards/request-runtime.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 7,
      "source_hash": "946482c24022e23c2f5e7acac7202ae7"
    },
    {
      "file": ".missiond/v3/shards/workstation-runtime.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 14,
      "source_hash": "d0daf5bab4539ec0b243ccc91839a00e"
    },
    {
      "file": ".missiond/v3/shards/control-plane-runtime.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 21,
      "source_hash": "c1231d91115f19666ac99f0a03dad1fa"
    },
    {
      "file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 28,
      "source_hash": "04a6cb03a76e8ee9f527a906b3dff044"
    },
    {
      "file": ".missiond/v3/shards/agent-navigation.lisp",
      "kind": "agent-entry-index",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 35,
      "source_hash": "6d79ae7a37df9b4fc8f8aaff017dd8ce"
    },
    {
      "file": ".missiond/v3/shards/ops-infra.lisp",
      "kind": "ops-infra",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 42,
      "source_hash": "1d22cd3453cd5e339abd345862496288"
    },
    {
      "file": ".missiond/v3/shards/v2-convergence-map.lisp",
      "kind": "v2-convergence-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 49,
      "source_hash": "f05400d2ab861b36fe9689114d24b95f"
    },
    {
      "file": ".missiond/v3/shards/pillar-flow-map.lisp",
      "kind": "pillar-flow-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 56,
      "source_hash": "62cae5ea5ae20f13b9a0d3aef901dbbc"
    },
    {
      "file": ".missiond/v3/shards/universe/service-runtime.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 63,
      "source_hash": "c1219f14bc6f768655b8c54c52dba815"
    },
    {
      "file": ".missiond/v3/shards/universe/infrastructure.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 70,
      "source_hash": "6b2e914f03d12bcde8af5a271e1e0abc"
    },
    {
      "file": ".missiond/v3/shards/universe/data-residency.lisp",
      "kind": "data-residency-universe",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 77,
      "source_hash": "23834fd90b8b46a01f5dcfdc57044012"
    },
    {
      "file": ".missiond/v3/shards/universe/project-maturity.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 84,
      "source_hash": "41156cb2ff4412a1135ec2c0fd0507b7"
    },
    {
      "file": ".missiond/v3/shards/universe/project-registry.lisp",
      "kind": "multi-section-shard",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 91,
      "source_hash": "8c565d4f104ac8e28ecf4c8122e42c98"
    },
    {
      "file": ".missiond/v3/shards/universe/behavior-closure.lisp",
      "kind": "behavior-universe",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 98,
      "source_hash": "fe930f3e44a811ba2104fbdc36fa34d2"
    },
    {
      "file": ".missiond/v3/shards/implementation/request-surfaces.lisp",
      "kind": "implementation-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 105,
      "source_hash": "992de6e0edd89c23cd7a58dcdfb0e6d2"
    },
    {
      "file": ".missiond/v3/shards/implementation/execution-surfaces.lisp",
      "kind": "implementation-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 112,
      "source_hash": "8f4b7eed977a390cd9889812b3eec044"
    },
    {
      "file": ".missiond/v3/shards/implementation/runtime-surfaces.lisp",
      "kind": "implementation-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 119,
      "source_hash": "830ab127c6ba5096faa73225847a688e"
    },
    {
      "file": ".missiond/v3/shards/implementation/knowledge-surfaces.lisp",
      "kind": "implementation-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 126,
      "source_hash": "eb7215a0e0f5bb9ecfb607991d762b44"
    },
    {
      "file": ".missiond/v3/shards/implementation/ops-surfaces.lisp",
      "kind": "implementation-map",
      "included_by": ".missiond/v3/shards/index.lisp",
      "include_line": 133,
      "source_hash": "a4415ad5a6fb275479d1ec33d39fb237"
    }
  ],
  "source_domains": [
    {
      "id": "blueprint-core",
      "source_hash": "a096defaa8229a68698783e5f2d507ae",
      "source_units": [
        {
          "file": ".missiond/v3/missiond-blueprint.lisp",
          "kind": "missiond-blueprint",
          "included_by": null,
          "include_line": null,
          "source_hash": "b9fe1413d0c677187a8d784ffe23d828"
        },
        {
          "file": ".missiond/v3/shards/index.lisp",
          "kind": "missiond-blueprint-shards",
          "included_by": ".missiond/v3/missiond-blueprint.lisp",
          "include_line": 357,
          "source_hash": "8882108e8391f000fe8717dc67c1c03f"
        }
      ]
    },
    {
      "id": "control-plane-runtime",
      "source_hash": "780270cd3c04b5b9c179186122a54020",
      "source_units": [
        {
          "file": ".missiond/v3/shards/request-runtime.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 7,
          "source_hash": "946482c24022e23c2f5e7acac7202ae7"
        },
        {
          "file": ".missiond/v3/shards/control-plane-runtime.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 21,
          "source_hash": "c1231d91115f19666ac99f0a03dad1fa"
        }
      ]
    },
    {
      "id": "workstation-runtime",
      "source_hash": "ce781f9dd15246add597950b6745f82b",
      "source_units": [
        {
          "file": ".missiond/v3/shards/workstation-runtime.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 14,
          "source_hash": "d0daf5bab4539ec0b243ccc91839a00e"
        }
      ]
    },
    {
      "id": "memory-knowledge-runtime",
      "source_hash": "68da92743c976df7d842d974ed3840c8",
      "source_units": [
        {
          "file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 28,
          "source_hash": "04a6cb03a76e8ee9f527a906b3dff044"
        }
      ]
    },
    {
      "id": "agent-navigation",
      "source_hash": "ba7a66d07782af2af017f407529c8d26",
      "source_units": [
        {
          "file": ".missiond/v3/shards/agent-navigation.lisp",
          "kind": "agent-entry-index",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 35,
          "source_hash": "6d79ae7a37df9b4fc8f8aaff017dd8ce"
        }
      ]
    },
    {
      "id": "ops-infra",
      "source_hash": "cd4dc2c56fd98852d9d4d8f555b55888",
      "source_units": [
        {
          "file": ".missiond/v3/shards/ops-infra.lisp",
          "kind": "ops-infra",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 42,
          "source_hash": "1d22cd3453cd5e339abd345862496288"
        }
      ]
    },
    {
      "id": "v2-convergence",
      "source_hash": "b44046d6cf71135acb57c02faf44d629",
      "source_units": [
        {
          "file": ".missiond/v3/shards/v2-convergence-map.lisp",
          "kind": "v2-convergence-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 49,
          "source_hash": "f05400d2ab861b36fe9689114d24b95f"
        }
      ]
    },
    {
      "id": "pillar-flow",
      "source_hash": "caf3501d5ee2bbd762f9e8393ffc0d5f",
      "source_units": [
        {
          "file": ".missiond/v3/shards/pillar-flow-map.lisp",
          "kind": "pillar-flow-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 56,
          "source_hash": "62cae5ea5ae20f13b9a0d3aef901dbbc"
        }
      ]
    },
    {
      "id": "universe",
      "source_hash": "98311eadcff020a1fe511bf1b3fcdde6",
      "source_units": [
        {
          "file": ".missiond/v3/shards/universe/service-runtime.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 63,
          "source_hash": "c1219f14bc6f768655b8c54c52dba815"
        },
        {
          "file": ".missiond/v3/shards/universe/infrastructure.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 70,
          "source_hash": "6b2e914f03d12bcde8af5a271e1e0abc"
        },
        {
          "file": ".missiond/v3/shards/universe/data-residency.lisp",
          "kind": "data-residency-universe",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 77,
          "source_hash": "23834fd90b8b46a01f5dcfdc57044012"
        },
        {
          "file": ".missiond/v3/shards/universe/project-maturity.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 84,
          "source_hash": "41156cb2ff4412a1135ec2c0fd0507b7"
        },
        {
          "file": ".missiond/v3/shards/universe/project-registry.lisp",
          "kind": "multi-section-shard",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 91,
          "source_hash": "8c565d4f104ac8e28ecf4c8122e42c98"
        },
        {
          "file": ".missiond/v3/shards/universe/behavior-closure.lisp",
          "kind": "behavior-universe",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 98,
          "source_hash": "fe930f3e44a811ba2104fbdc36fa34d2"
        }
      ]
    },
    {
      "id": "implementation-map",
      "source_hash": "c62113865405c036e071ef6a89bc53cb",
      "source_units": [
        {
          "file": ".missiond/v3/shards/implementation/request-surfaces.lisp",
          "kind": "implementation-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 105,
          "source_hash": "992de6e0edd89c23cd7a58dcdfb0e6d2"
        },
        {
          "file": ".missiond/v3/shards/implementation/execution-surfaces.lisp",
          "kind": "implementation-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 112,
          "source_hash": "8f4b7eed977a390cd9889812b3eec044"
        },
        {
          "file": ".missiond/v3/shards/implementation/runtime-surfaces.lisp",
          "kind": "implementation-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 119,
          "source_hash": "830ab127c6ba5096faa73225847a688e"
        },
        {
          "file": ".missiond/v3/shards/implementation/knowledge-surfaces.lisp",
          "kind": "implementation-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 126,
          "source_hash": "eb7215a0e0f5bb9ecfb607991d762b44"
        },
        {
          "file": ".missiond/v3/shards/implementation/ops-surfaces.lisp",
          "kind": "implementation-map",
          "included_by": ".missiond/v3/shards/index.lisp",
          "include_line": 133,
          "source_hash": "a4415ad5a6fb275479d1ec33d39fb237"
        }
      ]
    }
  ],
  "runtime_policies": [
    {
      "id": "autopilot-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "autopilot-policy",
      "payload_key": "autopilot",
      "keyword_keys": [
        ":desc",
        ":stale-conversation-minutes",
        ":slot-task-reap-stale-secs",
        ":recover-stale-running-minutes",
        ":slot-failure-throttle-secs",
        ":deploy-review-timeout-secs",
        ":dynamic-slot-expiring-soon-secs",
        ":stale-board-progress-minutes",
        ":completed-job-gc-minutes",
        ":idle-persistent-slot-secs",
        ":recent-intents-window-secs",
        ":user-stuck-cooldown-secs",
        ":direction-shift-cooldown-secs",
        ":invariants",
        ":checker"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 323,
        "source_column": 3,
        "source_hash": "94844577f61f66fd3b016d4ccf74180a"
      }
    },
    {
      "id": "cascade-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "cascade-policy",
      "payload_key": "cascade",
      "keyword_keys": [
        ":desc",
        ":default-manifest",
        ":allowed-root",
        ":trigger-enabled",
        ":default-max-cycles",
        ":max-cycles-limit",
        ":env-overrides",
        ":invariants"
      ],
      "nested_forms": [
        "UNIVERSE_MANIFEST"
      ],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 344,
        "source_column": 3,
        "source_hash": "94844577f61f66fd3b016d4ccf74180a"
      }
    },
    {
      "id": "flow-runtime-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "flow-runtime-policy",
      "payload_key": "flow",
      "keyword_keys": [
        ":desc",
        ":llm-call-default-max-tokens",
        ":slot-task-default-model",
        ":slot-task-default-timeout-secs",
        ":parallel-slot-default-parallelism",
        ":parallel-slot-default-timeout-secs",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 357,
        "source_column": 3,
        "source_hash": "94844577f61f66fd3b016d4ccf74180a"
      }
    },
    {
      "id": "compute-runtime-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "compute-runtime-policy",
      "payload_key": "compute",
      "keyword_keys": [
        ":desc",
        ":invariants"
      ],
      "nested_forms": [
        "timeout-policy"
      ],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 369,
        "source_column": 3,
        "source_hash": "94844577f61f66fd3b016d4ccf74180a"
      }
    },
    {
      "id": "minimax-runtime-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "minimax-runtime-policy",
      "payload_key": "minimax",
      "keyword_keys": [
        ":desc",
        ":model",
        ":direct-http-timeout-secs",
        ":quota-throttle-secs",
        ":default-max-tokens",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 379,
        "source_column": 3,
        "source_hash": "94844577f61f66fd3b016d4ccf74180a"
      }
    },
    {
      "id": "router-runtime-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "router-runtime-policy",
      "payload_key": "router",
      "keyword_keys": [
        ":desc",
        ":default-chat-model",
        ":chat-default-max-tokens",
        ":file-chat-default-max-tokens",
        ":flow-gemini-model",
        ":stateless-sonnet-model",
        ":queued-sonnet-model",
        ":anthropic-urgent-model",
        ":anthropic-ops-model",
        ":anthropic-docs-test-chore-model",
        ":compress-model",
        ":compress-channel",
        ":compress-max-tokens",
        ":compress-char-budget-chars",
        ":direct-http-timeout-secs",
        ":router-chat-idle-timeout-secs",
        ":router-chat-retry-max-attempts",
        ":router-chat-retry-initial-backoff-ms",
        ":router-chat-retry-max-backoff-ms",
        ":gemini-pty-queue-timeout-secs",
        ":gemini-http-queue-timeout-secs",
        ":gemini-file-upload-timeout-secs",
        ":gemini-file-poll-timeout-secs",
        ":gemini-cli-absolute-timeout-secs",
        ":gemini-cli-tool-exec-timeout-secs",
        ":queued-sonnet-quota-throttle-secs",
        ":queued-sonnet-default-max-tokens",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/control-plane-runtime.lisp",
        "source_line": 390,
        "source_column": 3,
        "source_hash": "94844577f61f66fd3b016d4ccf74180a"
      }
    },
    {
      "id": "project-registry-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "project-registry-policy",
      "payload_key": "projectRegistry",
      "keyword_keys": [
        ":desc",
        ":intent-path-candidates",
        ":default-universe-manifest",
        ":env-overrides",
        ":invariants"
      ],
      "nested_forms": [
        "UNIVERSE_MANIFEST"
      ],
      "source": {
        "source_file": ".missiond/v3/shards/universe/project-registry.lisp",
        "source_line": 1,
        "source_column": 1,
        "source_hash": "94844577f61f66fd3b016d4ccf74180a"
      }
    },
    {
      "id": "capability-governance-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "capability-governance-policy",
      "payload_key": "capabilityGovernance",
      "keyword_keys": [
        ":desc",
        ":review-sidecar",
        ":protected-tool-patterns",
        ":protected-flow-patterns",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
        "source_line": 1,
        "source_column": 3,
        "source_hash": "94844577f61f66fd3b016d4ccf74180a"
      }
    },
    {
      "id": "memory-kb-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "memory-kb-policy",
      "payload_key": "memoryKb",
      "keyword_keys": [
        ":desc",
        ":pending-message-limit",
        ":tool-result-preview-chars",
        ":assistant-preview-chars",
        ":active-memory-target-ratio",
        ":sensitive-query-suppression",
        ":review-states",
        ":default-query-policy",
        ":invariants"
      ],
      "nested_forms": [
        "architecture:module",
        "active"
      ],
      "source": {
        "source_file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
        "source_line": 118,
        "source_column": 3,
        "source_hash": "94844577f61f66fd3b016d4ccf74180a"
      }
    },
    {
      "id": "conversation-ingestion-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "conversation-ingestion-policy",
      "payload_key": "conversationIngestion",
      "keyword_keys": [
        ":desc",
        ":conversation-get-tail-default",
        ":conversation-search-default-limit",
        ":message-search-default-limit",
        ":analysis-context-max-turns",
        ":label-calibration-sample-limit",
        ":jarvis-stream-envelope-schema",
        ":context-before-default",
        ":context-after-default",
        ":conversation-events-default-limit",
        ":agent-trajectory-default-limit",
        ":timeline-query-default-limit",
        ":timeline-query-max-limit",
        ":timeline-search-default-limit",
        ":timeline-search-max-limit",
        ":intent-router-model",
        ":intent-router-timeout-ms",
        ":vision-codex-binary",
        ":vision-codex-model",
        ":vision-codex-idle-timeout-secs",
        ":vision-codex-absolute-timeout-secs",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
        "source_line": 184,
        "source_column": 3,
        "source_hash": "94844577f61f66fd3b016d4ccf74180a"
      }
    },
    {
      "id": "learning-engine-policy",
      "schema_version": "missiond.runtime-policy-descriptor.v1",
      "form": "learning-engine-policy",
      "payload_key": "learningEngine",
      "keyword_keys": [
        ":desc",
        ":realtime-extraction-timeout-secs",
        ":realtime-empty-backoff-base-secs",
        ":realtime-empty-backoff-max-secs",
        ":deep-analysis-zero-output-fuse-threshold",
        ":deep-analysis-zero-output-fuse-secs",
        ":decision-tier3-timeout-secs",
        ":habit-scan-timeout-secs",
        ":token-spend-guard-window-secs",
        ":token-spend-guard-soft-limit",
        ":timeline-analysis-interval-secs",
        ":timeline-analysis-window-hours",
        ":timeline-error-limit",
        ":timeline-llm-sample-limit",
        ":timeline-slow-event-limit",
        ":timeline-slow-threshold-ms",
        ":idle-explore-interval-secs",
        ":habit-scan-interval-secs",
        ":habit-scan-batch-size",
        ":kb-auto-gc-interval-secs",
        ":kb-consolidation-interval-secs",
        ":kb-reflection-interval-secs",
        ":kb-reflection-utility-threshold",
        ":kb-reflection-min-access",
        ":kb-reflection-max-entries",
        ":kb-reflection-max-tokens",
        ":decision-harvest-interval-secs",
        ":cooccurrence-refresh-interval-secs",
        ":invariants"
      ],
      "nested_forms": [],
      "source": {
        "source_file": ".missiond/v3/shards/memory-knowledge-runtime.lisp",
        "source_line": 141,
        "source_column": 3,
        "source_hash": "94844577f61f66fd3b016d4ccf74180a"
      }
    }
  ],
  "workstation": {
    "slot_default_profiles": {
      "coder": "coding-default-opus-4-7",
      "researcher": "research-default",
      "ops": "daily-sonnet"
    },
    "slot_templates": {
      "coder": {
        "name": "coder",
        "role": "coder",
        "description": "Dynamic coder slot (ephemeral)",
        "default_model_profile": "coding-default-opus-4-7",
        "mcp_config": "$MISSION_HOME/xjp-mcp-config.json",
        "default_cwd": "/Users/jinchen/Projects"
      },
      "researcher": {
        "name": "researcher",
        "role": "coder",
        "description": "Dynamic researcher slot (read-only analysis)",
        "default_model_profile": "research-default",
        "mcp_config": "$MISSION_HOME/xjp-mcp-config.json",
        "default_cwd": "/Users/jinchen/Projects"
      },
      "ops": {
        "name": "ops",
        "role": "operator",
        "description": "Dynamic ops slot (ephemeral)",
        "default_model_profile": "daily-sonnet",
        "mcp_config": "$MISSION_HOME/xjp-mcp-config.json",
        "default_cwd": "/Users/jinchen/Projects"
      }
    },
    "model_profile_spawn_args": {
      "coding-default-opus-4-7": null,
      "research-default": null,
      "gemini-ultra-pro-preview": "gemini-3.1-pro-preview",
      "codex-master-gpt-5-5-xhigh": "gpt-5.5",
      "daily-sonnet": "sonnet",
      "quick-haiku": "haiku"
    },
    "startup_slots": [
      {
        "task_type": "arch_maintenance",
        "engine": "claude-code",
        "lifecycle": "persistent",
        "slot_id": "slot-arch-maint",
        "role": "arch-maint",
        "model_profile": "coding-default-opus-4-7",
        "timeout_secs": 600,
        "skip_permissions": true
      },
      {
        "task_type": "strategy_analyst",
        "engine": "gemini",
        "lifecycle": "persistent",
        "slot_id": "slot-gemini-strategy",
        "role": "strategy",
        "model_profile": null,
        "timeout_secs": 600,
        "skip_permissions": true
      },
      {
        "task_type": "gemini_router",
        "engine": "gemini",
        "lifecycle": "persistent",
        "slot_id": "slot-gemini-router",
        "role": "gemini-router",
        "model_profile": null,
        "timeout_secs": 120,
        "skip_permissions": true
      },
      {
        "task_type": "lisp_survey",
        "engine": "claude-code",
        "lifecycle": "persistent",
        "slot_id": "lisp-surveyor",
        "role": "coder",
        "model_profile": "coding-default-opus-4-7",
        "timeout_secs": 900,
        "skip_permissions": true
      }
    ],
    "workstation_pool": [
      {
        "id": "claude-code-default",
        "engine": "claude-code",
        "role": "coder",
        "slot_id": "slot-claude-code-default",
        "task_type": "claude_code_default",
        "model_profile": "coding-default-opus-4-7",
        "model": null,
        "task_classes": [
          "code",
          "implementation",
          "review",
          "context-pack",
          "ops"
        ],
        "capabilities": [
          "code-read",
          "code-write",
          "scoped-commit",
          "mcp"
        ],
        "max_concurrency": 1,
        "timeout_secs": 1800,
        "default_use": "code-implementation",
        "accepts_boardtask": true,
        "write_allowed": true,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": null,
        "tool_policy_path": null
      },
      {
        "id": "claude-code-deploy-ops",
        "engine": "claude-code",
        "role": "deploy-ops",
        "slot_id": "slot-claude-code-deploy-ops",
        "task_type": "claude_code_deploy_ops",
        "model_profile": "coding-default-opus-4-7",
        "model": null,
        "task_classes": [
          "deploy-ops",
          "deployment",
          "ops",
          "incident-response"
        ],
        "capabilities": [
          "deploy-read",
          "deploy-observe",
          "deploy-center-query",
          "rollback-plan",
          "mcp"
        ],
        "max_concurrency": 1,
        "timeout_secs": 2400,
        "default_use": "deployment-operations",
        "accepts_boardtask": true,
        "write_allowed": false,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": null,
        "tool_policy_path": null
      },
      {
        "id": "claude-code-fast-patch",
        "engine": "claude-code",
        "role": "patcher",
        "slot_id": "slot-claude-code-fast-patch",
        "task_type": "claude_code_fast_patch",
        "model_profile": "daily-sonnet",
        "model": null,
        "task_classes": [
          "patch",
          "test",
          "chore",
          "low-risk-fast-path"
        ],
        "capabilities": [
          "code-read",
          "code-write",
          "scoped-commit",
          "narrow-patch",
          "mcp"
        ],
        "max_concurrency": 1,
        "timeout_secs": 900,
        "default_use": "narrow-patch",
        "accepts_boardtask": true,
        "write_allowed": true,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": null,
        "tool_policy_path": null
      },
      {
        "id": "gemini-ultra-pro",
        "engine": "gemini",
        "role": "researcher",
        "slot_id": "slot-gemini-ultra",
        "task_type": "gemini_ultra",
        "model_profile": "gemini-ultra-pro-preview",
        "model": null,
        "task_classes": [
          "research",
          "review",
          "context-pack",
          "lisp-compression",
          "general"
        ],
        "capabilities": [
          "read-only",
          "analysis",
          "design-review"
        ],
        "max_concurrency": 1,
        "timeout_secs": 900,
        "default_use": "research-review",
        "accepts_boardtask": true,
        "write_allowed": false,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": "plan",
        "tool_policy_path": ".missiond/v3/policies/gemini-readonly-policy.toml"
      },
      {
        "id": "gemini-fast-survey",
        "engine": "gemini",
        "role": "survey",
        "slot_id": "slot-gemini-fast-survey",
        "task_type": "gemini_fast_survey",
        "model_profile": null,
        "model": "gemini-2.5-flash",
        "task_classes": [
          "survey",
          "summary",
          "mechanical-scan"
        ],
        "capabilities": [
          "read-only",
          "summary"
        ],
        "max_concurrency": 1,
        "timeout_secs": 600,
        "default_use": "low-authority-survey",
        "accepts_boardtask": true,
        "write_allowed": false,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": "plan",
        "tool_policy_path": ".missiond/v3/policies/gemini-readonly-policy.toml"
      },
      {
        "id": "agy-research",
        "engine": "agy",
        "role": "researcher",
        "slot_id": "slot-agy-research",
        "task_type": "agy_research",
        "model_profile": null,
        "model": null,
        "task_classes": [
          "research",
          "review",
          "context-pack",
          "survey"
        ],
        "capabilities": [
          "read-only",
          "analysis",
          "design-review",
          "provider-successor"
        ],
        "max_concurrency": 1,
        "timeout_secs": 900,
        "default_use": "agy-read-only-research",
        "accepts_boardtask": true,
        "write_allowed": false,
        "reasoning_effort": null,
        "search_enabled": false,
        "sandbox": null,
        "approval_policy": null,
        "tool_policy_path": null
      },
      {
        "id": "codex-code-worker",
        "engine": "codex",
        "role": "coder",
        "slot_id": "slot-codex-code-worker",
        "task_type": "codex_code_worker",
        "model_profile": "codex-master-gpt-5-5-xhigh",
        "model": null,
        "task_classes": [
          "code",
          "implementation",
          "design",
          "review",
          "regression-analysis"
        ],
        "capabilities": [
          "code-read",
          "code-write",
          "scoped-commit",
          "shell-exec",
          "search"
        ],
        "max_concurrency": 1,
        "timeout_secs": 1800,
        "default_use": "codex-code-shard",
        "accepts_boardtask": true,
        "write_allowed": true,
        "reasoning_effort": "xhigh",
        "search_enabled": true,
        "sandbox": "danger-full-access",
        "approval_policy": "never",
        "tool_policy_path": null
      },
      {
        "id": "codex-review-worker",
        "engine": "codex",
        "role": "reviewer",
        "slot_id": "slot-codex-review-worker",
        "task_type": "codex_review_worker",
        "model_profile": "codex-master-gpt-5-5-xhigh",
        "model": null,
        "task_classes": [
          "review",
          "architecture-review",
          "regression-analysis"
        ],
        "capabilities": [
          "code-read",
          "design-review",
          "search"
        ],
        "max_concurrency": 1,
        "timeout_secs": 1200,
        "default_use": "codex-review-shard",
        "accepts_boardtask": true,
        "write_allowed": false,
        "reasoning_effort": "xhigh",
        "search_enabled": true,
        "sandbox": "read-only",
        "approval_policy": "never",
        "tool_policy_path": null
      },
      {
        "id": "codex-master-control",
        "engine": "codex",
        "role": "orchestrator",
        "slot_id": "slot-codex-master-control",
        "task_type": "codex_master_control",
        "model_profile": "codex-master-gpt-5-5-xhigh",
        "model": null,
        "task_classes": [
          "master-control",
          "orchestration",
          "governance",
          "night-audit"
        ],
        "capabilities": [
          "board-write",
          "kb-write",
          "execution-log",
          "dispatch",
          "code-read",
          "code-write",
          "shell-exec",
          "search",
          "mcp",
          "full-access"
        ],
        "max_concurrency": 1,
        "timeout_secs": 7200,
        "default_use": "resident-master-control",
        "accepts_boardtask": false,
        "write_allowed": true,
        "reasoning_effort": "xhigh",
        "search_enabled": true,
        "sandbox": "danger-full-access",
        "approval_policy": "never",
        "tool_policy_path": null
      }
    ],
    "allowed_cwd_prefixes": [
      "/Users/jinchen/Projects",
      "/Users/jinchen/Downloads",
      "/Users/jinchen/Documents",
      "/tmp"
    ],
    "chat_completions_default_slot": "slot-claude-code-default",
    "timeout_policy": {
      "default_secs": 1800,
      "min_secs": 60,
      "max_secs": 7200,
      "watchdog_grace_secs": 120,
      "missing_session_probe_secs": 120
    },
    "cc_swarm_timeout_policy": {
      "default_secs": 600,
      "min_secs": 60,
      "max_secs": 7200
    },
    "pty_send_timeout_policy": {
      "default_secs": 300,
      "min_secs": 1,
      "max_secs": 7200
    },
    "dynamic_slot_spawn_timeout_policy": {
      "default_secs": 60,
      "min_secs": 10,
      "max_secs": 600
    },
    "context_pack_dispatch_policy": {
      "default_max_parallel": 4,
      "min_parallel": 1,
      "max_parallel": 8
    },
    "swarm_capacity_policy": {
      "default_claude_workers": 8,
      "max_claude_workers": 16,
      "default_gemini_workers": 2,
      "max_gemini_workers": 6,
      "dynamic_slot_limit": 20,
      "delegate_rate_per_minute": 24
    },
    "slot_ttl_policy": {
      "default_secs": 14400,
      "min_secs": 300,
      "max_secs": 28800,
      "default_extend_secs": 3600,
      "max_extend_secs": 3600
    }
  },
  "flow": {
    "llm_call_default_max_tokens": 65536,
    "slot_task_default_model": "opus",
    "slot_task_default_timeout_secs": 3600,
    "parallel_slot_default_parallelism": 3,
    "parallel_slot_default_timeout_secs": 1800
  },
  "compute": {
    "pty_spawn_timeout_policy": {
      "default_secs": 30,
      "min_secs": 1,
      "max_secs": 600
    }
  },
  "minimax": {
    "model": "MiniMax-M2.5-highspeed",
    "direct_http_timeout_secs": 30,
    "quota_throttle_secs": 60,
    "default_max_tokens": 500
  },
  "router": {
    "default_chat_model": "gemini-3.1-pro",
    "chat_default_max_tokens": 16384,
    "file_chat_default_max_tokens": 65536,
    "flow_gemini_model": "gemini-3.1-pro",
    "stateless_sonnet_model": "claude-sonnet",
    "queued_sonnet_model": "claude-sonnet",
    "anthropic_urgent_model": "claude-opus-4-6",
    "anthropic_ops_model": "claude-sonnet-4.5",
    "anthropic_docs_test_chore_model": "claude-haiku-4-5-20251001",
    "compress_model": "gemini-3.1-pro",
    "compress_channel": "google",
    "compress_max_tokens": 2048,
    "compress_char_budget_chars": 100000,
    "direct_http_timeout_secs": 60,
    "router_chat_idle_timeout_secs": 600,
    "router_chat_retry_max_attempts": 3,
    "router_chat_retry_initial_backoff_ms": 250,
    "router_chat_retry_max_backoff_ms": 2000,
    "gemini_pty_queue_timeout_secs": 30,
    "gemini_http_queue_timeout_secs": 300,
    "gemini_file_upload_timeout_secs": 600,
    "gemini_file_poll_timeout_secs": 300,
    "gemini_cli_absolute_timeout_secs": 900,
    "gemini_cli_tool_exec_timeout_secs": 300,
    "queued_sonnet_quota_throttle_secs": 30,
    "queued_sonnet_default_max_tokens": 1024
  },
  "cascade": {
    "default_manifest_path": "/Users/jinchen/Projects/universe.intent.lisp",
    "allowed_root": "/Users/jinchen/Projects",
    "trigger_enabled": true,
    "default_max_cycles": 3,
    "max_cycles_limit": 12
  },
  "projectRegistry": {
    "intent_path_candidates": [
      ".missiond/intent.lisp",
      ".jarvis/intent.lisp",
      "intent.lisp"
    ],
    "default_universe_manifest": "/Users/jinchen/Projects/universe.intent.lisp"
  },
  "capabilityGovernance": {
    "review_sidecar_path": ".missiond/v3/runtime/capability-usage-review.json",
    "protected_tool_patterns": [
      "mission_execution",
      "mission_intent",
      "mission_forge_",
      "mission_sys_",
      "mission_daemon_update",
      "mission_health",
      "mission_power_control",
      "mission_kb_ops",
      "mission_audit",
      "mission_pty_signal",
      "mission_pty_confirm",
      "mission_incident"
    ],
    "protected_flow_patterns": [
      "engineering",
      "F-execution-log-governance",
      "F-incident-reaction",
      "F-capability-usage-monitoring"
    ]
  },
  "memoryKb": {
    "pending_message_limit": 60,
    "tool_result_preview_chars": 1000,
    "assistant_preview_chars": 500
  },
  "conversationIngestion": {
    "conversation_get_tail_default": 50,
    "conversation_search_default_limit": 10,
    "message_search_default_limit": 20,
    "context_before_default": 3,
    "context_after_default": 5,
    "conversation_events_default_limit": 100,
    "agent_trajectory_default_limit": 200,
    "timeline_query_default_limit": 50,
    "timeline_query_max_limit": 200,
    "timeline_search_default_limit": 20,
    "timeline_search_max_limit": 100,
    "intent_router_model": "claude-opus-4.6",
    "intent_router_timeout_ms": 10000,
    "vision_codex_binary": "codex",
    "vision_codex_model": "gpt-5.4",
    "vision_codex_idle_timeout_secs": 120,
    "vision_codex_absolute_timeout_secs": 300
  },
  "autopilot": {
    "boardtask_timeout_policy": {
      "default_secs": 1800,
      "min_secs": 60,
      "max_secs": 7200,
      "watchdog_grace_secs": 120,
      "missing_session_probe_secs": 120
    },
    "stale_conversation_minutes": 10,
    "slot_task_reap_stale_secs": 1800,
    "recover_stale_running_minutes": 15,
    "slot_failure_throttle_secs": 1800,
    "deploy_review_timeout_secs": 600,
    "dynamic_slot_expiring_soon_secs": 900,
    "stale_board_progress_minutes": 30,
    "completed_job_gc_minutes": 30,
    "idle_persistent_slot_secs": 1800,
    "recent_intents_window_secs": 1800,
    "user_stuck_cooldown_secs": 1800,
    "direction_shift_cooldown_secs": 3600
  },
  "learningEngine": {
    "realtime_extraction_timeout_secs": 300,
    "realtime_empty_backoff_base_secs": 30,
    "realtime_empty_backoff_max_secs": 900,
    "deep_analysis_zero_output_fuse_threshold": 3,
    "deep_analysis_zero_output_fuse_secs": 3600,
    "decision_tier3_timeout_secs": 300,
    "habit_scan_timeout_secs": 600,
    "token_spend_guard_window_secs": 3600,
    "token_spend_guard_soft_limit": 250000,
    "timeline_analysis_interval_secs": 43200,
    "timeline_analysis_window_hours": 12,
    "timeline_error_limit": 20,
    "timeline_llm_sample_limit": 50,
    "timeline_slow_event_limit": 20,
    "timeline_slow_threshold_ms": 60000,
    "idle_explore_interval_secs": 7200,
    "habit_scan_interval_secs": 14400,
    "habit_scan_batch_size": 5,
    "kb_auto_gc_interval_secs": 3600,
    "kb_consolidation_interval_secs": 86400,
    "kb_reflection_interval_secs": 604800,
    "kb_reflection_utility_threshold": 0.3,
    "kb_reflection_min_access": 3,
    "kb_reflection_max_entries": 20,
    "kb_reflection_max_tokens": 2000,
    "decision_harvest_interval_secs": 86400,
    "cooccurrence_refresh_interval_secs": 21600
  }
}
"#;
