(work-order-plan
  :schema "missiond.work-order.plan.v1"
  :id "wo-20260602085705-Implement-deployment-closure-pol"
  :intent "wo-20260602085705-Implement-deployment-closure-pol"
  :status draft
  :accepted_shards
    ((shard default
       :accepted_shard_id "wo-20260602085705-Implement-deployment-closure-pol-shard-default"
       :read_scope ["."]
       :write_scope [".missiond/v3/missiond-blueprint.lisp"
                     "scripts/compile-v3-runtime.mjs"
                     "scripts/deploy-daemon.sh"
                     ".missiond/v3/shards/index.lisp"
                     ".missiond/v3/shards/deployment-closure-plane.lisp"
                     ".missiond/v3/shards/ops-infra.lisp"
                     ".missiond/v3/shards/implementation/ops-surfaces.lisp"
                     ".missiond/v3/shards/request-runtime.lisp"
                     ".missiond/v3/shards/memory-knowledge-runtime.lisp"
                     "crates/missiond-core/src/types/knowledge.rs"
                     "crates/missiond-core/src/db/traits.rs"
                     "crates/missiond-core/src/db/pg/knowledge.rs"
                     "crates/missiond-daemon/src/context/v3_contracts/generated.rs"
                     "crates/missiond-daemon/src/context/v3_blueprint_runtime.rs"
                     "crates/missiond-daemon/src/context/v3_blueprint_runtime/compiled_snapshot.rs"
                     "crates/missiond-daemon/src/context/v3_runtime_defaults/generated.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/context_gather.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/memory.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/project.rs"
                     "crates/missiond-daemon/src/handlers/knowledge/project/registry.rs"
                     "crates/missiond-daemon/src/handlers/sysinfra/infra.rs"
                     "crates/missiond-daemon/src/handlers/comm/timeline.rs"
                     "crates/missiond-mcp/src/tools/knowledge/memory.rs"
                     "scripts/check-v3-memory-kb-isomorphism.mjs"
                     "scripts/check-v3-ops-infra-isomorphism.mjs"
                     "scripts/check-missiond-blue-green-deploy.mjs"
                     "scripts/check-v3-deployment-closure-plane.mjs"
                     "scripts/generated/v3_contracts.d.ts"
                     "scripts/generated/v3_contracts.mjs"
                     "scripts/generated/v3_runtime_defaults.mjs"]
       :acceptance ["node scripts/compile-v3-runtime.mjs --check --json"
                    "node scripts/check-v3-memory-kb-isomorphism.mjs --json"
                    "node scripts/check-v3-ops-infra-isomorphism.mjs --json"
                    "node scripts/check-missiond-blue-green-deploy.mjs --json"
                    "node scripts/check-v3-deployment-closure-plane.mjs --json"
                    "cargo check -p missiond-daemon"])))
