(work-order-plan
  :schema "missiond.work-order.plan.v1"
  :id "20260523-jarvis-intent-plan-codex-agy"
  :intent "20260523-jarvis-intent-plan-codex-agy"
  :status draft
  :accepted_shards
    ((shard default
       :accepted_shard_id "20260523-jarvis-intent-plan-codex-agy-shard-default"
       :read_scope ["."]
	       :write_scope [".missiond/frontend/board-blueprint.lisp"
	                     ".missiond/v3/evidence/codex-boot-context.lisp"
	                     ".missiond/v3/evidence/workstation-pool.lisp"
	                     ".missiond/v3/shards/memory-knowledge-runtime.lisp"
	                     ".missiond/v3/shards/v2-convergence-map.lisp"
	                     ".missiond/v3/shards/implementation/runtime-surfaces.lisp"
	                     ".missiond/v3/shards/universe/infrastructure.lisp"
	                     ".missiond/v3/shards/workstation-runtime.lisp"
	                     ".missiond/work-orders/20260523-jarvis-intent-plan-codex-agy/plan.lisp"
	                     ".missiond/workflows/m6-deployment-rollout.lisp"
	                     "crates/missiond-core/migrations/20260523003000_codex_replay.sql"
	                     "crates/missiond-core/src/lib.rs"
                     "crates/missiond-core/src/types/mod.rs"
                     "crates/missiond-core/src/types/slot.rs"
                     "crates/missiond-core/src/ws/mod.rs"
                     "crates/missiond-core/src/ws/server.rs"
                     "crates/missiond-daemon/src/context/v3_blueprint_runtime.rs"
                     "crates/missiond-daemon/src/context/v3_blueprint_runtime/**"
                     "crates/missiond-daemon/src/context/v3_contracts/generated.rs"
	                     "crates/missiond-daemon/src/context/v3_runtime_defaults/generated.rs"
	                     "crates/missiond-daemon/src/control_tree.rs"
	                     "crates/missiond-daemon/src/engine/codex_replay.rs"
	                     "crates/missiond-daemon/src/engine/mod.rs"
	                     "crates/missiond-daemon/src/engine/intent_engine/autopilot.rs"
	                     "crates/missiond-daemon/src/handlers/compute/slot.rs"
	                     "crates/missiond-daemon/src/handlers/comm/codex_replay.rs"
	                     "crates/missiond-daemon/src/handlers/comm/mod.rs"
	                     "crates/missiond-daemon/src/handlers/mod.rs"
	                     "crates/missiond-daemon/src/handlers/knowledge/request/respond/materialization.rs"
	                     "crates/missiond-daemon/src/main.rs"
	                     "crates/missiond-daemon/src/state.rs"
	                     "crates/missiond-daemon/src/workers/local/codex_ingestion_worker.rs"
	                     "crates/missiond-mcp/src/tools/comm/codex_replay.rs"
	                     "crates/missiond-mcp/src/tools/comm/mod.rs"
	                     "crates/missiond-mcp/src/tools/mod.rs"
	                     "crates/missiond-daemon/src/slot_orchestrator/**"
	                     "crates/missiond-pty/src/pty_recognition.rs"
	                     "crates/missiond-pty/src/session.rs"
	                     "packages/board/src/App.tsx"
	                     "packages/board/src/app/api/codex-replay/**"
	                     "packages/board/src/components/CodexReplayDashboard.tsx"
	                     "packages/board/src/generated/board-frontend-config.ts"
	                     "scripts/check-v3-agent-cli-regression.mjs"
	                     "scripts/check-v3-cli-conversation-ingestion-isomorphism.mjs"
	                     "scripts/check-v3-code-isomorphism-complete.mjs"
	                     "scripts/check-v3-final-convergence.mjs"
	                     "scripts/check-v3-infrastructure-universe-isomorphism.mjs"
	                     "scripts/check-v3-pty-recognition-isomorphism.mjs"
                     "scripts/check-v3-workstation-pool-isomorphism.mjs"
                     "scripts/deploy-daemon.sh"
                     "scripts/generated/v3_contracts.d.ts"
                     "scripts/generated/v3_contracts.mjs"
                     "scripts/generated/v3_runtime_defaults.mjs"
                     "scripts/lib/v3_compiled_contract.mjs"
                     "tools/missiond_lispc/bin/emit_json.ml"]
       :acceptance ["cargo check -p missiond-core -p missiond-daemon"
                    "cargo test -p missiond-pty agy -- --nocapture"
                    "cargo test -p missiond-core jarvis -- --nocapture"
                    "bash scripts/rustfmt-missiond.sh --check"
                    "node scripts/check-v3-grounded-dispatch-isomorphism.mjs --json"
                    "node scripts/check-v3-workflow-isomorphism.mjs --engine=ocaml --json"
                    "node scripts/check-v3-workstation-pool-isomorphism.mjs --json"
                    "node scripts/check-v3-agent-cli-regression.mjs --json"
                    "node scripts/check-v3-code-isomorphism-complete.mjs --json"
                    "node scripts/check-v3-final-convergence.mjs --json --static-only"
                    "git diff --check"])))
