// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent.lisp (pure-utility string-helpers)
// Pattern: pure-utility (algorithm isolation chamber)
//
// Implement the trait in custom.rs — only pure functions allowed.

#[allow(unused_imports)]
use std::time::Duration;


// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in custom.rs
// ═══════════════════════════════════════════════════════════

pub trait StringHelpers {
    /// Truncate string to at most max_bytes, never breaking a char boundary. Returns a valid UTF-8 slice.
    fn safe_byte_truncate(s: &str, max_bytes: usize) -> &str;

    /// Truncate string to at most max_chars Unicode characters.
    fn safe_char_truncate(s: &str, max_chars: usize) -> &str;
}

// ═══════════════════════════════════════════════════════════
// Stub: replace todo!() in custom.rs with real logic
// ═══════════════════════════════════════════════════════════

pub struct StringHelpersImpl;

impl StringHelpers for StringHelpersImpl {
    /// Truncate string to at most max_bytes, never breaking a char boundary. Returns a valid UTF-8 slice.
    fn safe_byte_truncate(_s: &str, _max_bytes: usize) -> &str {
        todo!("implement safe_byte_truncate in custom.rs")
    }

    /// Truncate string to at most max_chars Unicode characters.
    fn safe_char_truncate(_s: &str, _max_chars: usize) -> &str {
        todo!("implement safe_char_truncate in custom.rs")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_safe_byte_truncate_ascii_within() {
        let result = StringHelpersImpl::safe_byte_truncate("hello", 10);
        assert_eq!(result, "hello");
    }

    #[test]
    fn test_safe_byte_truncate_ascii_exact() {
        let result = StringHelpersImpl::safe_byte_truncate("hello", 5);
        assert_eq!(result, "hello");
    }

    #[test]
    fn test_safe_byte_truncate_ascii_cut() {
        let result = StringHelpersImpl::safe_byte_truncate("hello world", 5);
        assert_eq!(result, "hello");
    }

    #[test]
    fn test_safe_byte_truncate_cjk_boundary() {
        let result = StringHelpersImpl::safe_byte_truncate("abc你好", 4);
        assert_eq!(result, "abc");
    }

    #[test]
    fn test_safe_byte_truncate_cjk_boundary_6() {
        let result = StringHelpersImpl::safe_byte_truncate("abc你好", 6);
        assert_eq!(result, "abc你");
    }

    #[test]
    fn test_safe_byte_truncate_box_drawing() {
        let result = StringHelpersImpl::safe_byte_truncate("ab═cd", 4);
        assert_eq!(result, "ab");
    }

    #[test]
    fn test_safe_byte_truncate_empty() {
        let result = StringHelpersImpl::safe_byte_truncate("", 100);
        assert_eq!(result, "");
    }

    #[test]
    fn test_safe_byte_truncate_zero_max() {
        let result = StringHelpersImpl::safe_byte_truncate("hello", 0);
        assert_eq!(result, "");
    }

    #[test]
    fn test_safe_char_truncate_within() {
        let result = StringHelpersImpl::safe_char_truncate("hello", 10);
        assert_eq!(result, "hello");
    }

    #[test]
    fn test_safe_char_truncate_cut() {
        let result = StringHelpersImpl::safe_char_truncate("hello world", 5);
        assert_eq!(result, "hello");
    }

    #[test]
    fn test_safe_char_truncate_cjk() {
        let result = StringHelpersImpl::safe_char_truncate("你好世界", 2);
        assert_eq!(result, "你好");
    }

}
