// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-pure-utility.lisp (pure-utility token-budget)
// Pattern: pure-utility (algorithm isolation chamber)
//
// Implement the trait in custom.rs — only pure functions allowed.

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in custom.rs
// ═══════════════════════════════════════════════════════════

pub trait TokenBudget {
    /// Rough token count estimate: chars / 4 for English, / 2 for CJK
    fn estimate_tokens(text: &str) -> usize;

    /// Divide token budget across N sources with diminishing returns per source
    fn allocate_budget(total: usize, source_count: usize) -> Vec<usize>;
}
