// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent.lisp (domain-types crates/missiond-core/src/types/gen_types.rs)
// Pattern: domain-types

use serde::{Deserialize, Serialize};

/// Board task execution status
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "lowercase")]
pub enum BoardTaskStatus {
    Open,
    Running,
    Verifying,
    Done,
    Blocked,
    Failed,
    Skipped,
}

impl BoardTaskStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Open => "open",
            Self::Running => "running",
            Self::Verifying => "verifying",
            Self::Done => "done",
            Self::Blocked => "blocked",
            Self::Failed => "failed",
            Self::Skipped => "skipped",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "open" => Some(Self::Open),
            "running" => Some(Self::Running),
            "verifying" => Some(Self::Verifying),
            "done" => Some(Self::Done),
            "blocked" => Some(Self::Blocked),
            "failed" => Some(Self::Failed),
            "skipped" => Some(Self::Skipped),
            _ => None,
        }
    }
}

/// Board task note type
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "lowercase")]
pub enum BoardNoteType {
    Progress,
    Summary,
    Note,
}

impl BoardNoteType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Progress => "progress",
            Self::Summary => "summary",
            Self::Note => "note",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "progress" => Some(Self::Progress),
            "summary" => Some(Self::Summary),
            "note" => Some(Self::Note),
            _ => None,
        }
    }
}

/// Phase in the engineering task flow state machine
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "snake_case")]
pub enum EngineeringPhase {
    Investigate,
    ConsultGemini1,
    Plan,
    ConsultGemini2,
    Execute,
    Finalize,
    Done,
}

impl EngineeringPhase {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Investigate => "investigate",
            Self::ConsultGemini1 => "consult_gemini1",
            Self::Plan => "plan",
            Self::ConsultGemini2 => "consult_gemini2",
            Self::Execute => "execute",
            Self::Finalize => "finalize",
            Self::Done => "done",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "investigate" => Some(Self::Investigate),
            "consult_gemini1" => Some(Self::ConsultGemini1),
            "plan" => Some(Self::Plan),
            "consult_gemini2" => Some(Self::ConsultGemini2),
            "execute" => Some(Self::Execute),
            "finalize" => Some(Self::Finalize),
            "done" => Some(Self::Done),
            _ => None,
        }
    }
}

/// Background task queue status
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "lowercase")]
pub enum TaskStatus {
    Queued,
    Running,
    Completed,
    Failed,
}

impl TaskStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Queued => "queued",
            Self::Running => "running",
            Self::Completed => "completed",
            Self::Failed => "failed",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "queued" => Some(Self::Queued),
            "running" => Some(Self::Running),
            "completed" => Some(Self::Completed),
            "failed" => Some(Self::Failed),
            _ => None,
        }
    }
}

/// Task event type
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "snake_case")]
pub enum EventType {
    TaskCreated,
    TaskStarted,
    TaskCompleted,
    TaskFailed,
    MessageSent,
    MessageReceived,
}

impl EventType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::TaskCreated => "task_created",
            Self::TaskStarted => "task_started",
            Self::TaskCompleted => "task_completed",
            Self::TaskFailed => "task_failed",
            Self::MessageSent => "message_sent",
            Self::MessageReceived => "message_received",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "task_created" => Some(Self::TaskCreated),
            "task_started" => Some(Self::TaskStarted),
            "task_completed" => Some(Self::TaskCompleted),
            "task_failed" => Some(Self::TaskFailed),
            "message_sent" => Some(Self::MessageSent),
            "message_received" => Some(Self::MessageReceived),
            _ => None,
        }
    }
}

/// Async job execution status
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "lowercase")]
pub enum AsyncJobStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Cancelled,
}

impl AsyncJobStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Running => "running",
            Self::Completed => "completed",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "pending" => Some(Self::Pending),
            "running" => Some(Self::Running),
            "completed" => Some(Self::Completed),
            "failed" => Some(Self::Failed),
            "cancelled" => Some(Self::Cancelled),
            _ => None,
        }
    }
}

/// Agent question lifecycle status
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "lowercase")]
pub enum AgentQuestionStatus {
    Pending,
    Answered,
    Dismissed,
    Expired,
    Harvested,
}

impl AgentQuestionStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Answered => "answered",
            Self::Dismissed => "dismissed",
            Self::Expired => "expired",
            Self::Harvested => "harvested",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "pending" => Some(Self::Pending),
            "answered" => Some(Self::Answered),
            "dismissed" => Some(Self::Dismissed),
            "expired" => Some(Self::Expired),
            "harvested" => Some(Self::Harvested),
            _ => None,
        }
    }
}

/// Incident severity level
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "lowercase")]
pub enum IncidentSeverity {
    Critical,
    High,
    Medium,
    Low,
    Info,
}

impl IncidentSeverity {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Critical => "critical",
            Self::High => "high",
            Self::Medium => "medium",
            Self::Low => "low",
            Self::Info => "info",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "critical" => Some(Self::Critical),
            "high" => Some(Self::High),
            "medium" => Some(Self::Medium),
            "low" => Some(Self::Low),
            "info" => Some(Self::Info),
            _ => None,
        }
    }
}

/// Incident source system
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "lowercase")]
pub enum IncidentSource {
    Monitoring,
    AlertManager,
    Manual,
    System,
    Webhook,
}

impl IncidentSource {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Monitoring => "monitoring",
            Self::AlertManager => "alert_manager",
            Self::Manual => "manual",
            Self::System => "system",
            Self::Webhook => "webhook",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "monitoring" => Some(Self::Monitoring),
            "alert_manager" => Some(Self::AlertManager),
            "manual" => Some(Self::Manual),
            "system" => Some(Self::System),
            "webhook" => Some(Self::Webhook),
            _ => None,
        }
    }
}

/// DAG dependency resolution result
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum DependencyStatus {}

/// CLI engine for PTY slots
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "lowercase")]
pub enum CliEngine {
    ClaudeCode,
    ClaudeMd,
}

impl CliEngine {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::ClaudeCode => "claude_code",
            Self::ClaudeMd => "claude_md",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "claude_code" => Some(Self::ClaudeCode),
            "claude_md" => Some(Self::ClaudeMd),
            _ => None,
        }
    }
}

/// Slot lifecycle mode
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "lowercase")]
pub enum Lifecycle {
    Persistent,
    Transient,
}

impl Lifecycle {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Persistent => "persistent",
            Self::Transient => "transient",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "persistent" => Some(Self::Persistent),
            "transient" => Some(Self::Transient),
            _ => None,
        }
    }
}

/// Slot capability trait
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
#[serde(rename_all = "snake_case")]
pub enum SlotTrait {
    Memory,
    Sonnet,
    AutoPilot,
    Decision,
    Strategy,
}

impl SlotTrait {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Memory => "memory",
            Self::Sonnet => "sonnet",
            Self::AutoPilot => "auto_pilot",
            Self::Decision => "decision",
            Self::Strategy => "strategy",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "memory" => Some(Self::Memory),
            "sonnet" => Some(Self::Sonnet),
            "auto_pilot" => Some(Self::AutoPilot),
            "decision" => Some(Self::Decision),
            "strategy" => Some(Self::Strategy),
            _ => None,
        }
    }
}

/// Context passed between engineering flow phases
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowContext {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub investigation_report: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gemini_advice_1: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub execution_plan: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gemini_advice_2: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub execution_result: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub commit_hash: Option<String>,
}

impl Default for FlowContext {
    fn default() -> Self {
        Self {
            investigation_report: None,
            gemini_advice_1: None,
            execution_plan: None,
            gemini_advice_2: None,
            execution_result: None,
            commit_hash: None,
        }
    }
}

/// Personal task board entry
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BoardTask {
    pub id: TaskId,
    pub title: String,
    pub description: String,
    pub status: BoardTaskStatus,
    pub priority: String,
    pub category: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub server: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<TaskId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assignee: Option<String>,
    pub auto_execute: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_template: Option<String>,
    pub hidden: bool,
    pub retry_count: i64,
    pub max_retries: i64,
    pub order_idx: i64,
    pub created_at: String,
    pub updated_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claim_executor_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claim_executor_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claimed_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flow_phase: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flow_context: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flow_template: Option<String>,
    pub depends_on: Vec<TaskId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lease_expires_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dedupe_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout_secs: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_intent: Option<String>,
    pub notes_count: i64,
}

/// Compact board task for search results
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CompactBoardTask {
    pub id: TaskId,
    pub title: String,
    pub status: BoardTaskStatus,
    pub priority: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<TaskId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    pub category: String,
}

/// Note attached to a board task
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BoardTaskNote {
    pub id: String,
    pub task_id: String,
    pub content: String,
    pub note_type: BoardNoteType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    pub created_at: String,
}

/// Input for creating a board task
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateBoardTaskInput {
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub server: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assignee: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_execute: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_template: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dedupe_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout_secs: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_intent: Option<String>,
}

impl Default for CreateBoardTaskInput {
    fn default() -> Self {
        Self {
            title: String::new(),
            description: None,
            priority: None,
            category: None,
            project: None,
            server: None,
            due_date: None,
            parent_id: None,
            assignee: None,
            auto_execute: None,
            prompt_template: None,
            hidden: None,
            depends_on: None,
            dedupe_key: None,
            timeout_secs: None,
            context_intent: None,
        }
    }
}

/// Input for updating a board task
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateBoardTaskInput {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub server: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assignee: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_execute: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_template: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_idx: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flow_phase: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flow_context: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flow_template: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claim_executor_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claim_executor_type: Option<String>,
}

impl Default for UpdateBoardTaskInput {
    fn default() -> Self {
        Self {
            title: None,
            description: None,
            status: None,
            priority: None,
            category: None,
            project: None,
            server: None,
            due_date: None,
            parent_id: None,
            assignee: None,
            auto_execute: None,
            prompt_template: None,
            hidden: None,
            order_idx: None,
            flow_phase: None,
            flow_context: None,
            flow_template: None,
            depends_on: None,
            claim_executor_id: None,
            claim_executor_type: None,
        }
    }
}

/// Claude Code conversation session
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Conversation {
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slot_id: Option<String>,
    pub source: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub git_branch: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub jsonl_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_session_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,
    pub message_count: i64,
    pub started_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<String>,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub analyzed_at: Option<String>,
    pub analysis_version: i32,
    pub analysis_retries: i32,
    pub deep_analyzed_message_id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub chat_type: Option<String>,
    pub conversation_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub llm_summary: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub embedding_provider: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_timeline: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeline_built_at: Option<String>,
}

/// Single message in a conversation
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConversationMessage {
    pub id: i64,
    pub session_id: String,
    pub role: String,
    pub content: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub raw_content: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_uuid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_uuid: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    pub timestamp: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub raw_role: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_types: Option<String>,
    pub has_image: bool,
    pub has_tool_use: bool,
    pub has_tool_result: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role_display: Option<String>,
}

/// Knowledge base entry
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct KnowledgeEntry {
    pub id: String,
    pub category: String,
    pub key: String,
    pub summary: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    pub source: String,
    pub confidence: f64,
    pub access_count: i64,
    pub created_at: String,
    pub updated_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_accessed_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub linked_task_id: Option<String>,
    #[serde(default)]
    pub kb_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_snippet: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope_task_id: Option<String>,
    #[serde(default)]
    pub utility_score: f64,
}

/// Input for remembering knowledge
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct KBRememberInput {
    pub category: String,
    pub key: String,
    pub summary: String,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
}

/// Knowledge graph edge
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct KBEdge {
    pub source_id: String,
    pub target_id: String,
    pub relation_type: String,
    pub weight: f64,
    pub created_at: String,
}

/// Background task in task queue
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Task {
    pub id: String,
    pub role: String,
    pub prompt: String,
    pub status: TaskStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slot_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    pub created_at: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finished_at: Option<i64>,
}

/// Inter-agent inbox message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InboxMessage {
    pub id: String,
    pub task_id: String,
    pub from_role: String,
    pub content: String,
    pub read: bool,
    pub created_at: i64,
}

/// Task lifecycle event
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskEvent {
    pub id: i64,
    pub task_id: String,
    pub event_type: EventType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    pub timestamp: i64,
}

/// Agent decision point question
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentQuestion {
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slot_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    pub question: String,
    pub context: String,
    pub status: AgentQuestionStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub answer: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub target: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<String>,
    pub decision_type: String,
    pub retry_count: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub routing_trace: Option<String>,
}

/// Incident record
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IncidentRow {
    pub id: String,
    pub severity: String,
    pub source: String,
    pub title: String,
    pub description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub raw_payload: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub board_task_id: Option<String>,
    pub dedupe_key: String,
    pub created_at: String,
}

/// Dynamically spawned compute slot
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DynamicSlot {
    pub id: String,
    pub parent_slot_id: String,
    pub template: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub objective: Option<String>,
    pub config: String,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub termination_reason: Option<String>,
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub terminated_at: Option<String>,
    pub ttl_seconds: i32,
    pub expires_at: String,
    pub extend_count: i32,
}

/// Skill topic definition
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillTopic {
    pub topic: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aka: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub allowed_tools: Option<String>,
    pub file_path: String,
    pub hit_count: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_hit_at: Option<String>,
    pub fragment_count: i32,
    pub total_lines: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub requires_json: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actions_json: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_hooks_json: Option<String>,
}

/// Skill content block
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillBlock {
    pub id: String,
    pub topic: String,
    pub block_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    pub content: String,
    pub sort_order: i32,
    pub status: String,
    pub created_at: String,
    pub updated_at: String,
}

/// Tool call audit record
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolCallRecord {
    pub id: String,
    pub session_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_id: Option<i64>,
    pub tool_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_summary: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub raw_input: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_summary: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub raw_output: Option<String>,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i32>,
    pub timestamp: String,
}
