// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent.lisp (domain-engine autopilot)
// Pattern: domain-engine (zero internal logic)
//
// Implement EngineLogic trait in custom.rs — all business logic lives there.

use anyhow::Result;
use async_trait::async_trait;


pub struct Autopilot {
    pub(crate) db: DbExecutor,
    pub(crate) slots: Arc<SlotOrchestrator>,
    pub(crate) event_bus: EventBus,
    pub(crate) llm: LlmGateway,
    pub(crate) context: ContextPipeline,
}

impl Autopilot {
    pub fn new(db: DbExecutor, slots: Arc<SlotOrchestrator>, event_bus: EventBus, llm: LlmGateway, context: ContextPipeline) -> Self {
        Self {
            db,
            slots,
            event_bus,
            llm,
            context,
        }
    }
}

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in custom.rs
// ═══════════════════════════════════════════════════════════

#[async_trait]
pub trait AutopilotLogic {
    /// Execute one full tick cycle: memory → extraction → task → decision → flow
    async fn tick(&self) -> Result<()>;

    /// Pause the tick loop
    async fn pause(&self) -> ();

    /// Resume the tick loop
    async fn resume(&self) -> ();
}

