// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module insight)

use serde_json::json;
use crate::ToolDefinition;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_insight =====
        ToolDefinition::new(
            "mission_insight",
            "查看 MissionD 战略认知 — 开发轨迹、协作模式、反面模式、摩擦点。纯只读",
            json!({
                "type": "object",
                "properties": {
                    "section": {"type": "string", "enum": ["all", "profile", "trajectory", "patterns", "proposals", "friction"], "default": "all"}
                }
            }),
        ),

    ]
}
