// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module kb)

use serde_json::json;
use crate::ToolDefinition;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_kb_query =====
        ToolDefinition::new(
            "mission_kb_query",
            "知识库查询(统一入口)。search: FTS5+Embedding 混合 RRF; get: 按 key 精确查询; list: 列出条目",
            json!({
                "type": "object",
                "properties": {
                    "action": {"type": "string", "enum": ["search", "get", "list"], "default": "search"},
                    "query": {"type": "string", "description": "[search] 搜索关键词"},
                    "category": {"type": "string", "description": "[search/list] 分类过滤"},
                    "limit": {"type": "integer", "description": "[search/list] 返回条数上限(最大 50)", "default": 10},
                    "offset": {"type": "integer", "description": "[search/list] 分页偏移", "default": 0},
                    "compact": {"type": "boolean", "description": "[list] 紧凑模式: 只返回 key/category/summary 骨架", "default": false},
                    "search_mode": {"type": "string", "description": "[search] exact=纯相关性; explore=含 MMR 多样性", "enum": ["exact", "explore"], "default": "explore"},
                    "key": {"type": "string", "description": "[get] 精确 key"}
                }
            }),
        ),

        // ===== mission_kb_remember =====
        ToolDefinition::new(
            "mission_kb_remember",
            "记录知识到长期记忆。key 已存在则更新。主动调用无需许可",
            json!({
                "type": "object",
                "required": ["category", "key", "summary"],
                "properties": {
                    "category": {"type": "string", "enum": ["preference", "memory", "memory:architecture", "memory:bugfix", "memory:debug", "memory:ops", "memory:feature", "memory:decision", "memory:platform", "project", "architecture", "architecture:summary", "decision", "policy:decision", "feature", "infra", "procedure"]},
                    "key": {"type": "string", "description": "唯一标识"},
                    "summary": {"type": "string", "description": "结论性摘要 ≤400字"},
                    "detail": {"type": "object", "description": "结构化详情 JSON"},
                    "source": {"type": "string", "enum": ["conversation", "discovery", "import"], "default": "conversation"},
                    "confidence": {"type": "number", "description": "置信度 0.0-1.0", "default": 1.0}
                }
            }),
        ),

        // ===== mission_kb_mutate =====
        ToolDefinition::new(
            "mission_kb_mutate",
            "知识库写操作。forget: 删除; update: 部分更新; import: 导入",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["forget", "update", "import"]},
                    "key": {"type": "string", "description": "[forget/update] 目标 key"},
                    "keys": {"type": "array", "description": "[forget] 批量删除 key 列表(优先于 key)"},
                    "category": {"type": "string", "description": "[update] 新分类"},
                    "summary": {"type": "string", "description": "[update] 新摘要 ≤400字"},
                    "detail": {"type": "object", "description": "[update] 新详情 JSON"},
                    "confidence": {"type": "number", "description": "[update] 新置信度"},
                    "linked_task_id": {"type": "string", "description": "[update] 关联 Board 任务 ID(空串清除)"},
                    "format": {"type": "string", "description": "[import] 导入格式", "enum": ["servers_yaml", "json"]},
                    "path": {"type": "string", "description": "[import] 文件路径"}
                }
            }),
        ),

        // ===== mission_kb_ops =====
        ToolDefinition::new(
            "mission_kb_ops",
            "知识库运维。gc: 治理; analyze: AI分析; discover: SSH探测; queue_status/execute_plan: 操作队列; compact: 清理低质量",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["gc", "analyze", "discover", "queue_status", "execute_plan", "compact"]},
                    "gc_action": {"type": "string", "description": "[gc] stats/stale/duplicates/clean_stale/clean_duplicates"},
                    "days": {"type": "integer", "description": "[gc] stale 天数阈值(默认 30)"},
                    "mode": {"type": "string", "description": "[analyze] 分析模式", "enum": ["overview", "consolidation_plan", "custom"]},
                    "target_category": {"type": "string", "description": "[analyze] 按分类过滤(前缀匹配)"},
                    "limit": {"type": "integer", "description": "[analyze/execute_plan] 每次最大条目数"},
                    "offset": {"type": "integer", "description": "[analyze] 分页偏移"},
                    "include_board_context": {"type": "boolean", "description": "[analyze] 注入 Board 任务上下文"},
                    "custom_prompt": {"type": "string", "description": "[analyze] 自定义分析 prompt(mode=custom)"},
                    "model": {"type": "string", "description": "[analyze] 使用的模型"},
                    "max_tokens": {"type": "integer", "description": "[analyze] 最大响应 token 数(默认 16384)"},
                    "save_plan": {"type": "boolean", "description": "[analyze] consolidation_plan 自动保存到队列", "default": true},
                    "task_id": {"type": "string", "description": "[analyze] 关联 Board 任务 ID"},
                    "host": {"type": "string", "description": "[discover] SSH 目标: user@ip 或 infra key"},
                    "port": {"type": "integer", "description": "[discover] SSH 端口", "default": 22},
                    "password": {"type": "string", "description": "[discover] SSH 密码(不填用密钥)"},
                    "plan_id": {"type": "string", "description": "[queue_status/execute_plan] 批次 ID"},
                    "status": {"type": "string", "description": "[queue_status] pending/running/done/skipped/failed"},
                    "dryRun": {"type": "boolean", "description": "[compact] 预览模式", "default": true}
                }
            }),
        ),

        // ===== mission_beacon =====
        ToolDefinition::new(
            "mission_beacon",
            "代码信标操作。list: 列出所有; map: 获取拓扑 L3; upsert: 打/更新标签",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["list", "map", "upsert"]},
                    "name": {"type": "string", "description": "[map/upsert] 信标名称"},
                    "file_path": {"type": "string", "description": "[upsert] 文件路径"},
                    "symbol": {"type": "string", "description": "[upsert] 目标函数/结构体名称"},
                    "feature": {"type": "string", "description": "[upsert] 信标名称(新建时必填)"},
                    "annotation": {"type": "string", "description": "[upsert] 人工注释"}
                }
            }),
        ),

        // ===== mission_code_search =====
        ToolDefinition::new(
            "mission_code_search",
            "搜索代码结构 L3(AST 索引)。tree-sitter 提取的签名和调用关系",
            json!({
                "type": "object",
                "required": ["query"],
                "properties": {
                    "query": {"type": "string", "description": "搜索查询(函数名/结构体名/自然语言)"},
                    "repo": {"type": "string", "description": "限定仓库名"},
                    "file_path": {"type": "string", "description": "限定文件路径前缀"},
                    "node_type": {"type": "string", "enum": ["function", "struct", "enum", "impl", "trait", "mod", "const", "type"]},
                    "limit": {"type": "integer", "default": 20}
                }
            }),
        ),

    ]
}
