// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module memory_ops)

use crate::ToolDefinition;
use serde_json::json;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_memory =====
        ToolDefinition::new(
            "mission_memory",
            "记忆与 Token 管理。pending: 待分析对话; pause: 暂停/恢复; token_stats: Token 消耗统计",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["pending", "pause", "token_stats"]},
                    "paused": {"type": "boolean", "description": "[pause] true=暂停, false=恢复, 省略=toggle"},
                    "sessionId": {"type": "string", "description": "[token_stats] 按会话 ID 过滤"},
                    "slotId": {"type": "string", "description": "[token_stats] 按工位 ID 过滤"},
                    "since": {"type": "string", "description": "[token_stats] 时间过滤 ISO 8601"},
                    "groupBy": {"type": "string", "description": "[token_stats] 聚合维度", "enum": ["session", "slot", "model", "day"]}
                }
            }),
        ),
    ]
}
