// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module skill)

use serde_json::json;
use crate::ToolDefinition;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_skill_query =====
        ToolDefinition::new(
            "mission_skill_query",
            "Skill 知识库查询。list/search/topics/actions/stats",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["list", "search", "topics", "actions", "stats"]},
                    "query": {"type": "string", "description": "[search] 搜索关键词"},
                    "skill": {"type": "string", "description": "按 Skill 名筛选"}
                }
            }),
        ),

        // ===== mission_skill_context =====
        ToolDefinition::new(
            "mission_skill_context",
            "Skill 上下文构建。build: 简单匹配; resolve: 递归聚合含 requires 依赖",
            json!({
                "type": "object",
                "required": ["action", "query"],
                "properties": {
                    "action": {"type": "string", "enum": ["build", "resolve"]},
                    "query": {"type": "string", "description": "任务关键词/描述"},
                    "skill": {"type": "string", "description": "直接指定 skill name 跳过搜索"},
                    "project_id": {"type": "string", "description": "[resolve] 项目 ID，用于优先匹配项目 skill 并返回项目上下文"},
                    "project": {"type": "string", "description": "[resolve] project_id alias"},
                    "include_board": {"type": "boolean", "description": "[resolve] 包含 Board 相关任务"},
                    "include_kb": {"type": "boolean", "description": "[resolve] 显式包含 KB 记忆；默认 false，避免噪声预加载"}
                }
            }),
        ),

        // ===== mission_skill_mutate =====
        ToolDefinition::new(
            "mission_skill_mutate",
            "Skill 写操作。upsert: 创建/更新章节; record: 记录碎片; render: 重建 .md; rollback: 回滚",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["upsert", "record", "render", "rollback"]},
                    "topic": {"type": "string", "description": "Skill 主题名"},
                    "section_title": {"type": "string", "description": "[upsert] 章节标题"},
                    "content": {"type": "string", "description": "[upsert/record] 内容"},
                    "sort_order": {"type": "integer", "description": "[upsert] 章节排序"},
                    "skill": {"type": "string", "description": "[rollback] Skill 名称"},
                    "version_id": {"type": "integer", "description": "[rollback] 版本 ID"}
                }
            }),
        ),

        // ===== mission_skill_exec =====
        ToolDefinition::new(
            "mission_skill_exec",
            "执行 Skill 中定义的 workflow。顺序执行 MCP 工具步骤",
            json!({
                "type": "object",
                "required": ["skill", "action"],
                "properties": {
                    "skill": {"type": "string", "description": "Skill 名称"},
                    "action": {"type": "string", "description": "Action ID(workflow block id)"},
                    "dry_run": {"type": "boolean", "description": "预览模式", "default": false},
                    "params": {"type": "object", "description": "运行时参数覆盖(注入为 ${key})"}
                }
            }),
        ),

    ]
}
