// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module infra)

use crate::ToolDefinition;
use serde_json::json;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_infra_query =====
        ToolDefinition::new(
            "mission_infra_query",
            "基础设施查询。list/get/health/reconcile/skill_evidence/credential_refs/diagnostic_profiles。skills 只是 evidence；凭据只返回 secret_ref，不返回明文值；远程诊断只返回 deploy-center 只读 profile 要求，不直接执行 raw agent。",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["list", "get", "health", "reconcile", "skill_evidence", "credential_refs", "diagnostic_profiles"]},
                    "id": {"type": "string", "description": "[get] 服务器 ID"},
                    "target_id": {"type": "string", "description": "[skill_evidence/credential_refs/diagnostic_profiles] runtime target ID"},
                    "service_id": {"type": "string", "description": "[diagnostic_profiles] 服务 ID"},
                    "profile": {"type": "string", "description": "[diagnostic_profiles] deploy_provenance_snapshot/container_inventory/dependency_manifest_scan/supply_chain_ioc_scan"},
                    "skill": {"type": "string", "description": "[skill_evidence] 限定 skill 名称"},
                    "query": {"type": "string", "description": "[skill_evidence/credential_refs] 查询文本；无 target_id/skill 时用于相关性过滤"},
                    "project_id": {"type": "string", "description": "[skill_evidence/credential_refs] 项目 ID；无 target_id/skill 时用于项目相关性过滤"},
                    "projectId": {"type": "string", "description": "project_id alias"},
                    "project": {"type": "string", "description": "project_id alias"},
                    "limit": {"type": "integer", "description": "[skill_evidence] 最大返回条数"},
                    "role": {"type": "string", "description": "[list] 角色: build/deploy/gpu/vpn/production"},
                    "provider": {"type": "string", "description": "[list] 云厂商: gcp/aliyun/self-hosted"}
                }
            }),
        ),
        // ===== mission_infra_ops =====
        ToolDefinition::new(
            "mission_infra_ops",
            "基础设施运维。health/reachability/diagnose",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["health", "reachability", "diagnose"]},
                    "target": {"type": "string", "description": "[reachability/diagnose] Infra ID 或 user@host"},
                    "channels": {"type": "array", "description": "[reachability] 探测通道: lan_ping/public_ping/tailscale/ssh/deploy_agent"},
                    "checks": {"type": "array", "description": "[diagnose] 检查项: system/crashes/top_cpu/temperatures/journal_errors/docker/network/gpu"}
                }
            }),
        ),
    ]
}
