// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module infra)

use crate::ToolDefinition;
use serde_json::json;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_infra_query =====
        ToolDefinition::new(
            "mission_infra_query",
            "基础设施查询。list: 列出服务器; get: 单个详情",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["list", "get"]},
                    "id": {"type": "string", "description": "[get] 服务器 ID"},
                    "role": {"type": "string", "description": "[list] 角色: build/deploy/gpu/vpn/production"},
                    "provider": {"type": "string", "description": "[list] 云厂商: gcp/aliyun/self-hosted"}
                }
            }),
        ),
        // ===== mission_infra_ops =====
        ToolDefinition::new(
            "mission_infra_ops",
            "基础设施运维。health/reachability/diagnose",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["health", "reachability", "diagnose"]},
                    "target": {"type": "string", "description": "[reachability/diagnose] Infra ID 或 user@host"},
                    "channels": {"type": "array", "description": "[reachability] 探测通道: lan_ping/public_ping/tailscale/ssh/deploy_agent"},
                    "checks": {"type": "array", "description": "[diagnose] 检查项: system/crashes/top_cpu/temperatures/journal_errors/docker/network/gpu"}
                }
            }),
        ),
    ]
}
