// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module permission)

use serde_json::json;
use crate::ToolDefinition;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_permission_query =====
        ToolDefinition::new(
            "mission_permission_query",
            "权限查询。get: 获取配置; learned_list: 已学习的权限规则; merged_for_slot: 返回某工位 spawn 时可见的权限 union(global+role+project+slot)",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["get", "learned_list", "merged_for_slot"]},
                    "scopeType": {"type": "string", "description": "[learned_list] 作用域类型", "enum": ["role", "slot", "project", "global"]},
                    "scopeId": {"type": "string", "description": "[learned_list] 作用域 ID"},
                    "slotId": {"type": "string", "description": "[merged_for_slot] 工位 ID — 返回该工位角色+cwd→project+slot 维度的 learned union 以及静态规则"}
                }
            }),
        ),

        // ===== mission_permission_mutate =====
        ToolDefinition::new(
            "mission_permission_mutate",
            "权限写操作。set_role/set_slot/auto_allow/reload/revoke",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["set_role", "set_slot", "auto_allow", "reload", "revoke"]},
                    "role": {"type": "string", "description": "[set_role/auto_allow] 角色名称"},
                    "slotId": {"type": "string", "description": "[set_slot/auto_allow] 工位 ID"},
                    "rule": {"type": "object", "description": "[set_role/set_slot] 权限规则{auto_allow,require_confirm,deny}"},
                    "pattern": {"type": "string", "description": "[auto_allow] 工具模式(如 secret_*)"},
                    "scopeType": {"type": "string", "description": "[revoke] 作用域类型", "enum": ["role", "slot"]},
                    "scopeId": {"type": "string", "description": "[revoke] 作用域 ID"},
                    "toolPattern": {"type": "string", "description": "[revoke] 工具名称或模式"}
                }
            }),
        ),

    ]
}
