// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module power)

use crate::ToolDefinition;
use serde_json::json;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_power_control =====
        ToolDefinition::new(
            "mission_power_control",
            "物理服务器电源管控。wake(WoL/gcloud)/suspend/status",
            json!({
                "type": "object",
                "required": ["target", "action"],
                "properties": {
                    "target": {"type": "string", "description": "服务器 ID(如 win-3090ti/ecs/gcp-prod)"},
                    "action": {"type": "string", "enum": ["wake", "suspend", "status"]}
                }
            }),
        ),
    ]
}
