// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module system)

use crate::ToolDefinition;
use serde_json::json;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_sys_logs =====
        ToolDefinition::new(
            "mission_sys_logs",
            "读取 MissionD daemon 运行日志尾部",
            json!({
                "type": "object",
                "properties": {
                    "lines": {"type": "integer", "description": "返回尾部行数(默认 50, 最大 500)"},
                    "level": {"type": "string", "description": "日志级别过滤", "enum": ["all", "warn", "error"], "default": "all"},
                    "grep": {"type": "string", "description": "关键词过滤(大小写不敏感)"}
                }
            }),
        ),

        // ===== mission_sys_config =====
        ToolDefinition::new(
            "mission_sys_config",
            "结构化配置管理。读取/修改 slots.yaml/llm.yaml/permissions.yaml",
            json!({
                "type": "object",
                "properties": {
                    "action": {"type": "string", "enum": ["get", "patch", "list"], "default": "get"},
                    "file": {"type": "string", "description": "[get/patch] 配置文件", "enum": ["slots.yaml", "llm.yaml", "permissions.yaml"]},
                    "path": {"type": "string", "description": "[patch] JSON Pointer(如 /slots/0/description)"},
                    "value": {"type": "object", "description": "[patch] 新值(任意 JSON)"}
                }
            }),
        ),

        // ===== mission_daemon_update =====
        ToolDefinition::new(
            "mission_daemon_update",
            "一键更新 MissionD daemon。默认异步启动 build/deploy job；skip_build=true 使用已构建二进制同步重启",
            json!({
                "type": "object",
                "properties": {
                    "confirm": {"type": "boolean", "description": "必须显式为 true；防止主控或工位误触发 daemon 重建/重启", "default": false},
                    "skip_build": {"type": "boolean", "description": "跳过 cargo build，使用 target/release/missiond 同步替换并重启", "default": false}
                }
            }),
        ),

    ]
}
