// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-pure-utility.lisp (pure-utility semantic-parsing)
// Pattern: pure-utility (algorithm isolation chamber)
//
// Implement the trait in custom.rs — only pure functions allowed.

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in custom.rs
// ═══════════════════════════════════════════════════════════

pub trait SemanticParsing {
    /// Check if a character is a known spinner glyph (braille dots, bars, etc)
    fn is_spinner_char(c: char) -> bool;

    /// Split comma-separated arguments respecting quoted strings
    fn split_args(input: &str) -> Vec<String>;

    /// Parse phase hint (thinking/tool) from status bar parenthesized content like '3m 2s · thinking'
    fn extract_phase_from_parens(parens_content: &str) -> Option<String>;

    /// Strip box-drawing characters and trim line for text analysis
    fn sanitize_line(line: &str) -> String;

    /// Detect (Ns · or (Nm Ns · timer pattern indicating active processing
    fn has_activity_timer(line: &str) -> bool;

    /// Check if terminal screen shows an idle prompt (❯ or > at bottom)
    fn is_idle_prompt(lines: &[&str]) -> bool;
}
