// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent.lisp (domain-engine llm-gateway)
// Pattern: domain-engine (zero internal logic)
//
// Implement EngineLogic trait in custom.rs — all business logic lives there.

use anyhow::Result;
use async_trait::async_trait;


pub struct LlmGateway {
    pub(crate) gemini: GeminiGateway,
    pub(crate) sonnet: SonnetHandle,
    pub(crate) minimax: Option<MinimaxHandle>,
    pub(crate) request_count: AtomicU64,
}

impl LlmGateway {
    pub fn new(gemini: GeminiGateway, sonnet: SonnetHandle, minimax: Option<MinimaxHandle>) -> Self {
        Self {
            gemini,
            sonnet,
            minimax,
            request_count: AtomicU64::new(0),
        }
    }
}

// ═══════════════════════════════════════════════════════════
// 🤖 GENERATED CONTRACT — implement in custom.rs
// ═══════════════════════════════════════════════════════════

#[async_trait]
pub trait LlmGatewayLogic {
    /// Route an interactive LLM request to the best provider
    async fn route_interactive(&self, prompt: &str, model: &str) -> Result<String>;

    /// Generate embedding vector via the embedding channel
    async fn route_embedding(&self, text: &str) -> Result<Vec<f32>>;

    /// Route a translation request
    async fn route_translation(&self, text: &str, target_lang: &str) -> Result<String>;

}

