// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module conversation)

use crate::ToolDefinition;
use serde_json::json;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_conversation_query =====
        ToolDefinition::new(
            "mission_conversation_query",
            "对话统一查询。list/get/search/message_search/context/events/audit_classification/backfill_classification/audit_message_roles/backfill_message_roles/turn_backfill/gemini_reconcile",
            json!({
                "type": "object",
                "properties": {
                    "action": {"type": "string", "enum": ["list", "get", "search", "message_search", "context", "events", "audit_classification", "backfill_classification", "audit_message_roles", "backfill_message_roles", "turn_backfill", "gemini_reconcile"], "default": "list"},
                    "status": {"type": "string", "description": "[list] active/completed"},
                    "conversationType": {"type": "string", "description": "[list] user/worker/meta/system/all"},
                    "taskId": {"type": "string", "description": "[list] 按 Board 任务 ID 过滤"},
                    "sessionId": {"type": "string", "description": "[get/search/events/audit_message_roles/backfill_message_roles/turn_backfill] 会话 ID"},
                    "tail": {"type": "integer", "description": "[get] 最近 N 条消息", "default": 50},
                    "sinceId": {"type": "integer", "description": "[get] 增量拉取(ID 大于此值)"},
                    "includeRaw": {"type": "boolean", "description": "[get] 完整消息含 rawContent/model", "default": false},
                    "query": {"type": "string", "description": "[search/message_search] 搜索关键词"},
                    "queryMode": {"type": "string", "description": "[search] 搜索模式", "enum": ["hybrid", "fts", "semantic"], "default": "hybrid"},
                    "timeRange": {"type": "string", "description": "[search/message_search] 时间范围", "enum": ["last_24h", "last_7d", "last_30d"]},
                    "project": {"type": "string", "description": "[search] 项目过滤"},
                    "excludeSessionId": {"type": "string", "description": "[search] 排除特定会话"},
                    "offset": {"type": "integer", "description": "[search] 分页偏移"},
                    "role": {"type": "string", "description": "[message_search] 消息角色", "enum": ["user", "assistant", "tool_result", "system", "thinking"]},
                    "toolName": {"type": "string", "description": "[message_search] 工具名过滤"},
                    "messageId": {"type": "integer", "description": "[context] 锚点消息 ID"},
                    "before": {"type": "integer", "description": "[context] 锚点前取几条(最大 50)", "default": 3},
                    "after": {"type": "integer", "description": "[context] 锚点后取几条(最大 50)", "default": 5},
                    "eventType": {"type": "string", "description": "[events] 事件类型过滤"},
                    "limit": {"type": "integer", "description": "[list/search/message_search/events] 最大返回数"},
                    "since": {"type": "string", "description": "[list] 起始时间(ISO/相对格式)"},
                    "until": {"type": "string", "description": "[list] 结束时间"},
                    "source": {"type": "string", "description": "[audit_classification/backfill_classification] provider source filter, e.g. claude_code"},
                    "minConfidence": {"type": "number", "description": "[audit_classification/backfill_classification] minimum confidence threshold"},
                    "apply": {"type": "boolean", "description": "[backfill_classification/backfill_message_roles] true to write reviewed repairs"},
                    "rebuildTurns": {"type": "boolean", "description": "[backfill_classification/backfill_message_roles] rebuild conversation_turns after repair"}
                }
            }),
        ),

        // ===== mission_conversation_analyze =====
        ToolDefinition::new(
            "mission_conversation_analyze",
            "对话分析。retrospective: 会话复盘; trajectory: 子 Agent 思维链; activity: 活动报告",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["retrospective", "trajectory", "activity"]},
                    "sessionId": {"type": "string", "description": "[retrospective] 会话 ID"},
                    "depth": {"type": "string", "description": "[retrospective] 分析深度", "enum": ["quick", "detailed", "full"], "default": "quick"},
                    "toolUseId": {"type": "string", "description": "[trajectory] 父 tool_use ID"},
                    "since": {"type": "string", "description": "[activity] 起始时间"},
                    "until": {"type": "string", "description": "[activity] 结束时间"},
                    "limit": {"type": "integer", "description": "[trajectory] 最大返回数", "default": 200}
                }
            }),
        ),

        // ===== mission_conversation_reconcile =====
        ToolDefinition::new(
            "mission_conversation_reconcile",
            "JSONL-DB 对账。不传 sessionId 触发全量扫描",
            json!({
                "type": "object",
                "properties": {
                    "sessionId": {"type": "string", "description": "指定会话 ID 立即对账"}
                }
            }),
        ),

        // ===== mission_retrospective_manage =====
        ToolDefinition::new(
            "mission_retrospective_manage",
            "复盘管理。list: 已完成复盘; backfill: 批量回填",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["list", "backfill"]},
                    "limit": {"type": "integer", "description": "[list] 最大返回数", "default": 10},
                    "since": {"type": "string", "description": "[backfill] 起始时间 ISO datetime"}
                }
            }),
        ),

        // ===== mission_embedding_ops =====
        ToolDefinition::new(
            "mission_embedding_ops",
            "Embedding 操作。stats: 覆盖率统计; backfill: 触发回填",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["stats", "backfill"]}
                }
            }),
        ),

    ]
}
