// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module router_chat)

use crate::ToolDefinition;
use serde_json::json;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_router_chat =====
        ToolDefinition::new(
            "mission_router_chat",
            "通过 AI 路由器与 Gemini 等模型多轮对话。传 task_id 自动持久化历史",
            json!({
                "type": "object",
                "properties": {
                    "messages": {"type": "array", "description": "本轮新消息(传 task_id 时历史自动加载)"},
                    "message": {"type": "string", "description": "单条 user 消息(便捷模式，与 messages 二选一)"},
                    "task_id": {"type": "string", "description": "关联 Board 任务 ID(自动加载/保存历史)"},
                    "context": {"type": "string", "description": "自动注入上下文", "enum": ["board", "kb", "both", "none"], "default": "none"},
                    "model": {"type": "string", "description": "模型(不传用 Router 默认)"},
                    "max_tokens": {"type": "integer", "default": 16384},
                    "search": {"type": "boolean", "description": "启用 Google 搜索增强", "default": false},
                    "files": {"type": "array", "description": "本地文件路径列表(≤1MB 文本, ≤10MB 二进制)"},
                    "idle_timeout": {"type": "integer", "description": "CLI 模式空闲超时秒数", "default": 600},
                    "channel": {"type": "string", "description": "Gemini 认证渠道", "enum": ["apikey", "google"]},
                    "api_key_alias": {"type": "string", "description": "指定 API key 别名"}
                }
            }),
        ),
        // ===== mission_router_chat_manage =====
        ToolDefinition::new(
            "mission_router_chat_manage",
            "Gemini 对话管理。history/list/delete/clear/delete_message/restore/stats/compress",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["history", "list", "delete", "clear", "delete_message", "restore", "stats", "compress"]},
                    "task_id": {"type": "string", "description": "[history/delete/clear/compress] Board 任务 ID"},
                    "conversation_id": {"type": "string", "description": "[delete/clear/restore/compress] 对话 ID"},
                    "message_id": {"type": "integer", "description": "[delete_message] 消息 ID"},
                    "count": {"type": "integer", "description": "[clear] 清理最后 N 条(-1=全部)", "default": 2},
                    "limit": {"type": "integer", "description": "[list] 最大返回数", "default": 50},
                    "batch_size": {"type": "integer", "description": "[compress] 压缩批次大小", "default": 20},
                    "keep_recent": {"type": "integer", "description": "[compress] 保留最近 N 条不压缩", "default": 10}
                }
            }),
        ),
    ]
}
