// 🤖 GENERATED BY FORGE - DO NOT EDIT
// Source: .missiond/intent-tools.lisp (module timeline)

use serde_json::json;
use crate::ToolDefinition;

pub fn definitions() -> Vec<ToolDefinition> {
    vec![
        // ===== mission_timeline =====
        ToolDefinition::new(
            "mission_timeline",
            "系统时间轴。query/trace/stats/search",
            json!({
                "type": "object",
                "required": ["action"],
                "properties": {
                    "action": {"type": "string", "enum": ["query", "trace", "stats", "search"]},
                    "eventType": {"type": "string", "description": "[query] 事件类型过滤"},
                    "traceId": {"type": "string", "description": "[query/trace] 因果链 trace_id"},
                    "since": {"type": "string", "description": "起始时间(相对格式 1h/24h/7d 或 ISO)"},
                    "until": {"type": "string", "description": "结束时间"},
                    "limit": {"type": "integer", "description": "[query/search] 返回条数", "default": 50},
                    "offset": {"type": "integer", "description": "[query] 分页偏移", "default": 0},
                    "keyword": {"type": "string", "description": "[search] 搜索关键字"}
                }
            }),
        ),

    ]
}
